// Iriarte ERP V2 · núcleo unificado
(function(){
'use strict';

const SUPABASE_URL='https://kzmjeccivhkhtuokfkta.supabase.co';
const SUPABASE_KEY='sb_publishable_YBf9vRaOlVQBHM4ionZLPw_TIIxZY9G';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
if(!window.__iriarteDb)window.__iriarteDb=sb;

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v||0));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const sum=(a,f)=>a.reduce((n,x)=>n+num(f(x)),0);
const today=()=>new Date().toISOString().slice(0,10);

const NAV=[['inicio','Inicio'],['clientes','Clientes'],['proyectos','Proyectos'],['presupuestos','Presupuestos'],['facturas','Facturas'],['proveedores','Proveedores'],['compras','Compras'],['obra','Obra'],['horas','Horas'],['documentos','Documentos'],['finanzas','Finanzas'],['gastos','Gastos generales'],['informes','Informes']];
const S={route:'inicio',user:null,profile:null,data:{clientes:[],proyectos:[],presupuestos:[],facturas:[],lineas:[],proveedores:[],compras:[],cobros:[],pagos:[],horas:[],visitas:[],tareas:[],incidencias:[],docs:[],gastos:[],movs:[]},sel:{},budgetView:'edit',budgetKind:'obra',budgetFilter:'todos'};
window.APP=S;

function toast(msg,bad=false){const t=$('#toast');if(!t)return;t.textContent=msg;t.style.background=bad?'#8f4d3c':'#253120';t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
function badge(s='—'){const v=String(s||'—'),c=/cobrad|pagad|acept|final|complet|resuelt/i.test(v)?'good':/anulad|cancel|venc|rechaz/i.test(v)?'bad':'warn';return `<span class="badge ${c}">${esc(v.replaceAll('_',' '))}</span>`}
function empty(t='No hay datos todavía.'){return `<div class="empty">${esc(t)}</div>`}
function kpi(l,v,n){return `<div class="card kpi"><small>${esc(l)}</small><strong class="${typeof n==='number'?(n<0?'negative':'positive'):''}">${v}</strong></div>`}
function info(l,v){return `<div class="info"><small>${esc(l)}</small><b>${esc(v??'—')}</b></div>`}
function btn(t,a,c=''){return `<button class="btn ${c}" data-action="${esc(a)}">${esc(t)}</button>`}
function pageHead(t,a=''){return `<div class="page-head"><h1>${esc(t)}</h1><div class="grow"></div><div class="toolbar">${a}</div></div>`}
function options(arr,val,label=x=>x.nombre||x.name||''){return `<option value="">—</option>`+(arr||[]).map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(val)?'selected':''}>${esc(label(x))}</option>`).join('')}
function clientName(id){return S.data.clientes.find(x=>String(x.id)===String(id))?.nombre||'—'}
function projectName(id){return S.data.proyectos.find(x=>String(x.id)===String(id))?.nombre||'—'}
function supplierName(id){return S.data.proveedores.find(x=>String(x.id)===String(id))?.nombre||'—'}
function filtered(arr,key='proyecto_id'){return S.sel.project?(arr||[]).filter(x=>String(x[key]??x.project_id??'')===String(S.sel.project)):(arr||[])}

async function selectSafe(table,order){try{let q=sb.from(table).select('*');if(order)q=q.order(order,{ascending:false});const {data,error}=await q;if(error)throw error;return data||[]}catch(e){console.warn('Carga',table,e.message);return[]}}
async function loadAll(){
  const [clientes,proyectos,presupuestos,facturas,lineas,proveedores,compras,cobros,pagos,horas,visitas,tareas,incidencias,docs,gastos,movs]=await Promise.all([
    selectSafe('clientes','updated_at'),selectSafe('v_proyectos_operativos','updated_at'),selectSafe('presupuestos','updated_at'),selectSafe('facturas','fecha'),selectSafe('factura_lineas','orden'),selectSafe('proveedores','updated_at'),selectSafe('compras','fecha'),selectSafe('cobros','fecha'),selectSafe('pagos','fecha'),selectSafe('horas_proyecto','fecha'),selectSafe('obra_visitas','fecha'),selectSafe('obra_tareas','created_at'),selectSafe('obra_incidencias','created_at'),selectSafe('documentos','created_at'),selectSafe('gastos_generales','fecha'),selectSafe('movimientos_financieros','fecha')
  ]);
  S.data={clientes,proyectos,presupuestos,facturas,lineas,proveedores,compras,cobros,pagos,horas,visitas,tareas,incidencias,docs,gastos,movs};
  if(S.sel.project&&!proyectos.some(x=>String(x.id)===String(S.sel.project)))S.sel.project='';
}
window.reloadIriarte=async()=>{await loadAll();render()};

function renderNav(){const n=$('#main-nav');if(!n)return;n.innerHTML=NAV.map(([k,l])=>`<a class="nav-item ${S.route===k?'active':''}" href="#${k}" data-route="${k}">${l}</a>`).join('')}
function routeTo(r){S.route=NAV.some(x=>x[0]===r)?r:'inicio';if(location.hash!=='#'+S.route)history.replaceState(null,'','#'+S.route);render()}
window.iriarteRoute=routeTo;

function modal(title,body,onSave,save='Guardar'){
  const root=$('#modal-root');if(!root)return;
  root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-core-close>Cerrar</button></div><form id="core-modal-form"><div class="modal-body">${body}<div id="core-modal-error"></div></div><div class="modal-foot"><button type="button" class="btn" data-core-close>Cancelar</button><button class="btn primary" type="submit">${esc(save)}</button></div></form></div></div>`;
  const close=()=>root.innerHTML='';root.querySelectorAll('[data-core-close]').forEach(b=>b.onclick=close);
  $('#core-modal-form').onsubmit=async e=>{e.preventDefault();const submit=e.submitter;submit.disabled=true;try{const vals=Object.fromEntries(new FormData(e.currentTarget).entries());const ok=await onSave(vals);if(ok!==false){close();await loadAll();render();toast('Guardado')}}catch(err){$('#core-modal-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`}finally{submit.disabled=false}};
}

function renderDashboard(){
  const inv=S.data.facturas.filter(x=>x.estado!=='anulada'),pur=S.data.compras.filter(x=>x.estado!=='anulada');
  const fb=sum(inv,x=>x.base),cb=sum(pur,x=>x.base),hc=sum(S.data.horas,x=>num(x.horas)*num(x.coste_hora)),cob=sum(S.data.cobros,x=>x.importe),pag=sum(S.data.pagos,x=>x.importe),gg=sum(S.data.gastos,x=>x.base),m=fb-cb-hc;
  return `<div class="card panel" style="padding:28px;background:linear-gradient(100deg,#31452a,#607a55);color:white;margin-bottom:14px"><h1 style="font:38px Georgia,serif;margin:0 0 5px">Gestión del estudio</h1><p style="margin:0;letter-spacing:2px;font-size:10px">CLIENTE → PRESUPUESTO → PROYECTO → OBRA → FACTURACIÓN → RENTABILIDAD</p></div><div class="grid cols-6">${kpi('Proyectos',S.data.proyectos.length)}${kpi('Facturado base',money(fb))}${kpi('Cobrado',money(cob))}${kpi('Compras base',money(cb))}${kpi('Margen directo',money(m),m)}${kpi('Tesorería',money(cob-pag),cob-pag)}</div><div class="grid cols-2" style="margin-top:14px"><div class="card panel"><h3>Proyectos recientes</h3>${S.data.proyectos.length?`<table class="table"><tr><th>Proyecto</th><th>Cliente</th><th>Estado</th></tr>${S.data.proyectos.slice(0,7).map(p=>`<tr data-open-project="${p.id}" style="cursor:pointer"><td><b>${esc(p.nombre)}</b></td><td>${esc(clientName(p.cliente_id))}</td><td>${badge(p.estado)}</td></tr>`).join('')}</table>`:empty()}</div><div class="card panel"><h3>Resultado interno</h3><div class="info-grid">${info('Margen directo',money(m))}${info('Gastos generales',money(gg))}${info('Resultado',money(m-gg))}</div><p style="color:var(--muted);font-size:12px;margin-top:14px">El margen directo mantiene separados los gastos generales. El resultado interno sí los descuenta.</p></div></div>`;
}

function renderClients(){const rows=S.data.clientes;return pageHead('Clientes',btn('+ Nuevo cliente','new-client','primary'))+(rows.length?`<div class="card panel table-wrap"><table class="table"><tr><th>Nombre</th><th>CIF</th><th>Email</th><th>Teléfono</th><th>Proyectos</th></tr>${rows.map(c=>`<tr><td><b>${esc(c.nombre)}</b></td><td>${esc(c.cif||'')}</td><td>${esc(c.email||'')}</td><td>${esc(c.telefono||'')}</td><td>${S.data.proyectos.filter(p=>String(p.cliente_id)===String(c.id)).length}</td></tr>`).join('')}</table></div>`:empty('No hay clientes todavía.'))}

function renderProjects(){
  const rows=S.data.proyectos,pid=S.sel.project||rows[0]?.id,p=rows.find(x=>String(x.id)===String(pid));if(p)S.sel.project=p.id;
  return pageHead('Proyectos',btn('+ Nuevo proyecto','new-project','primary'))+(rows.length?`<div class="master-detail"><div class="card master"><input class="master-search" data-project-search placeholder="Buscar proyecto…">${rows.map(x=>`<div class="master-item ${String(p?.id)===String(x.id)?'active':''}" data-project-item data-search="${esc((x.nombre+' '+(x.codigo||'')+' '+clientName(x.cliente_id)).toLowerCase())}" data-select-project="${x.id}"><b>${esc(x.nombre)}</b><small>${esc(x.codigo||'')} · ${esc(clientName(x.cliente_id))}</small></div>`).join('')}</div>${renderProjectDetail(p)}</div>`:empty('Todavía no hay proyectos activos.'));
}
function panel(title,rows,fn){return `<div class="card panel"><h3>${esc(title)}</h3>${rows.length?rows.slice(0,10).map(x=>`<div class="master-item">${fn(x)}</div>`).join(''):empty()}</div>`}
function renderProjectDetail(p){
  if(!p)return `<div class="card detail">${empty()}</div>`;
  const inv=filtered(S.data.facturas),pur=filtered(S.data.compras),hrs=filtered(S.data.horas),vis=filtered(S.data.visitas,'project_id'),tas=filtered(S.data.tareas,'project_id'),inc=filtered(S.data.incidencias,'project_id'),docs=filtered(S.data.docs),bud=S.data.presupuestos.filter(x=>String(x.proyecto_id||'')===String(p.id));
  const fb=sum(inv,x=>x.base),cb=sum(pur,x=>x.base),hc=sum(hrs,x=>num(x.horas)*num(x.coste_hora)),m=fb-cb-hc;
  return `<div class="card detail"><div class="page-head"><div><small style="color:var(--muted)">PROYECTO ${esc(p.codigo||'')}</small><h1 style="font-size:27px">${esc(p.nombre)}</h1><div style="color:var(--muted)">${esc(clientName(p.cliente_id))} · ${esc(p.direccion||'')}</div></div><div class="grow"></div>${badge(p.estado)} ${btn('Editar','edit-project')}</div><div class="flow"><button data-project-nav="clientes">Cliente</button><button data-project-nav="presupuestos">Presupuesto</button><button class="active">Proyecto</button><button data-project-nav="obra">Obra</button><button data-project-nav="facturas">Facturación</button><button data-project-nav="finanzas">Rentabilidad</button></div><div class="grid cols-4" style="margin-top:14px">${kpi('Facturado base',money(fb))}${kpi('Compras base',money(cb))}${kpi('Coste horas',money(hc))}${kpi('Margen directo',money(m),m)}</div><div class="grid cols-2" style="margin-top:14px">${panel('Presupuestos',bud,x=>`${esc(x.name||x.nombre||'Presupuesto')} · ${esc(x.status||x.estado||'')}`)}${panel('Facturas',inv,x=>`${esc(x.numero||'Borrador')} · ${money(x.total)}`)}${panel('Compras',pur,x=>`${esc(x.concepto||x.numero_factura||'Compra')} · ${money(x.total)}`)}${panel('Horas',hrs,x=>`${esc(x.persona||'')} · ${num(x.horas).toFixed(1)} h`)}${panel('Obra',[...vis.map(x=>({...x,_t:'Visita'})),...tas.map(x=>({...x,_t:'Tarea'})),...inc.map(x=>({...x,_t:'Incidencia'}))],x=>`${x._t}: ${esc(x.titulo||x.descripcion||'Registro')}`)}${panel('Documentos',docs,x=>esc(x.nombre||x.archivo_nombre||'Documento'))}</div></div>`;
}

function budgetBase(p){return (p.kind||'obra')==='honorarios'?sum(p.fee_lines||[],x=>x.amount??x.importe):sum(p.items||[],x=>num(x.qty??x.cantidad)*num(x.price??x.precio))}
function budgetVat(p){return (p.kind||'obra')==='honorarios'?sum(p.fee_lines||[],x=>num(x.amount??x.importe)*num(x.vat??x.ivaPct??21)/100):sum(p.items||[],x=>num(x.qty??x.cantidad)*num(x.price??x.precio)*num(x.vat??x.ivaPct??21)/100)}
function budgetIrpf(p){return p.irpf_enabled?budgetBase(p)*num(p.irpf_pct||15)/100:0}
function currentBudget(){return S.data.presupuestos.find(x=>String(x.id)===String(S.sel.budget))||null}
function budgetState(phase){const v=String(phase||'').toLowerCase();if(v.includes('acept'))return'aceptado';if(v.includes('envi'))return'enviado';if(v.includes('rech'))return'rechazado';if(v.includes('anul'))return'anulado';return'borrador'}
function renderBudgetSummary(p){const b=budgetBase(p),v=budgetVat(p),r=budgetIrpf(p);return `<h3 style="font:20px Georgia,serif;margin-top:0">Resumen</h3><div class="info"><small>Base imponible</small><b>${money(b)}</b></div><div style="height:8px"></div><div class="info"><small>IVA</small><b>${money(v)}</b></div>${p.irpf_enabled?`<div style="height:8px"></div><div class="info"><small>IRPF</small><b>− ${money(r)}</b></div>`:''}<div style="font:26px Georgia,serif;margin-top:16px">${money(b+v-r)}</div>`}
function budgetMeta(p){return `<div class="budget-meta"><input data-budget-field="name" value="${esc(p.name||p.nombre||'')}" placeholder="Nombre del presupuesto"><select data-budget-client>${options(S.data.clientes,p.cliente_id,x=>x.nombre)}</select><input data-budget-field="client" value="${esc(p.client||'')}" placeholder="Cliente / contacto"><input data-budget-field="date" type="date" value="${esc(p.date||p.fecha||today())}"><input data-budget-field="address" value="${esc(p.address||'')}" placeholder="Dirección"><input data-budget-field="ref" value="${esc(p.ref||p.numero||'')}" placeholder="Referencia"><select data-budget-field="phase"><option ${String(p.phase||'').toLowerCase()==='borrador'?'selected':''}>Borrador</option><option ${String(p.phase||'').toLowerCase()==='enviado'?'selected':''}>Enviado</option><option ${String(p.phase||'').toLowerCase()==='aceptado'?'selected':''}>Aceptado</option></select></div>`}
function worksEditor(p){p.items=p.items||[];return `${budgetMeta(p)}<div class="budget-line-head"><b>Código</b><b>Sección</b><b>Descripción</b><b>Ubicación</b><b>Ud.</b><b>Cant.</b><b>Precio</b><b>IVA</b><span></span></div>${p.items.map((x,n)=>`<div class="budget-line" data-line="${n}"><input data-k="code" value="${esc(x.code||x.codigo||'')}"><input data-k="section" value="${esc(x.section||x.seccion||'')}"><input data-k="description" value="${esc(x.description||x.descripcion||'')}"><input data-k="location" value="${esc(x.location||x.ubicacion||'')}"><input data-k="unit" value="${esc(x.unit||x.unidad||'ud')}"><input data-k="qty" type="number" step=".001" value="${num(x.qty??x.cantidad)}"><input data-k="price" type="number" step=".01" value="${num(x.price??x.precio)}"><input data-k="vat" type="number" step=".01" value="${num(x.vat??x.ivaPct??21)}"><button class="btn danger" data-remove-line="${n}">×</button></div>`).join('')}<div class="toolbar no-print" style="margin-top:14px"><button class="btn" data-action="add-budget-line">+ Línea</button><button class="btn" data-action="paste-budget">Pegar Excel</button><button class="btn primary" data-action="save-budget">Guardar</button><button class="btn" data-action="budget-to-project">Convertir en proyecto</button><button class="btn" data-action="budget-to-invoice">Crear factura</button></div>`}
function feesEditor(p){p.fee_lines=p.fee_lines||[];return `${budgetMeta(p)}<label style="font-size:11px;color:var(--muted)">Introducción</label><textarea data-budget-field="intro_text" style="min-height:100px">${esc(p.intro_text||'')}</textarea><h3 style="font-family:Georgia,serif">Honorarios</h3>${p.fee_lines.map((x,n)=>`<div class="budget-line" style="grid-template-columns:minmax(260px,1fr) 130px 80px 40px" data-fee-line="${n}"><input data-k="description" value="${esc(x.description||x.concepto||'')}"><input data-k="amount" type="number" step=".01" value="${num(x.amount??x.importe)}"><input data-k="vat" type="number" step=".01" value="${num(x.vat??x.ivaPct??21)}"><button class="btn danger" data-remove-fee="${n}">×</button></div>`).join('')}<div class="toolbar" style="margin-top:14px"><button class="btn" data-action="add-fee-line">+ Honorario</button><button class="btn primary" data-action="save-budget">Guardar</button><button class="btn" data-action="budget-to-project">Convertir en proyecto</button><button class="btn" data-action="budget-to-invoice">Crear factura</button></div>`}
function budgetDoc(p,supplier){const rows=(p.kind||'obra')==='honorarios'?(p.fee_lines||[]).map(x=>({description:x.description||x.concepto,qty:1,unit:'',price:x.amount??x.importe})):(p.items||[]);return `<div class="doc-sheet"><div><small>${supplier?'VISTA PROVEEDOR':'VISTA CLIENTE'}</small><h1>${esc(p.name||p.nombre||'Presupuesto')}</h1><p>${esc(p.client||'')}<br>${esc(p.address||'')}</p></div><table><tr><th>Descripción</th><th>Ud.</th><th>Cant.</th>${supplier?'':'<th class="right">Importe</th>'}</tr>${rows.map(x=>`<tr><td>${esc(x.description||'')}</td><td>${esc(x.unit||'')}</td><td>${num(x.qty||1).toLocaleString('es-ES')}</td>${supplier?'':`<td class="right">${money(num(x.qty||1)*num(x.price))}</td>`}</tr>`).join('')}</table>${supplier?'':`<h2 style="text-align:right">${money(budgetBase(p)+budgetVat(p)-budgetIrpf(p))}</h2>`}</div>`}
function renderBudgets(){
  let rows=S.data.presupuestos.filter(p=>S.budgetFilter==='todos'||(S.budgetFilter==='presupuestos'&&String(p.status||'').toLowerCase()!=='proyecto')||(S.budgetFilter==='proyectos'&&String(p.status||'').toLowerCase()==='proyecto')).filter(p=>S.budgetKind==='obra'?(p.kind||'obra')==='obra':p.kind==='honorarios');
  let p=currentBudget();if(!p||!rows.some(x=>String(x.id)===String(p.id)))p=rows[0]||null;if(p)S.sel.budget=p.id;
  return `${pageHead('Presupuestos')}<div class="budget-layout"><aside class="budget-sidebar"><div class="budget-tabs"><button class="${S.budgetKind==='obra'?'active':''}" data-budget-kind="obra">Obra</button><button class="${S.budgetKind==='honorarios'?'active':''}" data-budget-kind="honorarios">Honorarios</button></div><button class="btn primary" style="width:100%;margin:12px 0" data-action="new-budget">+ Nuevo presupuesto</button><div class="budget-tabs"><button class="${S.budgetFilter==='todos'?'active':''}" data-budget-filter="todos">Todos</button><button class="${S.budgetFilter==='presupuestos'?'active':''}" data-budget-filter="presupuestos">Presupuestos</button><button class="${S.budgetFilter==='proyectos'?'active':''}" data-budget-filter="proyectos">Proyectos</button></div><input class="master-search" data-budget-search placeholder="Buscar proyecto o cliente…" style="margin-top:12px">${rows.map(x=>`<div class="master-item ${String(p?.id)===String(x.id)?'active':''}" data-budget-item="${x.id}" data-search="${esc(((x.name||x.nombre||'')+' '+(x.client||'')).toLowerCase())}"><b>${esc(x.name||x.nombre||'Sin título')}</b><small>${esc(x.client||'')} · ${esc(x.status||x.estado||'')}</small></div>`).join('')}</aside><section class="budget-main"><div class="budget-main-head"><button class="${S.budgetView==='edit'?'active':''}" data-budget-view="edit">Trabajo</button><button class="${S.budgetView==='client'?'active':''}" data-budget-view="client">Vista cliente</button><button class="${S.budgetView==='supplier'?'active':''}" data-budget-view="supplier">Vista proveedor</button></div><div class="budget-content">${p?(S.budgetView==='edit'?((p.kind||'obra')==='honorarios'?feesEditor(p):worksEditor(p)):budgetDoc(p,S.budgetView==='supplier')):empty('Crea o selecciona un presupuesto.')}</div></section><aside class="budget-summary">${p?renderBudgetSummary(p):''}</aside></div>`;
}
async function createBudget(){const kind=S.budgetKind||'obra';const row={nombre:'Nuevo presupuesto',name:'Nuevo presupuesto',kind,fecha:today(),date:today(),estado:'borrador',status:'Borrador',phase:'Borrador',items:[],fee_lines:[],irpf_enabled:false,irpf_pct:15,base:0,total:0};const {data,error}=await sb.from('presupuestos').insert(row).select('*').single();if(error)throw error;await loadAll();S.sel.budget=data.id;S.budgetView='edit';render()}
async function saveBudget(){const p=currentBudget();if(!p)return;const b=budgetBase(p),v=budgetVat(p),r=budgetIrpf(p);const payload={nombre:p.name||p.nombre||'Presupuesto',name:p.name||p.nombre||'Presupuesto',cliente_id:p.cliente_id||null,proyecto_id:p.proyecto_id||null,fecha:p.date||p.fecha||today(),date:p.date||p.fecha||today(),numero:p.ref||p.numero||null,ref:p.ref||p.numero||null,client:p.client||null,address:p.address||null,phase:p.phase||'Borrador',estado:budgetState(p.phase||p.estado),kind:p.kind||'obra',irpf_enabled:!!p.irpf_enabled,irpf_pct:p.irpf_enabled?num(p.irpf_pct||15):0,items:p.items||[],status:p.status||'Borrador',archived:!!p.archived,intro_text:p.intro_text||'',zonas:p.zonas||[],scope_items:p.scope_items||[],redaccion_toggle:p.redaccion_toggle!==false,redaccion_texto:p.redaccion_texto||'',fases_obra:p.fases_obra||[],direccion_resumen:p.direccion_resumen||'',fee_lines:p.fee_lines||[],clausulas:p.clausulas||[],base:b,total:b+v-r,updated_at:new Date().toISOString()};const {error}=await sb.from('presupuestos').update(payload).eq('id',p.id);if(error)throw error;await loadAll();S.sel.budget=p.id;toast('Presupuesto guardado');render()}
function pasteBudget(){const p=currentBudget();if(!p)return;const raw=prompt('Pega filas: Código | Sección | Descripción | Ubicación | Ud. | Cant. | Precio | IVA');if(!raw)return;p.items=p.items||[];raw.split(/\r?\n/).filter(Boolean).forEach(r=>{const a=r.split('\t');p.items.push({code:a[0]||'',section:a[1]||'',description:a[2]||'',location:a[3]||'',unit:a[4]||'ud',qty:num(a[5]||1),price:num(a[6]),vat:a[7]==null?21:num(a[7])})});render()}

function projectSelect(){return `<select class="btn" data-project-filter><option value="">Todos los proyectos</option>${S.data.proyectos.map(p=>`<option value="${p.id}" ${String(S.sel.project)===String(p.id)?'selected':''}>${esc(p.nombre)}</option>`).join('')}</select>`}
function renderInvoices(){const arr=filtered(S.data.facturas);return pageHead('Facturas y cobros',`${projectSelect()} ${btn('+ Nueva factura','new-invoice','primary')}`)+(arr.length?`<div class="card panel table-wrap"><table class="table"><tr><th>Número</th><th>Fecha</th><th>Cliente</th><th>Proyecto</th><th>Base</th><th>Total</th><th>Cobrado</th><th>Estado</th><th></th></tr>${arr.map(x=>{const paid=sum(S.data.cobros.filter(c=>String(c.factura_id)===String(x.id)),c=>c.importe);return `<tr><td><b>${esc(x.numero||'Borrador')}</b></td><td>${esc(x.fecha||'')}</td><td>${esc(clientName(x.cliente_id))}</td><td>${esc(projectName(x.proyecto_id))}</td><td>${money(x.base)}</td><td>${money(x.total)}</td><td>${money(paid)}</td><td>${badge(x.estado)}</td><td>${btn('Editar','edit-invoice:'+x.id)} ${btn('PDF','print-invoice:'+x.id)}</td></tr>`}).join('')}</table></div>`:empty('No hay facturas.'))}
function renderSimple(title,key,cols,newAction){const rows=S.data[key]||[];return pageHead(title,newAction?btn('+ Nuevo',newAction,'primary'):'')+(rows.length?`<div class="card panel table-wrap"><table class="table"><tr>${cols.map(c=>`<th>${esc(c[0])}</th>`).join('')}</tr>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c[2]?c[2](r):esc(r[c[1]]??'—')}</td>`).join('')}</tr>`).join('')}</table></div>`:empty())}
function renderFinance(){const inv=S.data.facturas.filter(x=>x.estado!=='anulada'),pur=S.data.compras.filter(x=>x.estado!=='anulada'),fb=sum(inv,x=>x.base),pb=sum(pur,x=>x.base),hc=sum(S.data.horas,x=>num(x.horas)*num(x.coste_hora)),gg=sum(S.data.gastos,x=>x.base),m=fb-pb-hc;return pageHead('Finanzas',btn('Importar banco','import-bank','primary'))+`<div class="grid cols-4">${kpi('Facturado base',money(fb))}${kpi('Costes directos',money(pb+hc))}${kpi('Margen directo',money(m),m)}${kpi('Resultado interno',money(m-gg),m-gg)}</div><div class="card panel" style="margin-top:14px"><h3>Movimientos financieros</h3>${S.data.movs.length?`<div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Concepto</th><th>Categoría</th><th>Proyecto</th><th>Conciliado</th><th>Importe</th></tr>${S.data.movs.map(x=>`<tr><td>${esc(x.fecha||'')}</td><td>${esc(x.concepto||'')}</td><td>${esc(x.categoria||'')}</td><td>${esc(projectName(x.proyecto_id))}</td><td>${x.conciliado?'Sí':'No'}</td><td>${money((x.tipo==='pago'||x.tipo==='gasto')?-Math.abs(num(x.total)):num(x.total))}</td></tr>`).join('')}</table></div>`:empty('Sin movimientos.')}</div>`}
function renderReports(){const unI=S.data.facturas.filter(x=>!x.proyecto_id).length,unP=S.data.compras.filter(x=>!x.proyecto_id).length,unH=S.data.horas.filter(x=>!x.proyecto_id).length;return pageHead('Informes')+`<div class="notice"><b>Control de fiabilidad:</b> facturas sin proyecto: ${unI} · compras sin proyecto: ${unP} · horas sin proyecto: ${unH}.</div>`+renderFinance().replace(pageHead('Finanzas',btn('Importar banco','import-bank','primary')),'')}

function render(){
  renderNav();const v=$('#app-view');if(!v)return;
  try{
    if(S.route==='inicio')v.innerHTML=renderDashboard();
    else if(S.route==='clientes')v.innerHTML=renderClients();
    else if(S.route==='proyectos')v.innerHTML=renderProjects();
    else if(S.route==='presupuestos')v.innerHTML=renderBudgets();
    else if(S.route==='facturas')v.innerHTML=renderInvoices();
    else if(S.route==='proveedores')v.innerHTML=renderSimple('Proveedores','proveedores',[['Nombre','nombre'],['CIF','cif'],['Email','email'],['Teléfono','telefono']],'new-supplier');
    else if(S.route==='compras')v.innerHTML=renderSimple('Compras y pagos','compras',[['Fecha','fecha'],['Proveedor','proveedor_id',x=>esc(supplierName(x.proveedor_id))],['Proyecto','proyecto_id',x=>esc(projectName(x.proyecto_id))],['Concepto','concepto'],['Total','total',x=>money(x.total)]],'new-purchase');
    else if(S.route==='obra')v.innerHTML=renderSimple('Obra','tareas',[['Proyecto','project_id',x=>esc(projectName(x.project_id))],['Tarea','titulo'],['Estado','estado',x=>badge(x.estado)],['Prioridad','prioridad']],'new-task');
    else if(S.route==='horas')v.innerHTML=renderSimple('Horas','horas',[['Fecha','fecha'],['Persona','persona'],['Proyecto','proyecto_id',x=>esc(projectName(x.proyecto_id))],['Horas','horas'],['Coste/hora','coste_hora',x=>money(x.coste_hora)]],'new-hour');
    else if(S.route==='documentos')v.innerHTML=renderSimple('Documentos','docs',[['Nombre','nombre'],['Proyecto','proyecto_id',x=>esc(projectName(x.proyecto_id))],['Tipo','tipo'],['Fecha','created_at',x=>esc((x.fecha_documento||x.created_at||'').slice(0,10))]],'new-doc');
    else if(S.route==='finanzas')v.innerHTML=renderFinance();
    else if(S.route==='gastos')v.innerHTML=renderSimple('Gastos generales','gastos',[['Fecha','fecha'],['Categoría','categoria'],['Concepto','concepto'],['Base','base',x=>money(x.base)],['Total','total',x=>money(x.total)]],'new-overhead');
    else v.innerHTML=renderReports();
    bindDynamic();
  }catch(err){console.error(err);v.innerHTML=`${pageHead('Error de módulo')}<div class="notice" style="background:#f6dfd7;color:#8f4d3c"><b>No se pudo renderizar esta sección.</b><br>${esc(err.message||err)}</div>`}
}
window.renderIriarte=render;

function bindDynamic(){
  $$('[data-route]').forEach(a=>a.onclick=e=>{e.preventDefault();routeTo(a.dataset.route)});
  $$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
  $$('[data-open-project]').forEach(r=>r.onclick=()=>{S.sel.project=r.dataset.openProject;routeTo('proyectos')});
  $$('[data-select-project]').forEach(r=>r.onclick=()=>{S.sel.project=r.dataset.selectProject;render()});
  const ps=$('[data-project-search]');if(ps)ps.oninput=()=>$$('[data-project-item]').forEach(x=>x.style.display=x.dataset.search.includes(ps.value.toLowerCase())?'':'');
  $$('[data-project-nav]').forEach(b=>b.onclick=()=>routeTo(b.dataset.projectNav));
  const pf=$('[data-project-filter]');if(pf)pf.onchange=()=>{S.sel.project=pf.value;render()};
  $$('[data-budget-kind]').forEach(b=>b.onclick=()=>{S.budgetKind=b.dataset.budgetKind;S.sel.budget='';render()});
  $$('[data-budget-filter]').forEach(b=>b.onclick=()=>{S.budgetFilter=b.dataset.budgetFilter;render()});
  $$('[data-budget-view]').forEach(b=>b.onclick=()=>{S.budgetView=b.dataset.budgetView;render()});
  $$('[data-budget-item]').forEach(b=>b.onclick=()=>{S.sel.budget=b.dataset.budgetItem;render()});
  const bs=$('[data-budget-search]');if(bs)bs.oninput=()=>$$('[data-budget-item]').forEach(x=>x.style.display=x.dataset.search.includes(bs.value.toLowerCase())?'':'');
  bindBudgetEditor();
}
function bindBudgetEditor(){
  const p=currentBudget();if(!p||S.route!=='presupuestos'||S.budgetView!=='edit')return;
  $$('[data-budget-field]').forEach(x=>x.oninput=()=>{p[x.dataset.budgetField]=x.value});
  const cs=$('[data-budget-client]');if(cs)cs.onchange=()=>{p.cliente_id=cs.value||null;p.client=S.data.clientes.find(x=>String(x.id)===String(cs.value))?.nombre||p.client||'';render()};
  $$('[data-line] input').forEach(x=>x.oninput=()=>{const i=+x.closest('[data-line]').dataset.line,k=x.dataset.k;p.items[i][k]=['qty','price','vat'].includes(k)?num(x.value):x.value;const s=$('.budget-summary');if(s)s.innerHTML=renderBudgetSummary(p)});
  $$('[data-fee-line] input').forEach(x=>x.oninput=()=>{const i=+x.closest('[data-fee-line]').dataset.feeLine,k=x.dataset.k;p.fee_lines[i][k]=k==='description'?x.value:num(x.value);const s=$('.budget-summary');if(s)s.innerHTML=renderBudgetSummary(p)});
  $$('[data-remove-line]').forEach(b=>b.onclick=()=>{p.items.splice(+b.dataset.removeLine,1);render()});
  $$('[data-remove-fee]').forEach(b=>b.onclick=()=>{p.fee_lines.splice(+b.dataset.removeFee,1);render()});
}

async function action(a){
  try{
    if(a==='new-client')return clientForm();
    if(a==='new-project')return projectForm();
    if(a==='edit-project')return projectForm(S.sel.project);
    if(a==='new-budget')return createBudget();
    if(a==='add-budget-line'){const p=currentBudget();p.items=p.items||[];p.items.push({code:'',section:'',description:'',location:'',unit:'ud',qty:1,price:0,vat:21});return render()}
    if(a==='add-fee-line'){const p=currentBudget();p.fee_lines=p.fee_lines||[];p.fee_lines.push({description:'',amount:0,vat:21});return render()}
    if(a==='save-budget')return saveBudget();
    if(a==='paste-budget')return pasteBudget();
    if(a==='new-supplier')return supplierForm();
    if(a==='new-visit')return visitForm();
    if(a==='new-incident')return incidentForm();
    toast('Acción pendiente de este módulo.',true);
  }catch(err){console.error(err);toast(err.message||String(err),true)}
}

function clientForm(){modal('Nuevo cliente',`<div class="form-grid"><label>Nombre<input name="nombre" required></label><label>CIF/NIF<input name="cif"></label><label>Email<input name="email" type="email"></label><label>Teléfono<input name="telefono"></label><label class="full">Dirección<input name="direccion"></label></div>`,async f=>{const {error}=await sb.from('clientes').insert(f);if(error)throw error})}
function supplierForm(){modal('Nuevo proveedor',`<div class="form-grid"><label>Nombre<input name="nombre" required></label><label>CIF<input name="cif"></label><label>Email<input name="email" type="email"></label><label>Teléfono<input name="telefono"></label></div>`,async f=>{const {error}=await sb.from('proveedores').insert(f);if(error)throw error})}
function projectForm(pid){const x=S.data.proyectos.find(p=>String(p.id)===String(pid))||{};modal(pid?'Editar proyecto':'Nuevo proyecto',`<div class="form-grid"><label class="full">Nombre<input name="nombre" required value="${esc(x.nombre||'')}"></label><label>Cliente<select name="cliente_id">${options(S.data.clientes,x.cliente_id,p=>p.nombre)}</select></label><label>Código<input name="codigo" value="${esc(x.codigo||'')}"></label><label class="full">Dirección<input name="direccion" value="${esc(x.direccion||'')}"></label><label>Estado<select name="estado"><option value="activo" ${x.estado==='activo'?'selected':''}>activo</option><option value="en_obra" ${x.estado==='en_obra'?'selected':''}>en obra</option><option value="finalizado" ${x.estado==='finalizado'?'selected':''}>finalizado</option><option value="pausado" ${x.estado==='pausado'?'selected':''}>pausado</option></select></label><label>Importe contratado<input name="importe_contratado" type="number" step=".01" value="${num(x.importe_contratado)}"></label></div>`,async f=>{const payload={name:f.nombre,cliente_id:f.cliente_id||null,codigo:f.codigo||null,ref:f.codigo||null,direccion:f.direccion||null,address:f.direccion||null,estado_gestion:f.estado||'activo',status:'Proyecto',es_proyecto:true,importe_contratado:num(f.importe_contratado)};if(pid){const {error}=await sb.from('projects').update(payload).eq('id',pid);if(error)throw error}else{payload.id=crypto.randomUUID();payload.fecha_inicio=today();payload.date=today();const {error}=await sb.from('projects').insert(payload);if(error)throw error}})}
function visitForm(){const pid=S.sel.project||S.data.proyectos[0]?.id;if(!pid)return toast('Crea o selecciona un proyecto primero.',true);modal('Nueva visita de obra',`<div class="form-grid"><label>Proyecto<select name="project_id">${options(S.data.proyectos,pid,p=>p.nombre)}</select></label><label>Fecha<input name="fecha" type="date" value="${today()}"></label><label class="full">Título<input name="titulo" value="Visita de obra"></label><label class="full">Descripción<textarea name="descripcion"></textarea></label></div>`,async f=>{const {error}=await sb.from('obra_visitas').insert({project_id:f.project_id,fecha:f.fecha,titulo:f.titulo||'Visita de obra',descripcion:f.descripcion||null});if(error)throw error})}
function incidentForm(){const pid=S.sel.project||S.data.proyectos[0]?.id;if(!pid)return toast('Crea o selecciona un proyecto primero.',true);modal('Nueva incidencia',`<div class="form-grid"><label>Proyecto<select name="project_id">${options(S.data.proyectos,pid,p=>p.nombre)}</select></label><label>Prioridad<select name="prioridad"><option>baja</option><option selected>normal</option><option>alta</option><option>urgente</option></select></label><label class="full">Título<input name="titulo" required></label><label class="full">Descripción<textarea name="descripcion"></textarea></label></div>`,async f=>{const {error}=await sb.from('obra_incidencias').insert({project_id:f.project_id,titulo:f.titulo,descripcion:f.descripcion||null,prioridad:f.prioridad||'normal',estado:'abierta'});if(error)throw error})}

async function enter(user){S.user=user;const {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();S.profile=data||{name:user.email,email:user.email};$('#user-name').textContent=S.profile.name||S.profile.nombre||S.profile.email||user.email;$('#auth-screen').classList.add('hidden');$('#app-shell').classList.remove('hidden');await loadAll();const h=location.hash.replace('#','');S.route=NAV.some(x=>x[0]===h)?h:'inicio';render();$('#logout-btn').onclick=async()=>{await sb.auth.signOut();location.reload()}}
async function init(){renderNav();const {data:{session}}=await sb.auth.getSession();if(session?.user)await enter(session.user);else{$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').textContent='';const {data,error}=await sb.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error){$('#login-error').textContent=error.message;return}await enter(data.user)}}}
window.addEventListener('hashchange',()=>{const h=location.hash.replace('#','');if(NAV.some(x=>x[0]===h)&&h!==S.route){S.route=h;render()}});
document.addEventListener('DOMContentLoaded',init);

})();
