// Iriarte ERP V2 · ficha rápida de cliente y proveedor
(function(){
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(v||0)||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
let timer;
function closeable(title,html){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(980px,96vw)"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-ch-close>Cerrar</button></div><div class="modal-body">${html}</div><div class="modal-foot"><button class="btn primary" type="button" data-ch-close>Cerrar</button></div></div></div>`;root.querySelectorAll('[data-ch-close]').forEach(b=>b.onclick=()=>root.innerHTML='')}
function badge(s){const v=String(s||'—');const cls=/cobrad|pagad|acept|activo/i.test(v)?'good':/anulad|cancel|inactiv/i.test(v)?'bad':'warn';return `<span class="badge ${cls}">${esc(v.replaceAll('_',' '))}</span>`}
function projectsForClient(id,D){return (D.proyectos||[]).filter(x=>String(x.cliente_id)===String(id))}
function clientHub(id){const D=window.APP?.data||{},x=(D.clientes||[]).find(c=>String(c.id)===String(id));if(!x)return;const projects=projectsForClient(id,D),pids=new Set(projects.map(p=>String(p.id))),budgets=(D.presupuestos||[]).filter(p=>String(p.cliente_id)===String(id)||pids.has(String(p.proyecto_id))),invoices=(D.facturas||[]).filter(f=>String(f.cliente_id)===String(id)&&String(f.estado)!=='anulada'),ids=new Set(invoices.map(f=>String(f.id))),collections=(D.cobros||[]).filter(c=>ids.has(String(c.factura_id))),docs=(D.docs||[]).filter(d=>String(d.cliente_id)===String(id)||pids.has(String(d.proyecto_id)));const billed=invoices.reduce((a,f)=>a+num(f.total),0),collected=collections.reduce((a,c)=>a+num(c.importe),0),pending=Math.max(0,billed-collected);
 closeable(`Cliente · ${x.nombre}`,`<div class="grid cols-4"><div class="info"><small>Proyectos</small><b>${projects.length}</b></div><div class="info"><small>Presupuestos</small><b>${budgets.length}</b></div><div class="info"><small>Facturado total</small><b>${money(billed)}</b></div><div class="info"><small>Pendiente de cobro</small><b class="${pending?'negative':'positive'}">${money(pending)}</b></div></div><div class="grid cols-2" style="margin-top:14px"><div class="card panel"><h3>Datos</h3><div class="info-grid"><div class="info"><small>CIF/NIF</small><b>${esc(x.cif||'—')}</b></div><div class="info"><small>Contacto</small><b>${esc(x.contacto||'—')}</b></div><div class="info"><small>Teléfono</small><b>${esc(x.telefono||'—')}</b></div><div class="info"><small>Email</small><b>${esc(x.email||'—')}</b></div><div class="info"><small>Dirección</small><b>${esc([x.direccion,x.codigo_postal,x.poblacion,x.provincia].filter(Boolean).join(', ')||'—')}</b></div><div class="info"><small>Documentos</small><b>${docs.length}</b></div></div></div><div class="card panel"><h3>Proyectos</h3>${projects.length?projects.map(p=>`<div class="master-item"><b>${esc(p.nombre)}</b><small>${esc(p.codigo||'')} · ${badge(p.estado)}</small></div>`).join(''):'<div class="empty">Sin proyectos.</div>'}</div><div class="card panel"><h3>Facturas</h3>${invoices.length?invoices.slice(0,12).map(f=>{const paid=collections.filter(c=>String(c.factura_id)===String(f.id)).reduce((a,c)=>a+num(c.importe),0);return `<div class="master-item"><b>${esc(f.numero||'Borrador')} · ${money(f.total)}</b><small>${esc(f.fecha||'')} · cobrado ${money(paid)} · ${badge(f.estado)}</small></div>`}).join(''):'<div class="empty">Sin facturas.</div>'}</div><div class="card panel"><h3>Presupuestos</h3>${budgets.length?budgets.slice(0,12).map(p=>`<div class="master-item"><b>${esc(p.name||p.nombre||'Presupuesto')}</b><small>${esc(p.ref||p.numero||'')} · ${badge(p.status||p.estado)}</small></div>`).join(''):'<div class="empty">Sin presupuestos.</div>'}</div></div>`)}
function supplierHub(id){const D=window.APP?.data||{},x=(D.proveedores||[]).find(c=>String(c.id)===String(id));if(!x)return;const purchases=(D.compras||[]).filter(c=>String(c.proveedor_id)===String(id)&&String(c.estado)!=='anulada'),ids=new Set(purchases.map(c=>String(c.id))),payments=(D.pagos||[]).filter(p=>ids.has(String(p.compra_id))),projectIds=new Set(purchases.map(c=>String(c.proyecto_id||'')).filter(Boolean)),projects=(D.proyectos||[]).filter(p=>projectIds.has(String(p.id))),docs=(D.docs||[]).filter(d=>String(d.proveedor_id)===String(id)||ids.has(String(d.compra_id)));const total=purchases.reduce((a,c)=>a+num(c.total),0),paid=payments.reduce((a,p)=>a+num(p.importe),0),pending=Math.max(0,total-paid);
 closeable(`Proveedor · ${x.nombre}`,`<div class="grid cols-4"><div class="info"><small>Compras</small><b>${purchases.length}</b></div><div class="info"><small>Total compras</small><b>${money(total)}</b></div><div class="info"><small>Pagado</small><b>${money(paid)}</b></div><div class="info"><small>Pendiente de pago</small><b class="${pending?'negative':'positive'}">${money(pending)}</b></div></div><div class="grid cols-2" style="margin-top:14px"><div class="card panel"><h3>Datos</h3><div class="info-grid"><div class="info"><small>CIF</small><b>${esc(x.cif||'—')}</b></div><div class="info"><small>Tipo</small><b>${esc(x.tipo||'—')}</b></div><div class="info"><small>Contacto</small><b>${esc(x.contacto||'—')}</b></div><div class="info"><small>Teléfono</small><b>${esc(x.telefono||'—')}</b></div><div class="info"><small>Email</small><b>${esc(x.email||'—')}</b></div><div class="info"><small>Documentos</small><b>${docs.length}</b></div></div></div><div class="card panel"><h3>Proyectos relacionados</h3>${projects.length?projects.map(p=>`<div class="master-item"><b>${esc(p.nombre)}</b><small>${esc(p.codigo||'')} · ${badge(p.estado)}</small></div>`).join(''):'<div class="empty">Sin proyectos relacionados.</div>'}</div><div class="card panel" style="grid-column:1/-1"><h3>Compras recientes</h3>${purchases.length?`<div class="table-wrap"><table class="table"><tr><th>Fecha</th><th>Factura</th><th>Proyecto</th><th>Concepto</th><th>Total</th><th>Estado</th></tr>${purchases.slice(0,15).map(c=>`<tr><td>${esc(c.fecha||'')}</td><td>${esc(c.numero_factura||'')}</td><td>${esc((D.proyectos||[]).find(p=>String(p.id)===String(c.proyecto_id))?.nombre||'—')}</td><td>${esc(c.concepto||'')}</td><td>${money(c.total)}</td><td>${badge(c.estado)}</td></tr>`).join('')}</table></div>`:'<div class="empty">Sin compras.</div>'}</div></div>`)}
function decorate(){clearTimeout(timer);timer=setTimeout(()=>{document.querySelectorAll('[data-ct-client]').forEach(edit=>{const cell=edit.parentElement;if(cell?.querySelector('[data-ch-client]'))return;const b=document.createElement('button');b.className='btn';b.type='button';b.textContent='Ficha';b.dataset.chClient=edit.dataset.ctClient;cell.insertBefore(b,edit)});document.querySelectorAll('[data-ct-supplier]').forEach(edit=>{const cell=edit.parentElement;if(cell?.querySelector('[data-ch-supplier]'))return;const b=document.createElement('button');b.className='btn';b.type='button';b.textContent='Ficha';b.dataset.chSupplier=edit.dataset.ctSupplier;cell.insertBefore(b,edit)})},60)}
new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',decorate);window.addEventListener('load',decorate);
document.addEventListener('click',e=>{const b=e.target.closest('[data-ch-client],[data-ch-supplier]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.chClient)clientHub(b.dataset.chClient);else supplierHub(b.dataset.chSupplier)},true);
})();
