// Iriarte ERP V2 · clientes y proveedores editables
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
let timer;
function modal(title,body,onSave){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button type="button" class="btn" data-ct-close>Cerrar</button></div><form id="ct-form"><div class="modal-body">${body}<div id="ct-error"></div></div><div class="modal-foot"><button type="button" class="btn" data-ct-close>Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form></div></div>`;const close=()=>root.innerHTML='';root.querySelectorAll('[data-ct-close]').forEach(b=>b.onclick=close);$('#ct-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await onSave(Object.fromEntries(new FormData(e.currentTarget).entries()));close();if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#ct-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}}
function editClient(x){modal('Editar cliente',`<div class="form-grid"><label class="full">Nombre<input name="nombre" required value="${esc(x.nombre||'')}"></label><label>CIF/NIF<input name="cif" value="${esc(x.cif||'')}"></label><label>IRPF %<input name="irpf" type="number" step="0.01" value="${num(x.irpf)}"></label><label>Contacto<input name="contacto" value="${esc(x.contacto||'')}"></label><label>Email<input name="email" type="email" value="${esc(x.email||'')}"></label><label>Teléfono<input name="telefono" value="${esc(x.telefono||'')}"></label><label>Teléfono 2<input name="telefono2" value="${esc(x.telefono2||'')}"></label><label class="full">Dirección<input name="direccion" value="${esc(x.direccion||'')}"></label><label>Código postal<input name="codigo_postal" value="${esc(x.codigo_postal||'')}"></label><label>Población<input name="poblacion" value="${esc(x.poblacion||'')}"></label><label>Provincia<input name="provincia" value="${esc(x.provincia||'')}"></label><label>Activo<select name="activo"><option value="true" ${x.activo?'selected':''}>Sí</option><option value="false" ${x.activo?'':'selected'}>No</option></select></label><label class="full">Notas<textarea name="notas">${esc(x.notas||'')}</textarea></label></div>`,async f=>{const {error}=await db().from('clientes').update({nombre:f.nombre,cif:f.cif||null,irpf:num(f.irpf),contacto:f.contacto||null,email:f.email||null,telefono:f.telefono||null,telefono2:f.telefono2||null,direccion:f.direccion||null,codigo_postal:f.codigo_postal||null,poblacion:f.poblacion||null,provincia:f.provincia||null,activo:f.activo==='true',notas:f.notas||null}).eq('id',x.id);if(error)throw error})}
function editSupplier(x){modal('Editar proveedor',`<div class="form-grid"><label class="full">Nombre<input name="nombre" required value="${esc(x.nombre||'')}"></label><label>CIF<input name="cif" value="${esc(x.cif||'')}"></label><label>Tipo<input name="tipo" value="${esc(x.tipo||'')}"></label><label>Contacto<input name="contacto" value="${esc(x.contacto||'')}"></label><label>Email<input name="email" type="email" value="${esc(x.email||'')}"></label><label>Teléfono<input name="telefono" value="${esc(x.telefono||'')}"></label><label>Web<input name="web" value="${esc(x.web||'')}"></label><label>Zona<input name="zona" value="${esc(x.zona||'')}"></label><label>Activo<select name="activo"><option value="true" ${x.activo?'selected':''}>Sí</option><option value="false" ${x.activo?'':'selected'}>No</option></select></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label><label class="full">Notas<textarea name="notas">${esc(x.notas||'')}</textarea></label></div>`,async f=>{const {error}=await db().from('proveedores').update({nombre:f.nombre,cif:f.cif||null,tipo:f.tipo||null,contacto:f.contacto||null,email:f.email||null,telefono:f.telefono||null,web:f.web||null,zona:f.zona||null,activo:f.activo==='true',descripcion:f.descripcion||null,notas:f.notas||null}).eq('id',x.id);if(error)throw error})}
async function deactivate(table,id){const label=table==='clientes'?'cliente':'proveedor';if(!confirm(`¿Desactivar este ${label}? No se borrarán sus operaciones.`))return;const {error}=await db().from(table).update({activo:false}).eq('id',id);if(error)return alert(error.message);if(window.reloadIriarte)await window.reloadIriarte()}
function renderClients(){if(window.APP?.route!=='clientes')return false;const D=window.APP.data,view=$('#app-view');if(!view||$('#clients-plus'))return true;const rows=D.clientes||[];view.innerHTML=`<div id="clients-plus"><div class="page-head"><h1>Clientes</h1><div class="grow"></div><button class="btn primary" data-action="new-client">+ Nuevo cliente</button></div>${rows.length?`<div class="card panel table-wrap"><table class="table"><tr><th>Cliente</th><th>CIF</th><th>Contacto</th><th>Email</th><th>Teléfono</th><th>Proyectos</th><th>Estado</th><th></th></tr>${rows.map(x=>`<tr><td><b>${esc(x.nombre)}</b><br><small>${esc([x.poblacion,x.provincia].filter(Boolean).join(', '))}</small></td><td>${esc(x.cif||'')}</td><td>${esc(x.contacto||'')}</td><td>${esc(x.email||'')}</td><td>${esc(x.telefono||'')}</td><td>${D.proyectos.filter(p=>String(p.cliente_id)===String(x.id)).length}</td><td><span class="badge ${x.activo?'good':'bad'}">${x.activo?'activo':'inactivo'}</span></td><td><div class="toolbar"><button class="btn" data-ct-client="${x.id}">Editar</button>${x.activo?`<button class="btn" data-ct-off="clientes:${x.id}">Desactivar</button>`:''}</div></td></tr>`).join('')}</table></div>`:'<div class="empty">No hay clientes todavía.</div>'}</div>`;view.querySelectorAll('[data-ct-client]').forEach(b=>b.onclick=()=>editClient(rows.find(x=>String(x.id)===String(b.dataset.ctClient))));return true}
function renderSuppliers(){if(window.APP?.route!=='proveedores')return false;const D=window.APP.data,view=$('#app-view');if(!view||$('#suppliers-plus'))return true;const rows=D.proveedores||[];view.innerHTML=`<div id="suppliers-plus"><div class="page-head"><h1>Proveedores</h1><div class="grow"></div><button class="btn primary" data-action="new-supplier">+ Nuevo proveedor</button></div>${rows.length?`<div class="card panel table-wrap"><table class="table"><tr><th>Proveedor</th><th>CIF</th><th>Tipo</th><th>Contacto</th><th>Email</th><th>Teléfono</th><th>Compras</th><th>Estado</th><th></th></tr>${rows.map(x=>`<tr><td><b>${esc(x.nombre)}</b><br><small>${esc(x.zona||'')}</small></td><td>${esc(x.cif||'')}</td><td>${esc(x.tipo||'')}</td><td>${esc(x.contacto||'')}</td><td>${esc(x.email||'')}</td><td>${esc(x.telefono||'')}</td><td>${D.compras.filter(c=>String(c.proveedor_id)===String(x.id)).length}</td><td><span class="badge ${x.activo?'good':'bad'}">${x.activo?'activo':'inactivo'}</span></td><td><div class="toolbar"><button class="btn" data-ct-supplier="${x.id}">Editar</button>${x.activo?`<button class="btn" data-ct-off="proveedores:${x.id}">Desactivar</button>`:''}</div></td></tr>`).join('')}</table></div>`:'<div class="empty">No hay proveedores todavía.</div>'}</div>`;view.querySelectorAll('[data-ct-supplier]').forEach(b=>b.onclick=()=>editSupplier(rows.find(x=>String(x.id)===String(b.dataset.ctSupplier))));return true}
function render(){clearTimeout(timer);timer=setTimeout(()=>{renderClients()||renderSuppliers()},60)}
new MutationObserver(render).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',render);window.addEventListener('load',render);
document.addEventListener('click',e=>{const b=e.target.closest('[data-ct-off]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const [table,id]=b.dataset.ctOff.split(':');deactivate(table,id)},true);
})();
