// Iriarte ERP V2 · alertas de calidad de datos que afectan a importes y coherencia
(function(){
'use strict';
const num=v=>Number(String(v??0).replace(',','.'))||0;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
let timer;
function budgetIssues(D){const out=[];(D.presupuestos||[]).forEach(p=>{let bad=0,detail=[];if((p.kind||'obra')==='honorarios'){(p.fee_lines||[]).forEach((x,i)=>{const amount=Number(x.amount??x.importe??0),vat=Number(x.vat??x.ivaPct??21);if(!Number.isFinite(amount)||amount<0){bad++;detail.push(`honorario ${i+1}: importe`)}if(!Number.isFinite(vat)||vat<0||vat>100){bad++;detail.push(`honorario ${i+1}: IVA ${x.vat??x.ivaPct??''}%`)}})}else{(p.items||[]).forEach((x,i)=>{const qty=Number(x.qty??x.cantidad??0),price=Number(x.price??x.precio??0),vat=Number(x.vat??x.ivaPct??21);if(!Number.isFinite(qty)||qty<0){bad++;detail.push(`línea ${i+1}: cantidad`)}if(!Number.isFinite(price)||price<0){bad++;detail.push(`línea ${i+1}: precio`)}if(!Number.isFinite(vat)||vat<0||vat>100){bad++;detail.push(`línea ${i+1}: IVA ${x.vat??x.ivaPct??''}%`)}})}if(bad)out.push({type:'budget',id:p.id,title:p.name||p.nombre||'Presupuesto',count:bad,detail:detail.slice(0,5).join(' · ')})});return out}
function invoiceIssues(D){const grouped=new Map();(D.lineas||[]).forEach(x=>{const qty=num(x.cantidad),price=num(x.precio_unitario),vat=num(x.iva_pct),discount=num(x.descuento_pct),bad=qty<0||price<0||vat<0||vat>100||discount<0||discount>100;if(!bad)return;const key=String(x.factura_id),row=grouped.get(key)||{count:0,detail:[]};row.count++;row.detail.push(`línea ${x.orden||'?'} fuera de rango`);grouped.set(key,row)});return [...grouped.entries()].map(([id,v])=>{const f=(D.facturas||[]).find(x=>String(x.id)===id);return{type:'invoice',id,title:f?.numero||'Factura',count:v.count,detail:v.detail.slice(0,5).join(' · ')}})}
function otherIssues(D){const out=[];(D.compras||[]).forEach(x=>{const detail=[];if(num(x.base)<0||num(x.total)<0||num(x.iva_pct)<0||num(x.iva_pct)>100)detail.push('Importe o IVA fuera de rango');if(num(x.total)===0)detail.push('Importe total 0');if(!String(x.concepto||'').trim()&&!String(x.numero_factura||'').trim())detail.push('Sin concepto ni número de factura');if(detail.length)out.push({type:'purchase',id:x.id,title:x.numero_factura||x.concepto||'Compra',count:detail.length,detail:detail.join(' · ')})});(D.gastos||[]).forEach(x=>{const detail=[];if(num(x.base)<0||num(x.total)<0||num(x.iva_pct)<0||num(x.iva_pct)>100)detail.push('Importe o IVA fuera de rango');if(num(x.total)===0)detail.push('Importe total 0');if(x.pagado&&!x.fecha_pago)detail.push('Marcado como pagado sin fecha de pago');if(!x.pagado&&x.fecha_pago)detail.push('Tiene fecha de pago pero está marcado como no pagado');if(x.fecha&&x.fecha_pago&&String(x.fecha_pago)<String(x.fecha))detail.push('La fecha de pago es anterior a la fecha del gasto');if(detail.length)out.push({type:'expense',id:x.id,title:x.concepto||'Gasto general',count:detail.length,detail:detail.join(' · ')})});(D.horas||[]).forEach(x=>{if(num(x.horas)<0||num(x.coste_hora)<0)out.push({type:'operational',id:'horas_proyecto:'+x.id,title:x.persona||'Horas',count:1,detail:'Horas o coste/hora negativo'})});return out}
function open(issue){if(issue.type==='budget'||issue.type==='invoice'||issue.type==='purchase')return window.iriarteOpenRecord?.(issue.type,issue.id);if(issue.type==='expense')return window.iriarteEditExpense?.(issue.id);if(issue.type==='operational'){const [table,id]=issue.id.split(':');return window.iriarteEditOperationalRecord?.(table,id)}}
function inject(){clearTimeout(timer);timer=setTimeout(()=>{if(window.APP?.route!=='informes')return;const view=document.querySelector('#reports-v2');if(!view||view.querySelector('#data-quality-panel'))return;const D=window.APP?.data||{},issues=[...budgetIssues(D),...invoiceIssues(D),...otherIssues(D)];if(!issues.length)return;const total=issues.reduce((a,x)=>a+x.count,0),panel=document.createElement('section');panel.id='data-quality-panel';panel.className='card panel';panel.style.marginTop='14px';panel.innerHTML=`<h3>Calidad de datos</h3><div class="notice" style="background:#fff2d8;color:#745b24"><b>${total} dato${total===1?'':'s'} a revisar.</b> Estos registros pueden distorsionar presupuestos, facturas, rentabilidad o estados administrativos. Pulsa un registro para revisarlo.</div><div class="table-wrap"><table class="table"><tr><th>Tipo</th><th>Registro</th><th>Problema</th><th></th></tr>${issues.map((x,i)=>`<tr><td>${esc(({budget:'Presupuesto',invoice:'Factura',purchase:'Compra',expense:'Gasto',operational:'Horas'})[x.type]||x.type)}</td><td><b>${esc(x.title)}</b></td><td>${esc(x.detail)}</td><td><button class="btn" data-quality-open="${i}">Revisar</button></td></tr>`).join('')}</table></div>`;view.appendChild(panel);panel.querySelectorAll('[data-quality-open]').forEach(b=>b.onclick=()=>open(issues[Number(b.dataset.qualityOpen)]))},90)}
new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',inject);window.addEventListener('load',inject);
})();
