// Iriarte ERP V2 · formularios operativos ajustados al esquema real
(function(){
'use strict';
const db=window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const today=()=>new Date().toISOString().slice(0,10);
function opts(arr,value){return '<option value="">—</option>'+(arr||[]).map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(value)?'selected':''}>${esc(x.nombre||x.name||'')}</option>`).join('')}
function modal(title,html,onSave){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-x-close>Cerrar</button></div><form id="x-form"><div class="modal-body">${html}<div id="x-error"></div></div><div class="modal-foot"><button class="btn" type="button" data-x-close>Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form></div></div>`;const close=()=>root.innerHTML='';root.querySelectorAll('[data-x-close]').forEach(b=>b.onclick=close);$('#x-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await onSave(Object.fromEntries(new FormData(e.currentTarget).entries()));close();if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#x-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}}
function projectId(){return window.APP?.sel?.project||window.APP?.data?.proyectos?.[0]?.id||''}

function purchaseForm(){const S=window.APP||{data:{}};modal('Nueva compra',`<div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label>Nº factura<input name="numero_factura"></label><label>Proveedor<select name="proveedor_id">${opts(S.data.proveedores)}</select></label><label>Proyecto<select name="proyecto_id">${opts(S.data.proyectos,projectId())}</select></label><label class="full">Concepto<input name="concepto" required></label><label>Base imponible<input name="base" type="number" step="0.01" value="0"></label><label>IVA %<input name="iva_pct" type="number" step="0.01" value="21"></label><label>Estado<select name="estado"><option value="pendiente">pendiente</option><option value="pagada">pagada</option></select></label><label>Vencimiento<input name="fecha_vencimiento" type="date"></label><label class="full">Notas<textarea name="notas"></textarea></label></div>`,async f=>{const base=num(f.base),ivaPct=num(f.iva_pct),iva=base*ivaPct/100;const {error}=await db.from('compras').insert({fecha:f.fecha,numero_factura:f.numero_factura||null,proveedor_id:f.proveedor_id||null,proyecto_id:f.proyecto_id||null,concepto:f.concepto,base,iva_pct:ivaPct,iva_importe:iva,total:base+iva,estado:f.estado||'pendiente',fecha_vencimiento:f.fecha_vencimiento||null,notas:f.notas||null});if(error)throw error})}
function taskForm(){const S=window.APP||{data:{}};modal('Nueva tarea de obra',`<div class="form-grid"><label>Proyecto<select name="project_id" required>${opts(S.data.proyectos,projectId())}</select></label><label>Prioridad<select name="prioridad"><option>baja</option><option selected>normal</option><option>alta</option><option>urgente</option></select></label><label class="full">Título<input name="titulo" required></label><label>Fecha límite<input name="fecha_limite" type="date"></label><label class="full">Descripción<textarea name="descripcion"></textarea></label></div>`,async f=>{const {error}=await db.from('obra_tareas').insert({project_id:f.project_id,titulo:f.titulo,descripcion:f.descripcion||null,estado:'pendiente',prioridad:f.prioridad||'normal',fecha_limite:f.fecha_limite||null});if(error)throw error})}
function hourForm(){const S=window.APP||{data:{}};modal('Registrar horas',`<div class="form-grid"><label>Proyecto<select name="proyecto_id" required>${opts(S.data.proyectos,projectId())}</select></label><label>Persona<input name="persona" required></label><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label>Horas<input name="horas" type="number" step="0.1" min="0" value="1"></label><label>Coste/hora histórico<input name="coste_hora" type="number" step="0.01" min="0" value="0"></label><label class="full">Concepto<textarea name="concepto"></textarea></label></div>`,async f=>{const {error}=await db.from('horas_proyecto').insert({proyecto_id:f.proyecto_id,persona:f.persona,fecha:f.fecha,horas:num(f.horas),coste_hora:num(f.coste_hora),concepto:f.concepto||null});if(error)throw error})}
function documentForm(){const S=window.APP||{data:{}};modal('Subir documento',`<div class="form-grid"><label>Proyecto<select name="proyecto_id">${opts(S.data.proyectos,projectId())}</select></label><label>Tipo<input name="tipo" value="Documento"></label><label class="full">Archivo<input id="x-doc-file" type="file" required></label><label class="full">Descripción<textarea name="descripcion"></textarea></label></div>`,async f=>{const file=$('#x-doc-file').files[0];if(!file)throw new Error('Selecciona un archivo');const safe=file.name.replace(/[^\w.\-áéíóúñ]+/gi,'_');const path=`${f.proyecto_id||'general'}/${Date.now()}-${safe}`;let bucket='',stored='',last=null;for(const b of ['documentos','obra-fotos']){const r=await db.storage.from(b).upload(path,file,{upsert:false});if(!r.error){bucket=b;stored=r.data.path;break}last=r.error}if(!stored)throw last||new Error('No hay bucket disponible');const {error}=await db.from('documentos').insert({proyecto_id:f.proyecto_id||null,nombre:file.name,tipo:f.tipo||'Documento',descripcion:f.descripcion||null,archivo_nombre:file.name,archivo_ruta:`${bucket}/${stored}`,mime_type:file.type||null,tamano_bytes:file.size,fecha_documento:today()});if(error)throw error})}
function overheadForm(){const S=window.APP||{data:{}};modal('Nuevo gasto general',`<div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label>Categoría<input name="categoria" value="Otros" required></label><label class="full">Concepto<input name="concepto" required></label><label>Proveedor<select name="proveedor_id">${opts(S.data.proveedores)}</select></label><label>Proyecto opcional<select name="proyecto_id">${opts(S.data.proyectos,projectId())}</select></label><label>Base<input name="base" type="number" step="0.01" value="0"></label><label>IVA %<input name="iva_pct" type="number" step="0.01" value="21"></label><label>Pagado<select name="pagado"><option value="false">No</option><option value="true">Sí</option></select></label><label>Cuenta<input name="cuenta"></label><label class="full">Notas<textarea name="notas"></textarea></label></div>`,async f=>{const base=num(f.base),ivaPct=num(f.iva_pct),iva=base*ivaPct/100;const {error}=await db.from('gastos_generales').insert({fecha:f.fecha,categoria:f.categoria,concepto:f.concepto,proveedor_id:f.proveedor_id||null,proyecto_id:f.proyecto_id||null,base,iva_pct:ivaPct,iva_importe:iva,total:base+iva,pagado:f.pagado==='true',fecha_pago:f.pagado==='true'?f.fecha:null,cuenta:f.cuenta||null,notas:f.notas||null,criterio_reparto:f.proyecto_id?'proyecto_directo':'sin_repartir'});if(error)throw error})}

document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const map={'new-purchase':purchaseForm,'new-task':taskForm,'new-hour':hourForm,'new-doc':documentForm,'new-overhead':overheadForm};const fn=map[b.dataset.action];if(!fn)return;e.preventDefault();e.stopImmediatePropagation();fn()},true);
})();
