// Iriarte ERP V2 · editor estructurado de Honorarios inspirado en la herramienta original
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
const uid=()=>crypto.randomUUID?.()||('h'+Date.now()+Math.random().toString(16).slice(2));
let timer;

const SCOPE=[
'Movimiento de tierras.',
'Estudio edafológico y determinación de enmiendas, mejoras o aporte de tierras según la calidad del terreno para el óptimo desarrollo de las especies vegetales a implantar, así como la permeabilidad del suelo, la necesidad de drenajes y de acolchados para protección de superficies. Se definirán las secciones de terreno requeridas por las diferentes especies vegetales, determinando las capas de tierras a eliminar, aportar o mejorar, la naturaleza y calidad de nuevas tierras a suministrar.',
'Diseño de la red de riego y drenaje óptima. Determinación de la necesidad de elementos como depósitos, bombas, nuevas acometidas, etc.',
'Elección y composición de especies vegetales valorando, aparte de su resistencia al medio e integración con el paisaje circundante, la búsqueda de sombras, aromas, atractivo y armonía con el entorno, con la decoración y la arquitectura.',
'Elección de macetas y elementos decorativos.',
'Estudio de iluminación en los espacios ajardinados, como ampliación de la ya prevista en el Proyecto de arquitectura (ubicación y tipo de luminaria). NO INCLUYE PROYECTO ELECTROTÉCNICO.',
'El diseño y selección de materiales de construcción de los elementos constructivos de las zonas ajardinadas tales como pavimentos, bordillos, muros de contención, bancos, piscina, pérgola, etc. NO ESTÁN INCLUIDOS EN ESTE PROYECTO LOS DETALLES TÉCNICOS Y CÁLCULOS DE ESTRUCTURAS DE LOS ELEMENTOS CONSTRUCTIVOS.',
'Inventario sobre el arbolado existente e informe sobre las pautas a seguir para su conservación y mejora.',
'Levantamiento del plano actual del jardín.',
'Búsqueda de proveedores/comparativos, y empresas para la ejecución de los distintos trabajos.'
];
const PEM=[
[0,15000,.10,.07],[15000,30000,.08,.06],[30000,53000,.07,.05],[53000,75000,.06,.04],[75000,150000,.05,.035],[150000,300000,.04,.03],[300000,600000,.032,.024],[600000,1500000,.024,.018],[1500000,Infinity,.02,.015]
];
const AREA=[[0,500,1817],[501,1000,3563.11],[1001,2000,3866.94],[2001,3000,5892.48],[3001,4000,6790],[4001,5000,6946.17],[5001,6000,9370.68],[6001,7000,10429.49],[7001,8000,11636.62],[8001,9000,12843.76],[9001,10000,13012.56]];
const HOURLY=[['director','Director de oficina',104.10],['autor','Autor del proyecto',78.08],['colaborador','Colaborador / Inspección Técnica de Obra',62.46],['delineante','Delineante / Auxiliar de oficina',49.45]];
const PHASE_FULL=[['Estudio previo',.10],['Anteproyecto',.20],['Proyecto (básico o ejecución)',.35],['Dirección y recepción de obra',.35]];
const PHASE_SINGLE=[['Estudio previo, en solitario',.20],['Anteproyecto, en solitario',.40],['Proyecto, en solitario',.85],['Dirección y recepción de obra, en solitario',.55]];

function current(){const A=window.APP;return A?.data?.presupuestos?.find(x=>String(x.id)===String(A?.sel?.budget))||null}
function normalize(p){
 p.zonas=Array.isArray(p.zonas)?p.zonas:[];
 p.scope_items=Array.isArray(p.scope_items)?p.scope_items:[];
 p.fases_obra=Array.isArray(p.fases_obra)?p.fases_obra:[];
 p.fee_lines=Array.isArray(p.fee_lines)?p.fee_lines:[];
 p.clausulas=Array.isArray(p.clausulas)?p.clausulas:[];
 p.zonas.forEach(x=>x.id=x.id||uid());p.scope_items.forEach(x=>x.id=x.id||uid());p.fases_obra.forEach(x=>x.id=x.id||uid());p.fee_lines.forEach(x=>x.id=x.id||uid());p.clausulas.forEach(x=>x.id=x.id||uid());
 p.fee_lines.forEach(x=>{if(x.concepto==null)x.concepto=x.description||'';if(x.importe==null)x.importe=x.amount??0;if(x.formaPago==null)x.formaPago=x.forma_pago||'';if(x.vat==null)x.vat=21});
 if(p.redaccion_toggle==null)p.redaccion_toggle=true;
 if(p.redaccion_texto==null)p.redaccion_texto='Redacción del Proyecto de Paisajismo conforme al alcance definido.';
}
function total(p){return p.fee_lines.reduce((a,x)=>a+num(x.importe??x.amount),0)}
function clientOptions(p){return '<option value="">— Sin ficha vinculada —</option>'+(window.APP?.data?.clientes||[]).map(x=>`<option value="${x.id}" ${String(x.id)===String(p.cliente_id)?'selected':''}>${esc(x.nombre)}</option>`).join('')}
function meta(p){return `<div class="card panel"><div class="form-grid"><label class="full">Proyecto<input data-h-meta="name" value="${esc(p.name||p.nombre||'')}"></label><label>Cliente<select data-h-client>${clientOptions(p)}</select></label><label>Cliente / contacto<input data-h-meta="client" value="${esc(p.client||'')}"></label><label class="full">Dirección / ubicación<input data-h-meta="address" value="${esc(p.address||'')}"></label><label>Fecha<input data-h-meta="date" type="date" value="${esc(p.date||p.fecha||'')}"></label><label>Nº EXPTE<input data-h-meta="expte" value="${esc(p.expte||'')}"></label><label>Referencia<input data-h-meta="ref" value="${esc(p.ref||p.numero||'')}"></label><label>Estado<select data-h-meta="phase"><option ${p.phase==='Borrador'?'selected':''}>Borrador</option><option ${p.phase==='Enviado'?'selected':''}>Enviado</option><option ${p.phase==='Aceptado'?'selected':''}>Aceptado</option><option ${p.phase==='Rechazado'?'selected':''}>Rechazado</option></select></label></div></div>`}
function card(title,body,extra=''){return `<div class="card panel honor-card"><div class="page-head" style="margin-bottom:10px"><h3>${title}</h3>${extra?`<div class="grow"></div>${extra}`:''}</div>${body}</div>`}
function editor(p){
 normalize(p);
 const zones=p.zonas.map((z,i)=>`<div class="h-grid-row h-zone" data-i="${i}"><input data-k="nombre" placeholder="Zona (p. ej. Planta 0 — Jardín)" value="${esc(z.nombre||'')}"><input data-k="m2" placeholder="m²" value="${esc(z.m2||'')}"><button class="btn danger" data-h-remove="zone:${i}">×</button></div>`).join('');
 const scope=p.scope_items.map((x,i)=>`<div class="h-block-row" data-scope="${i}"><textarea data-k="texto">${esc(x.texto||'')}</textarea><button class="btn danger" data-h-remove="scope:${i}">×</button></div>`).join('');
 const phases=p.fases_obra.map((x,i)=>`<div class="h-phase-row" data-phase="${i}"><input data-k="periodo" placeholder="Periodo (De marzo a abril)" value="${esc(x.periodo||'')}"><input data-k="frecuencia" placeholder="Frecuencia (1-2 visitas/mes)" value="${esc(x.frecuencia||'')}"><textarea data-k="descripcion" placeholder="Descripción">${esc(x.descripcion||'')}</textarea><button class="btn danger" data-h-remove="phase:${i}">×</button></div>`).join('');
 const fees=p.fee_lines.map((x,i)=>`<div class="h-fee-row" data-fee="${i}"><input data-k="concepto" placeholder="Concepto" value="${esc(x.concepto||x.description||'')}"><input data-k="importe" type="number" step="0.01" placeholder="€" value="${num(x.importe??x.amount)}"><textarea data-k="formaPago" placeholder="Forma de pago">${esc(x.formaPago||'')}</textarea><button class="btn danger" data-h-remove="fee:${i}">×</button></div>`).join('');
 const clauses=p.clausulas.map((x,i)=>`<div class="h-block-row" data-clause="${i}"><textarea data-k="texto">${esc(x.texto||x)}</textarea><button class="btn danger" data-h-remove="clause:${i}">×</button></div>`).join('');
 return `<div id="honorarios-v2">${meta(p)}
 ${card('A.- Objeto de la intervención',`<textarea data-h-field="intro_text" style="min-height:110px" placeholder="Describe el objeto del encargo…">${esc(p.intro_text||'')}</textarea><div class="toolbar" style="margin-top:8px"><button class="btn" data-h-intro="1">Plantilla: “A continuación se desarrollan…”</button><button class="btn" data-h-intro="2">Plantilla: “A petición de…”</button></div>`)}
 ${card('Zonas de estudio y superficies',`<div id="h-zones">${zones||'<div class="empty">Sin zonas definidas.</div>'}</div>`,`<button class="btn" data-h-add="zone">+ Añadir zona</button>`)}
 ${card('El proyecto incluye',`<div id="h-scope">${scope||'<div class="empty">Añade las partidas que forman parte del alcance.</div>'}</div><div class="toolbar h-template-list" style="margin-top:10px">${SCOPE.map((x,i)=>`<button class="btn" data-h-scope-template="${i}" title="${esc(x)}">${esc(x.slice(0,42))}${x.length>42?'…':''}</button>`).join('')}<button class="btn" data-h-add="scope">+ Línea en blanco</button></div>`)}
 ${card('Redacción del proyecto',`<label style="display:flex;gap:8px;align-items:center"><input type="checkbox" data-h-redaccion ${p.redaccion_toggle?'checked':''}> Incluir esta línea en la propuesta</label><input data-h-field="redaccion_texto" style="margin-top:9px" value="${esc(p.redaccion_texto||'')}">`)}
 ${card('Dirección de obra incluye',`<div id="h-phases">${phases||'<div class="empty">Sin fases de dirección definidas.</div>'}</div><label style="display:block;margin-top:12px">Resumen / cierre<textarea data-h-field="direccion_resumen" style="min-height:75px">${esc(p.direccion_resumen||'')}</textarea></label>`,`<button class="btn" data-h-add="phase">+ Añadir fase</button>`)}
 ${card('Calculadora de honorarios',`<div class="form-grid"><label><input type="radio" name="h-calc-method" value="pem" checked> Por presupuesto de ejecución material (PEM)</label><label><input type="radio" name="h-calc-method" value="m2"> Por superficie del área de estudio (m²)</label><label class="full">Valor<input id="h-calc-value" type="number" step="any" placeholder="Importe en € o m²"></label></div><div id="h-calc-results" style="margin-top:12px"></div>`)}
 ${card('Consultoría por horas',`<div class="table-wrap"><table class="table"><tr><th>Perfil</th><th>Tarifa</th><th>Horas</th><th>Subtotal</th></tr>${HOURLY.map(([k,l,r])=>`<tr><td>${esc(l)}</td><td>${money(r)}/h</td><td><input type="number" min="0" step="0.25" value="0" data-h-hour="${k}" style="width:90px"></td><td data-h-hour-total="${k}">${money(0)}</td></tr>`).join('')}</table></div><div class="page-head" style="margin-top:8px"><b id="h-hour-grand">Total: ${money(0)}</b><div class="grow"></div><button class="btn" data-h-add-hour>+ Añadir como honorario</button></div>`)}
 ${card('C.- Propuesta de honorarios',`<div id="h-fees">${fees||'<div class="empty">Sin conceptos de honorarios.</div>'}</div><div class="page-head" style="margin-top:12px"><button class="btn" data-h-add="fee">+ Añadir concepto</button><div class="grow"></div><div class="info"><small>Total (IVA no incluido)</small><b id="h-fee-total">${money(total(p))}</b></div></div>`)}
 ${card('Cláusulas',`<div id="h-clauses">${clauses||'<div class="empty">Sin cláusulas.</div>'}</div>`,`<button class="btn" data-h-add="clause">+ Añadir cláusula</button>`)}
 <div id="pp-extra-controls" class="card panel"><div class="page-head"><div><h3>Documento y acciones</h3><small style="color:var(--muted)">Se conserva la estructura de la propuesta de honorarios anterior.</small></div><div class="grow"></div><div class="toolbar"><button class="btn" data-h-view="client">Vista cliente</button><button class="btn primary" data-h-save>Guardar honorarios</button><button class="btn" data-action="budget-to-project">Convertir en proyecto</button><button class="btn" data-action="budget-to-invoice">Crear factura</button></div></div><div id="h-save-error"></div></div>
 </div>`;
}

function findBracket(list,v){return list.find(x=>v>=x[0]&&(v<x[1]||x[1]===Infinity))||list[list.length-1]}
function calcRender(p){const value=num($('#h-calc-value')?.value),out=$('#h-calc-results');if(!out)return;if(value<=0){out.innerHTML='<div class="empty">Introduce un valor para obtener una orientación.</div>';return}const method=$('input[name="h-calc-method"]:checked')?.value||'pem';let project=null,direction=null,totalFee=0,hint='';if(method==='pem'){const b=findBracket(PEM,value);project=value*b[2];direction=value*b[3];totalFee=project+direction;hint=`PEM: Proyecto ${(b[2]*100).toLocaleString('es-ES',{maximumFractionDigits:2})}% · Dirección ${(b[3]*100).toLocaleString('es-ES',{maximumFractionDigits:2})}%`;}else{const b=findBracket(AREA,value);totalFee=b[2];hint=`Baremo de superficie: ${b[0]}–${b[1]} m²`;}out.innerHTML=`<div class="notice"><b>${esc(hint)}</b></div>${method==='pem'?`<div class="grid cols-2" style="margin-top:8px"><div class="info"><small>Proyecto</small><b>${money(project)}</b></div><div class="info"><small>Dirección de obra</small><b>${money(direction)}</b></div></div><div class="toolbar" style="margin-top:8px"><button class="btn" data-h-use-fee="Proyecto|${project}">Usar Proyecto</button><button class="btn" data-h-use-fee="Dirección de obra|${direction}">Usar Dirección</button></div>`:`<div class="page-head"><div class="info"><small>Encargo completo</small><b>${money(totalFee)}</b></div><div class="grow"></div><button class="btn" data-h-use-fee="Honorarios (encargo completo)|${totalFee}">Usar importe</button></div>`}<h4 style="margin:14px 0 6px">Fases — encargo completo</h4><table class="table"><tr><th>Fase</th><th>%</th><th>Importe</th><th></th></tr>${PHASE_FULL.map(([n,pct])=>`<tr><td>${esc(n)}</td><td>${(pct*100).toLocaleString('es-ES')}%</td><td>${money(totalFee*pct)}</td><td><button class="btn" data-h-use-fee="${esc(n)}|${totalFee*pct}">Usar</button></td></tr>`).join('')}</table><h4 style="margin:14px 0 6px">Fases — contratadas en solitario</h4><table class="table"><tr><th>Fase</th><th>%</th><th>Importe</th><th></th></tr>${PHASE_SINGLE.map(([n,pct])=>`<tr><td>${esc(n)}</td><td>${(pct*100).toLocaleString('es-ES')}%</td><td>${money(totalFee*pct)}</td><td><button class="btn" data-h-use-fee="${esc(n)}|${totalFee*pct}">Usar</button></td></tr>`).join('')}</table>`;bindUseFees(p)}
function addFee(p,concept,amount){normalize(p);const existing=p.fee_lines.find(x=>(x.concepto||x.description)===concept);if(existing){existing.concepto=concept;existing.importe=Number(amount).toFixed(2)}else p.fee_lines.push({id:uid(),concepto:concept,importe:Number(amount).toFixed(2),formaPago:'',vat:21});rerender()}
function bindUseFees(p){$$('[data-h-use-fee]').forEach(b=>b.onclick=()=>{const raw=b.dataset.hUseFee,cut=raw.lastIndexOf('|');addFee(p,raw.slice(0,cut),num(raw.slice(cut+1)))})}
function hourly(){let total=0;HOURLY.forEach(([k,l,r])=>{const h=num($(`[data-h-hour="${k}"]`)?.value),v=h*r,totalEl=$(`[data-h-hour-total="${k}"]`);if(totalEl)totalEl.textContent=money(v);total+=v});const g=$('#h-hour-grand');if(g)g.textContent='Total: '+money(total);return total}
function rerender(){const area=$('.budget-content');const p=current();if(!area||!p)return;area.innerHTML=editor(p);const summary=$('.budget-summary');if(summary)summary.innerHTML=`<h3 style="font:20px Georgia,serif;margin-top:0">Resumen</h3>${p.fee_lines.map(x=>`<div class="sumRow"><span>${esc(x.concepto||x.description||'(sin concepto)')}</span><span class="amt">${money(x.importe??x.amount)}</span></div>`).join('')}<hr><div class="info"><small>Total (sin IVA)</small><b>${money(total(p))}</b></div>`;bind(p)}
async function save(p){normalize(p);const phase=p.phase||'Borrador',state=/acept/i.test(phase)?'aceptado':/envi/i.test(phase)?'enviado':/rech/i.test(phase)?'rechazado':'borrador';const payload={nombre:p.name||p.nombre||'Presupuesto de honorarios',name:p.name||p.nombre||'Presupuesto de honorarios',cliente_id:p.cliente_id||null,fecha:p.date||p.fecha||new Date().toISOString().slice(0,10),date:p.date||p.fecha||new Date().toISOString().slice(0,10),numero:p.ref||p.numero||null,ref:p.ref||p.numero||null,client:p.client||null,address:p.address||null,expte:p.expte||null,phase,estado:state,status:p.status||'Borrador',kind:'honorarios',intro_text:p.intro_text||'',zonas:p.zonas,scope_items:p.scope_items,redaccion_toggle:!!p.redaccion_toggle,redaccion_texto:p.redaccion_texto||'',fases_obra:p.fases_obra,direccion_resumen:p.direccion_resumen||'',fee_lines:p.fee_lines,clausulas:p.clausulas,base:total(p),total:total(p),updated_at:new Date().toISOString()};const {error}=await db().from('presupuestos').update(payload).eq('id',p.id);if(error)throw error;if(window.reloadIriarte){await window.reloadIriarte();window.APP.sel.budget=p.id;window.APP.budgetKind='honorarios';window.APP.budgetView='edit';if(window.renderIriarte)window.renderIriarte()} }
function bind(p){
 $$('[data-h-meta]').forEach(x=>x.oninput=()=>{p[x.dataset.hMeta]=x.value});const cl=$('[data-h-client]');if(cl)cl.onchange=()=>{p.cliente_id=cl.value||null;p.client=(window.APP.data.clientes.find(x=>String(x.id)===String(cl.value))?.nombre)||p.client||'';rerender()};
 $$('[data-h-field]').forEach(x=>x.oninput=()=>{p[x.dataset.hField]=x.value});const red=$('[data-h-redaccion]');if(red)red.onchange=()=>p.redaccion_toggle=red.checked;
 $$('[data-i] input').forEach(x=>x.oninput=()=>p.zonas[+x.closest('[data-i]').dataset.i][x.dataset.k]=x.value);
 $$('[data-scope] textarea').forEach(x=>x.oninput=()=>p.scope_items[+x.closest('[data-scope]').dataset.scope].texto=x.value);
 $$('[data-phase] input,[data-phase] textarea').forEach(x=>x.oninput=()=>p.fases_obra[+x.closest('[data-phase]').dataset.phase][x.dataset.k]=x.value);
 $$('[data-fee] input,[data-fee] textarea').forEach(x=>x.oninput=()=>{const f=p.fee_lines[+x.closest('[data-fee]').dataset.fee],k=x.dataset.k;f[k]=k==='importe'?x.value:x.value;const t=$('#h-fee-total');if(t)t.textContent=money(total(p))});
 $$('[data-clause] textarea').forEach(x=>x.oninput=()=>p.clausulas[+x.closest('[data-clause]').dataset.clause].texto=x.value);
 $$('[data-h-remove]').forEach(b=>b.onclick=()=>{const [type,i0]=b.dataset.hRemove.split(':'),i=+i0,key={zone:'zonas',scope:'scope_items',phase:'fases_obra',fee:'fee_lines',clause:'clausulas'}[type];p[key].splice(i,1);rerender()});
 $$('[data-h-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.hAdd;if(type==='zone')p.zonas.push({id:uid(),nombre:'',m2:''});if(type==='scope')p.scope_items.push({id:uid(),texto:''});if(type==='phase')p.fases_obra.push({id:uid(),periodo:'',frecuencia:'',descripcion:''});if(type==='fee')p.fee_lines.push({id:uid(),concepto:'',importe:'',formaPago:'',vat:21});if(type==='clause')p.clausulas.push({id:uid(),texto:''});rerender()});
 $$('[data-h-scope-template]').forEach(b=>b.onclick=()=>{p.scope_items.push({id:uid(),texto:SCOPE[+b.dataset.hScopeTemplate]});rerender()});
 $$('[data-h-intro]').forEach(b=>b.onclick=()=>{p.intro_text=b.dataset.hIntro==='1'?`A continuación se desarrollan las premisas básicas y líneas generales que regirán el Proyecto y Dirección de obra para [OBJETO], en ${p.address||'[UBICACIÓN]'}.`:`A petición de ${p.client||'[CLIENTE]'}, seguidamente se desarrollan las líneas generales que regirán [OBJETO], que abarcará los siguientes apartados:`;rerender()});
 $$('input[name="h-calc-method"]').forEach(x=>x.onchange=()=>calcRender(p));const cv=$('#h-calc-value');if(cv)cv.oninput=()=>calcRender(p);calcRender(p);
 $$('[data-h-hour]').forEach(x=>x.oninput=hourly);const ah=$('[data-h-add-hour]');if(ah)ah.onclick=()=>addFee(p,'Consultoría por horas',hourly());
 const saveBtn=$('[data-h-save]');if(saveBtn)saveBtn.onclick=async()=>{saveBtn.disabled=true;try{await save(p)}catch(err){const e=$('#h-save-error');if(e)e.innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`}finally{saveBtn.disabled=false}};
 const view=$('[data-h-view]');if(view)view.onclick=()=>{window.APP.budgetView='client';if(window.renderIriarte)window.renderIriarte()};
}

function proposal(p){normalize(p);const hasZones=p.zonas.some(x=>x.nombre||x.m2),hasScope=p.scope_items.some(x=>x.texto),hasPhases=p.fases_obra.some(x=>x.periodo||x.descripcion)||p.direccion_resumen;return `<div id="honorarios-doc-v2" class="doc-sheet"><div class="hon-doc-head"><div><div class="pp-brand">Sonsoles Pérez Iriarte</div><div class="pp-subbrand">JARDINERÍA Y PAISAJISMO</div></div><div style="text-align:right"><b>PROPUESTA INTERVENCIÓN</b><br>Estudio de Adecuación Paisajística<br>${esc(p.address||'')}<br>Nº EXPTE ${esc(p.expte||'—')}</div></div><h3>A.- OBJETO DE LA INTERVENCIÓN</h3><p class="h-pre">${esc(p.intro_text||'')}</p>${(hasZones||hasScope||hasPhases)?`<h3>B.- ORGANIZACIÓN DE LOS TRABAJOS</h3>${hasZones?`<table><tr><th>Zona</th><th>m²</th></tr>${p.zonas.filter(x=>x.nombre||x.m2).map(x=>`<tr><td>${esc(x.nombre||'')}</td><td>${esc(x.m2||'')}</td></tr>`).join('')}</table>`:''}${hasScope?`<p><b>El proyecto incluye:</b></p><ul>${p.scope_items.filter(x=>x.texto).map(x=>`<li>${esc(x.texto)}</li>`).join('')}</ul>`:''}${p.redaccion_toggle&&p.redaccion_texto?`<p><u>${esc(p.redaccion_texto)}</u></p>`:''}${hasPhases?`<p><b>Dirección de obra incluye</b></p><ul>${p.fases_obra.filter(x=>x.periodo||x.descripcion).map(x=>`<li><u>${esc(x.periodo||'')}${x.frecuencia?', '+esc(x.frecuencia):''}</u>${x.descripcion?': '+esc(x.descripcion):''}</li>`).join('')}</ul>${p.direccion_resumen?`<p class="h-pre">${esc(p.direccion_resumen)}</p>`:''}`:''}`:''}<h3>C.- PROPUESTA DE HONORARIOS</h3><table><tr><th>Concepto</th><th>Honorarios (IVA no incluido)</th><th>Forma de pago</th></tr>${p.fee_lines.map(x=>`<tr><td>${esc(x.concepto||x.description||'')}</td><td>${money(x.importe??x.amount)}</td><td class="h-pre">${esc(x.formaPago||'')}</td></tr>`).join('')}<tr><td><b>Total honorarios</b></td><td><b>${money(total(p))}</b></td><td></td></tr></table>${p.clausulas.some(x=>x.texto||x)?`<h3>CLÁUSULAS</h3><ul>${p.clausulas.filter(x=>x.texto||x).map(x=>`<li>${esc(x.texto||x)}</li>`).join('')}</ul>`:''}<p style="text-align:right;margin-top:28px">${esc(p.date||p.fecha||'')}</p><div class="hon-privacy">Tratamos sus datos en base a la existencia de un contrato, precontrato o relación comercial entre ambas partes. Puede ejercer sus derechos y obtener más información en iriartepaisajista@gmail.com.</div></div>`}
function printProposal(p){const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Honorarios - ${esc(p.name||p.nombre||'Proyecto')}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font:11px/1.45 Arial,sans-serif;color:#232b20}.pp-brand{font:22px Georgia,serif;color:#3f5a35}.pp-subbrand{font-size:8px;letter-spacing:2px;color:#687263}.hon-doc-head{display:flex;justify-content:space-between;border-bottom:1px solid #cfc8b9;padding-bottom:14px;margin-bottom:24px}.doc-sheet h3{font:16px Georgia,serif;color:#3f5a35;margin:24px 0 8px}.doc-sheet table{width:100%;border-collapse:collapse;margin:9px 0 18px}.doc-sheet th,.doc-sheet td{border-bottom:1px solid #e3ded2;padding:7px;text-align:left;vertical-align:top}.doc-sheet th{font-size:9px;color:#687263}.doc-sheet li{margin-bottom:5px}.h-pre{white-space:pre-wrap}.hon-privacy{font-size:8px;color:#777;border-top:1px solid #ded8ca;padding-top:8px;margin-top:30px}</style></head><body>${proposal(p)}<script>window.onload=()=>setTimeout(()=>window.print(),150)<\/script></body></html>`);w.document.close()}
function enhanceView(){const A=window.APP,p=current(),area=$('.budget-content');if(!A||A.route!=='presupuestos'||!p||(p.kind||'obra')!=='honorarios'||!area)return;if(A.budgetView==='edit'){if($('#honorarios-v2'))return;area.innerHTML=editor(p);const s=$('.budget-summary');if(s)s.innerHTML=`<h3 style="font:20px Georgia,serif;margin-top:0">Resumen</h3>${p.fee_lines.map(x=>`<div class="sumRow"><span>${esc(x.concepto||x.description||'(sin concepto)')}</span><span class="amt">${money(x.importe??x.amount)}</span></div>`).join('')}<hr><div class="info"><small>Total (sin IVA)</small><b>${money(total(p))}</b></div>`;bind(p)}else if(A.budgetView==='client'){if($('#honorarios-doc-v2'))return;area.innerHTML=`<div class="toolbar no-print" style="margin-bottom:12px"><button class="btn primary" data-h-print>Imprimir / Guardar PDF</button><button class="btn" data-h-edit>Volver a edición</button></div>${proposal(p)}`;area.querySelector('[data-h-print]').onclick=()=>printProposal(p);area.querySelector('[data-h-edit]').onclick=()=>{A.budgetView='edit';window.renderIriarte?.()}}
}
function schedule(){clearTimeout(timer);timer=setTimeout(enhanceView,70)}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',schedule);window.addEventListener('load',schedule);
})();
