// Iriarte ERP V2 · fotos y adjuntos de obra
(function(){
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const db=()=>window.__iriarteDb;
let timer;
function safeName(name){return String(name||'foto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/_+/g,'_').slice(-140)}
function findRecord(table,id){const D=window.APP?.data||{},key={obra_visitas:'visitas',obra_tareas:'tareas',obra_incidencias:'incidencias'}[table];return (D[key]||[]).find(x=>String(x.id)===String(id))}
function projectOf(x){return x?.project_id||x?.proyecto_id||window.APP?.sel?.project||null}
function label(table,x){if(table==='obra_tareas')return 'Tarea · '+(x?.titulo||'');if(table==='obra_incidencias')return 'Incidencia · '+(x?.titulo||'');return 'Visita · '+(x?.titulo||x?.fecha||'obra')}
function open(table,id){
 const client=db(),x=findRecord(table,id);if(!client||!x)return;
 const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(720px,95vw)"><div class="modal-head"><div><h2>Adjuntar foto / archivo</h2><small style="color:var(--muted)">${esc(label(table,x))}</small></div><div class="grow"></div><button class="btn" type="button" data-photo-close>Cerrar</button></div><form id="photo-form"><div class="modal-body"><div class="form-grid"><label class="full">Archivo<input id="photo-file" type="file" accept="image/*,.pdf" required style="display:block;width:100%;margin-top:6px"></label><label class="full">Nombre<input name="nombre" placeholder="Se completa automáticamente"></label><label class="full">Descripción<textarea name="descripcion" placeholder="Detalle de la foto o documento"></textarea></label></div><div id="photo-progress" class="notice" style="display:none"></div><div id="photo-error"></div></div><div class="modal-foot"><button class="btn" type="button" data-photo-close>Cancelar</button><button class="btn primary" type="submit">Subir archivo</button></div></form></div></div>`;
 const close=()=>root.innerHTML='';root.querySelectorAll('[data-photo-close]').forEach(b=>b.onclick=close);const fi=$('#photo-file');fi.onchange=()=>{if(fi.files?.[0]&&!$('#photo-form').elements.nombre.value)$('#photo-form').elements.nombre.value=fi.files[0].name};
 $('#photo-form').onsubmit=async e=>{e.preventDefault();const submit=e.submitter,progress=$('#photo-progress'),err=$('#photo-error');submit.disabled=true;let path='';try{const f=fi.files?.[0];if(!f)throw new Error('Selecciona un archivo.');const pid=projectOf(x);if(!pid)throw new Error('El registro no está vinculado a ningún proyecto.');const vals=Object.fromEntries(new FormData(e.currentTarget).entries());path=`${pid}/${table}/${id}/${Date.now()}-${safeName(f.name)}`;progress.style.display='block';progress.textContent='Subiendo archivo…';const up=await client.storage.from('obra-fotos').upload(path,f,{cacheControl:'3600',upsert:false,contentType:f.type||undefined});if(up.error)throw up.error;const payload={proyecto_id:pid,nombre:(vals.nombre||f.name).trim(),tipo:f.type?.startsWith('image/')?'Foto de obra':'Documento de obra',descripcion:vals.descripcion||label(table,x),archivo_nombre:f.name,archivo_ruta:'obra-fotos/'+path,mime_type:f.type||null,tamano_bytes:f.size,fecha_documento:new Date().toISOString().slice(0,10),tarea_id:table==='obra_tareas'?id:null,incidencia_id:table==='obra_incidencias'?id:null,notas:table==='obra_visitas'?`Vinculado a visita ${id}`:null};const ins=await client.from('documentos').insert(payload);if(ins.error)throw ins.error;close();if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(ex){if(path){try{await client.storage.from('obra-fotos').remove([path])}catch(_){}}progress.style.display='none';err.innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(ex.message||ex)}</div>`;submit.disabled=false}}
}
function decorate(){clearTimeout(timer);timer=setTimeout(()=>{if(window.APP?.route!=='obra')return;document.querySelectorAll('[data-op-delete^="obra_visitas:"],[data-op-delete^="obra_tareas:"],[data-op-delete^="obra_incidencias:"]').forEach(del=>{const parent=del.parentElement;if(parent.querySelector('[data-photo-attach]'))return;const value=del.dataset.opDelete,b=document.createElement('button');b.type='button';b.className='btn';b.textContent='Adjuntar';b.dataset.photoAttach=value;parent.insertBefore(b,del)})},90)}
new MutationObserver(decorate).observe(document.body,{subtree:true,childList:true});window.addEventListener('hashchange',decorate);window.addEventListener('load',decorate);
document.addEventListener('click',e=>{const b=e.target.closest('[data-photo-attach]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const [table,id]=b.dataset.photoAttach.split(':');open(table,id)},true);
})();
