// Iriarte ERP V2 · edición de registros operativos
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
let timer;
function modal(title,body,onSave){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-oe-close>Cerrar</button></div><form id="oe-form"><div class="modal-body">${body}<div id="oe-error"></div></div><div class="modal-foot"><button type="button" class="btn" data-oe-close>Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form></div></div>`;const close=()=>root.innerHTML='';root.querySelectorAll('[data-oe-close]').forEach(b=>b.onclick=close);$('#oe-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await onSave(Object.fromEntries(new FormData(e.currentTarget).entries()));close();if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#oe-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}}
function get(table,id){const D=window.APP?.data||{};const key={obra_visitas:'visitas',obra_tareas:'tareas',obra_incidencias:'incidencias',horas_proyecto:'horas',documentos:'docs'}[table];return (D[key]||[]).find(x=>String(x.id)===String(id))}
function edit(table,id){const x=get(table,id);if(!x)return;
 if(table==='obra_visitas')return modal('Editar visita',`<div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${esc(x.fecha||'')}"></label><label>Estado de obra<input name="estado_obra" value="${esc(x.estado_obra||'')}"></label><label class="full">Título<input name="titulo" value="${esc(x.titulo||'')}"></label><label class="full">Asistentes<input name="asistentes" value="${esc(x.asistentes||'')}"></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label><label class="full">Observaciones<textarea name="observaciones">${esc(x.observaciones||'')}</textarea></label></div>`,async f=>{const {error}=await db().from(table).update({fecha:f.fecha,titulo:f.titulo||null,descripcion:f.descripcion||null,asistentes:f.asistentes||null,estado_obra:f.estado_obra||null,observaciones:f.observaciones||null}).eq('id',id);if(error)throw error});
 if(table==='obra_tareas')return modal('Editar tarea',`<div class="form-grid"><label class="full">Título<input name="titulo" value="${esc(x.titulo||'')}" required></label><label>Prioridad<select name="prioridad"><option ${x.prioridad==='baja'?'selected':''}>baja</option><option ${x.prioridad==='normal'?'selected':''}>normal</option><option ${x.prioridad==='alta'?'selected':''}>alta</option><option ${x.prioridad==='urgente'?'selected':''}>urgente</option></select></label><label>Estado<select name="estado"><option ${x.estado==='pendiente'?'selected':''}>pendiente</option><option ${x.estado==='en_curso'?'selected':''}>en_curso</option><option ${x.estado==='completada'?'selected':''}>completada</option><option ${x.estado==='cancelada'?'selected':''}>cancelada</option></select></label><label>Fecha límite<input name="fecha_limite" type="date" value="${esc(x.fecha_limite||'')}"></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label></div>`,async f=>{const completed=f.estado==='completada'?(x.fecha_completada||new Date().toISOString().slice(0,10)):null;const {error}=await db().from(table).update({titulo:f.titulo,descripcion:f.descripcion||null,prioridad:f.prioridad,estado:f.estado,fecha_limite:f.fecha_limite||null,fecha_completada:completed}).eq('id',id);if(error)throw error});
 if(table==='obra_incidencias')return modal('Editar incidencia',`<div class="form-grid"><label class="full">Título<input name="titulo" value="${esc(x.titulo||'')}" required></label><label>Tipo<input name="tipo" value="${esc(x.tipo||'')}"></label><label>Prioridad<select name="prioridad"><option ${x.prioridad==='baja'?'selected':''}>baja</option><option ${x.prioridad==='normal'?'selected':''}>normal</option><option ${x.prioridad==='alta'?'selected':''}>alta</option><option ${x.prioridad==='urgente'?'selected':''}>urgente</option></select></label><label>Estado<select name="estado"><option ${x.estado==='abierta'?'selected':''}>abierta</option><option ${x.estado==='en_curso'?'selected':''}>en_curso</option><option ${x.estado==='resuelta'?'selected':''}>resuelta</option><option ${x.estado==='cerrada'?'selected':''}>cerrada</option></select></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label><label class="full">Solución<textarea name="solucion">${esc(x.solucion||'')}</textarea></label></div>`,async f=>{const done=/resuelta|cerrada/.test(f.estado)?(x.fecha_resolucion||new Date().toISOString().slice(0,10)):null;const {error}=await db().from(table).update({titulo:f.titulo,tipo:f.tipo||null,prioridad:f.prioridad,estado:f.estado,descripcion:f.descripcion||null,solucion:f.solucion||null,fecha_resolucion:done}).eq('id',id);if(error)throw error});
 if(table==='horas_proyecto')return modal('Editar horas',`<div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${esc(x.fecha||'')}"></label><label>Persona<input name="persona" value="${esc(x.persona||'')}" required></label><label>Horas<input name="horas" type="number" step="0.1" value="${num(x.horas)}"></label><label>Coste/hora<input name="coste_hora" type="number" step="0.01" value="${num(x.coste_hora)}"></label><label class="full">Concepto<textarea name="concepto">${esc(x.concepto||'')}</textarea></label><label class="full">Notas<textarea name="notas">${esc(x.notas||'')}</textarea></label></div>`,async f=>{const {error}=await db().from(table).update({fecha:f.fecha,persona:f.persona,horas:num(f.horas),coste_hora:num(f.coste_hora),concepto:f.concepto||null,notas:f.notas||null}).eq('id',id);if(error)throw error});
 if(table==='documentos')return modal('Editar documento',`<div class="form-grid"><label class="full">Nombre<input name="nombre" value="${esc(x.nombre||'')}" required></label><label>Tipo<input name="tipo" value="${esc(x.tipo||'')}"></label><label>Fecha documento<input name="fecha_documento" type="date" value="${esc(x.fecha_documento||'')}"></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label><label class="full">Notas<textarea name="notas">${esc(x.notas||'')}</textarea></label></div>`,async f=>{const {error}=await db().from(table).update({nombre:f.nombre,tipo:f.tipo||null,fecha_documento:f.fecha_documento||null,descripcion:f.descripcion||null,notas:f.notas||null}).eq('id',id);if(error)throw error});
}
function decorate(){clearTimeout(timer);timer=setTimeout(()=>{if(!['obra','horas','documentos'].includes(window.APP?.route))return;document.querySelectorAll('[data-op-delete]').forEach(del=>{if(del.parentElement.querySelector('[data-op-edit]'))return;const [table,id]=del.dataset.opDelete.split(':');const b=document.createElement('button');b.className='btn';b.textContent='Editar';b.dataset.opEdit=table+':'+id;del.parentElement.insertBefore(b,del)})},80)}
new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',decorate);window.addEventListener('load',decorate);
document.addEventListener('click',e=>{const b=e.target.closest('[data-op-edit]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const [table,id]=b.dataset.opEdit.split(':');edit(table,id)},true);
})();
