// Iriarte ERP V2 · costes mensuales de personal e imputaciones por proyecto
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
let loading=false,loaded=false,timer;
function D(){return window.APP?.data||{}}
function projectName(id){return (D().proyectos||[]).find(x=>String(x.id)===String(id))?.nombre||'—'}
function monthKey(v){return String(v||'').slice(0,7)}
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function toast(msg,bad=false){const t=$('#toast');if(!t)return;t.textContent=msg;t.style.background=bad?'#8f4d3c':'#253120';t.classList.add('show');clearTimeout(t._pc);t._pc=setTimeout(()=>t.classList.remove('show'),2600)}
async function load(){
 if(loading||!db()||!window.APP)return;loading=true;
 try{
  const [{data:costs,error:e1},{data:allocs,error:e2}]=await Promise.all([
   db().from('costes_personal_mensuales').select('*').order('periodo',{ascending:false}).order('persona'),
   db().from('costes_personal_imputaciones').select('*').order('created_at')
  ]);
  if(e1)throw e1;if(e2)throw e2;
  window.APP.data.costesPersonal=costs||[];window.APP.data.imputacionesPersonal=allocs||[];loaded=true;
 }catch(err){console.warn('Costes personal',err.message||err)}finally{loading=false}
}
const baseReload=window.reloadIriarte;
if(baseReload)window.reloadIriarte=async()=>{await baseReload();await load();window.renderIriarte?.();schedule()};
function allocations(costId){return (D().imputacionesPersonal||[]).filter(x=>String(x.coste_personal_id)===String(costId))}
function assigned(costId){return allocations(costId).reduce((a,x)=>a+num(x.importe),0)}
function people(){return [...new Set((D().horas||[]).map(x=>String(x.persona||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function monthHours(month){
 const map=new Map();(D().horas||[]).filter(x=>monthKey(x.fecha)===month).forEach(x=>{const k=`${x.persona}¦${x.proyecto_id}`,v=map.get(k)||{persona:x.persona,proyecto_id:x.proyecto_id,horas:0,coste:0};v.horas+=num(x.horas);v.coste+=num(x.horas)*num(x.coste_hora);map.set(k,v)});return [...map.values()].sort((a,b)=>String(a.persona).localeCompare(String(b.persona),'es')||projectName(a.proyecto_id).localeCompare(projectName(b.proyecto_id),'es'))
}
function costOptions(){return [['autonomos','Autónomos / Seguridad Social'],['seguridad_social','Seguridad Social'],['salario_fijo','Salario fijo'],['seguro_personal','Seguro / coste laboral'],['otro','Otro coste de personal']]}
function movementOptions(month){return (D().movs||[]).filter(x=>monthKey(x.fecha)===month&&num(x.total)!==0).map(x=>`<option value="${esc(x.id)}">${esc(x.fecha)} · ${esc(x.concepto||'Movimiento')} · ${money(x.total)}</option>`).join('')}
function openNew(){
 const root=$('#modal-root'),month=(D().horas||[]).map(x=>monthKey(x.fecha)).filter(Boolean).sort().reverse()[0]||currentMonth(),plist=people();
 root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>Nuevo coste mensual de personal</h2><div class="grow"></div><button class="btn" data-pc-close>Cerrar</button></div><form id="pc-new"><div class="modal-body"><div class="form-grid"><label>Mes<input name="periodo" type="month" value="${esc(month)}" required></label><label>Persona<input name="persona" list="pc-people" required placeholder="Sonsoles"><datalist id="pc-people">${plist.map(x=>`<option value="${esc(x)}">`).join('')}</datalist></label><label>Tipo<select name="tipo">${costOptions().map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Importe<input name="importe" type="number" min="0" step="0.01" required></label><label class="full">Concepto<input name="concepto" value="Seguridad Social / coste mensual" required></label><label class="full">Movimiento bancario relacionado (opcional)<select name="movimiento_financiero_id"><option value="">— Sin vincular todavía —</option>${movementOptions(month)}</select></label><label class="full">Notas<textarea name="notas"></textarea></label></div><div class="notice"><b>Reparto automático:</b> al guardar se distribuirá el importe entre los proyectos según las horas de esta persona durante el mes. Después podrás revisarlo y modificarlo.</div><div id="pc-error"></div></div><div class="modal-foot"><button class="btn" type="button" data-pc-close>Cancelar</button><button class="btn primary" type="submit">Crear y repartir</button></div></form></div></div>`;
 const close=()=>root.innerHTML='';root.querySelectorAll('[data-pc-close]').forEach(b=>b.onclick=close);
 $('#pc-new').onsubmit=async e=>{e.preventDefault();const submit=e.submitter;submit.disabled=true;try{const f=Object.fromEntries(new FormData(e.currentTarget).entries()),row={periodo:f.periodo+'-01',persona:f.persona.trim(),tipo:f.tipo,concepto:f.concepto.trim(),importe:num(f.importe),movimiento_financiero_id:f.movimiento_financiero_id||null,notas:f.notas||null,metodo_reparto:'horas_mes',estado:'borrador'};if(!row.persona)throw new Error('Indica la persona.');if(row.importe<0)throw new Error('El importe no puede ser negativo.');const {data,error}=await db().from('costes_personal_mensuales').insert(row).select('id').single();if(error)throw error;const rpc=await db().rpc('recalcular_imputaciones_coste_personal_v2',{p_coste_id:data.id});if(rpc.error)throw rpc.error;if(row.movimiento_financiero_id)await db().from('movimientos_financieros').update({categoria:'coste_personal',subcategoria:row.tipo}).eq('id',row.movimiento_financiero_id);close();await load();renderHours();openCost(data.id);toast('Coste creado y repartido por horas')}catch(err){$('#pc-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;submit.disabled=false}}
}
function rowHtml(x,c,locked){const cls=x.clasificacion||'proyecto';return `<tr data-pci="${esc(x.id||'new')}"><td><select data-pci-class ${locked?'disabled':''}><option value="proyecto" ${cls==='proyecto'?'selected':''}>Proyecto</option><option value="general" ${cls==='general'?'selected':''}>Estudio / general</option><option value="no_estudio" ${cls==='no_estudio'?'selected':''}>N · No estudio</option></select></td><td><select data-pci-project ${locked||cls!=='proyecto'?'disabled':''}><option value="">—</option>${(D().proyectos||[]).map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(x.proyecto_id)?'selected':''}>${esc(p.codigo||'')} · ${esc(p.nombre)}</option>`).join('')}</select></td><td><input data-pci-hours type="number" step="0.01" value="${num(x.horas_base)}" disabled></td><td><input data-pci-amount type="number" min="0" step="0.01" value="${num(x.importe).toFixed(2)}" ${locked?'disabled':''}></td><td>${x.ajuste_manual?'Manual':esc(x.metodo||'automático')}</td><td>${locked?'':'<button type="button" class="btn danger" data-pci-remove>Quitar</button>'}</td></tr>`}
function openCost(id){
 const c=(D().costesPersonal||[]).find(x=>String(x.id)===String(id));if(!c)return;const root=$('#modal-root'),list=allocations(c.id),locked=c.estado==='cerrado';
 root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(980px,97vw)"><div class="modal-head"><div><h2>${esc(c.persona)} · ${esc(c.concepto)}</h2><small style="color:var(--muted)">${esc(monthKey(c.periodo))} · ${money(c.importe)} · ${esc(c.estado)}</small></div><div class="grow"></div><button class="btn" data-pc-close>Cerrar</button></div><div class="modal-body"><div class="grid cols-4"><div class="info"><small>Coste origen</small><b>${money(c.importe)}</b></div><div class="info"><small>Imputado</small><b data-pc-assigned>${money(assigned(c.id))}</b></div><div class="info"><small>Diferencia</small><b data-pc-diff>${money(c.importe-assigned(c.id))}</b></div><div class="info"><small>Método</small><b>${esc(c.metodo_reparto)}</b></div></div><div class="table-wrap" style="margin-top:14px"><table class="table"><tr><th>Clasificación</th><th>Proyecto</th><th>Horas base</th><th>Importe</th><th>Origen</th><th></th></tr><tbody id="pc-alloc-body">${list.map(x=>rowHtml(x,c,locked)).join('')}</tbody></table></div>${locked?'<div class="notice"><b>Mes cerrado.</b> Reábrelo para modificar el reparto.</div>':'<div class="toolbar" style="margin-top:12px"><button class="btn" type="button" data-pc-add>+ Imputación manual</button><button class="btn" type="button" data-pc-recalc>Recalcular por horas</button><button class="btn primary" type="button" data-pc-save>Guardar reparto</button></div>'}<div id="pc-detail-error"></div></div><div class="modal-foot">${locked?'<button class="btn" type="button" data-pc-reopen>Reabrir</button>':'<button class="btn primary" type="button" data-pc-close-month>Cerrar mes</button>'}<button class="btn" type="button" data-pc-close>Cerrar</button></div></div></div>`;
 const close=()=>root.innerHTML='';root.querySelectorAll('[data-pc-close]').forEach(b=>b.onclick=close);
 function refreshDiff(){const vals=[...root.querySelectorAll('[data-pci-amount]')].reduce((a,x)=>a+num(x.value),0),diff=c.importe-vals;root.querySelector('[data-pc-assigned]').textContent=money(vals);root.querySelector('[data-pc-diff]').textContent=money(diff);root.querySelector('[data-pc-diff]').className=Math.abs(diff)>.01?'negative':'positive'}
 root.querySelectorAll('[data-pci-amount]').forEach(x=>x.oninput=refreshDiff);
 root.querySelectorAll('[data-pci-class]').forEach(x=>x.onchange=()=>{const pr=x.closest('tr').querySelector('[data-pci-project]');pr.disabled=x.value!=='proyecto';if(x.value!=='proyecto')pr.value=''});
 root.querySelectorAll('[data-pci-remove]').forEach(x=>x.onclick=()=>{x.closest('tr').remove();refreshDiff()});
 const add=root.querySelector('[data-pc-add]');if(add)add.onclick=()=>{root.querySelector('#pc-alloc-body').insertAdjacentHTML('beforeend',rowHtml({id:'new-'+Date.now(),clasificacion:'proyecto',proyecto_id:'',horas_base:0,importe:0,metodo:'manual',ajuste_manual:true},c,false));openCostBindings(root,c);refreshDiff()};
 const rec=root.querySelector('[data-pc-recalc]');if(rec)rec.onclick=async()=>{if(!confirm('Se sustituirá el reparto actual por el reparto automático según las horas del mes.'))return;const {error}=await db().rpc('recalcular_imputaciones_coste_personal_v2',{p_coste_id:c.id});if(error)return showErr(root,error);await load();openCost(c.id);toast('Reparto recalculado')};
 const save=root.querySelector('[data-pc-save]');if(save)save.onclick=async()=>saveAllocations(root,c);
 const closeMonth=root.querySelector('[data-pc-close-month]');if(closeMonth)closeMonth.onclick=async()=>{await saveAllocations(root,c,false);const {error}=await db().rpc('cerrar_coste_personal_v2',{p_coste_id:c.id});if(error)return showErr(root,error);await load();openCost(c.id);toast('Mes cerrado')};
 const reopen=root.querySelector('[data-pc-reopen]');if(reopen)reopen.onclick=async()=>{const {error}=await db().from('costes_personal_mensuales').update({estado:'revisado'}).eq('id',c.id);if(error)return showErr(root,error);await load();openCost(c.id);toast('Coste reabierto')};
}
function openCostBindings(root,c){root.querySelectorAll('[data-pci-amount]').forEach(x=>{if(x.dataset.bound)return;x.dataset.bound='1';x.oninput=()=>{const vals=[...root.querySelectorAll('[data-pci-amount]')].reduce((a,n)=>a+num(n.value),0);root.querySelector('[data-pc-assigned]').textContent=money(vals);root.querySelector('[data-pc-diff]').textContent=money(c.importe-vals)}});root.querySelectorAll('[data-pci-class]').forEach(x=>{if(x.dataset.bound)return;x.dataset.bound='1';x.onchange=()=>{const pr=x.closest('tr').querySelector('[data-pci-project]');pr.disabled=x.value!=='proyecto';if(x.value!=='proyecto')pr.value=''}});root.querySelectorAll('[data-pci-remove]').forEach(x=>x.onclick=()=>x.closest('tr').remove())}
function showErr(root,err){root.querySelector('#pc-detail-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`}
async function saveAllocations(root,c,notify=true){
 const rows=[...root.querySelectorAll('[data-pci]')].map(tr=>{const clasificacion=tr.querySelector('[data-pci-class]').value,proyecto_id=tr.querySelector('[data-pci-project]').value||null,importe=num(tr.querySelector('[data-pci-amount]').value),horas_base=num(tr.querySelector('[data-pci-hours]').value);return {coste_personal_id:c.id,clasificacion,proyecto_id:clasificacion==='proyecto'?proyecto_id:null,horas_base,porcentaje:c.importe?importe/c.importe*100:0,importe,metodo:'manual',ajuste_manual:true}});
 if(rows.some(x=>x.clasificacion==='proyecto'&&!x.proyecto_id))return showErr(root,new Error('Toda imputación de proyecto necesita un proyecto.'));
 const total=rows.reduce((a,x)=>a+x.importe,0);if(Math.abs(total-c.importe)>.01)return showErr(root,new Error(`El reparto debe sumar exactamente ${money(c.importe)}. Ahora suma ${money(total)}.`));
 const del=await db().from('costes_personal_imputaciones').delete().eq('coste_personal_id',c.id);if(del.error)return showErr(root,del.error);if(rows.length){const ins=await db().from('costes_personal_imputaciones').insert(rows);if(ins.error)return showErr(root,ins.error)}await db().from('costes_personal_mensuales').update({estado:'revisado'}).eq('id',c.id);await load();if(notify){openCost(c.id);toast('Reparto guardado')}return true
}
function renderHours(){
 if(window.APP?.route!=='horas'||!loaded)return;const view=$('#app-view');if(!view||view.querySelector('#personnel-costs-panel'))return;
 const months=[...new Set([...(D().horas||[]).map(x=>monthKey(x.fecha)),...(D().costesPersonal||[]).map(x=>monthKey(x.periodo))].filter(Boolean))].sort().reverse(),month=months[0]||currentMonth(),hrs=monthHours(month),costs=(D().costesPersonal||[]).filter(x=>monthKey(x.periodo)===month);
 const assignedMonth=costs.reduce((a,c)=>a+assigned(c.id),0),origin=costs.reduce((a,c)=>a+num(c.importe),0);
 view.insertAdjacentHTML('beforeend',`<section id="personnel-costs-panel" class="card panel" style="margin-top:14px"><div class="page-head" style="margin-bottom:10px"><div><h3 style="margin:0">Horas y costes mensuales de personal</h3><small style="color:var(--muted)">Revisión mensual, reparto automático por horas e imputación analítica a proyectos.</small></div><div class="grow"></div><button class="btn primary" data-pc-new>+ Coste mensual</button></div><div class="grid cols-4"><div class="info"><small>Mes revisado</small><b>${esc(month)}</b></div><div class="info"><small>Horas registradas</small><b>${hrs.reduce((a,x)=>a+x.horas,0).toLocaleString('es-ES',{maximumFractionDigits:2})} h</b></div><div class="info"><small>Costes mensuales origen</small><b>${money(origin)}</b></div><div class="info"><small>Importe imputado</small><b>${money(assignedMonth)}</b></div></div><div class="grid cols-2" style="margin-top:14px"><div><h3>Resumen mensual de horas</h3>${hrs.length?`<div class="table-wrap"><table class="table"><tr><th>Persona</th><th>Proyecto</th><th>Horas</th><th>Coste directo</th></tr>${hrs.map(x=>`<tr><td><b>${esc(x.persona)}</b></td><td>${esc(projectName(x.proyecto_id))}</td><td>${x.horas.toLocaleString('es-ES',{maximumFractionDigits:2})}</td><td>${money(x.coste)}</td></tr>`).join('')}</table></div>`:'<div class="empty">Sin horas en este mes.</div>'}</div><div><h3>Costes mensuales</h3>${costs.length?costs.map(c=>`<button class="master-item" style="width:100%;text-align:left;border:0" data-pc-open="${esc(c.id)}"><b>${esc(c.persona)} · ${esc(c.concepto)} · ${money(c.importe)}</b><small>${esc(c.tipo)} · imputado ${money(assigned(c.id))} · ${esc(c.estado)}</small></button>`).join(''):'<div class="empty">Todavía no hay costes mensuales registrados.</div>'}</div></div></section>`);
 view.querySelector('[data-pc-new]').onclick=openNew;view.querySelectorAll('[data-pc-open]').forEach(b=>b.onclick=()=>openCost(b.dataset.pcOpen));
}
function enhanceProject(){
 if(window.APP?.route!=='proyectos'||!loaded)return;const p=window.APP?.sel?.project,panel=$('#project-profitability-panel');if(!p||!panel||panel.querySelector('[data-personnel-project]'))return;const rows=(D().imputacionesPersonal||[]).filter(x=>x.clasificacion==='proyecto'&&String(x.proyecto_id)===String(p)),total=rows.reduce((a,x)=>a+num(x.importe),0),costMap=new Map((D().costesPersonal||[]).map(x=>[String(x.id),x]));const baseInv=(D().facturas||[]).filter(x=>String(x.proyecto_id)===String(p)&&!['borrador','anulada'].includes(String(x.estado||'').toLowerCase())).reduce((a,x)=>a+num(x.base),0),basePur=(D().compras||[]).filter(x=>String(x.proyecto_id)===String(p)&&String(x.estado||'').toLowerCase()!=='anulada').reduce((a,x)=>a+num(x.base),0),hourCost=(D().horas||[]).filter(x=>String(x.proyecto_id)===String(p)).reduce((a,x)=>a+num(x.horas)*num(x.coste_hora),0),over=(D().gastos||[]).filter(x=>String(x.proyecto_id||'')===String(p)).reduce((a,x)=>a+num(x.base),0),result=baseInv-basePur-hourCost-total-over;
 panel.insertAdjacentHTML('beforeend',`<div data-personnel-project class="card panel" style="margin-top:14px"><h3>Costes laborales imputados</h3><div class="grid cols-3"><div class="info"><small>Horas · coste directo</small><b>${money(hourCost)}</b></div><div class="info"><small>Costes mensuales repartidos</small><b>${money(total)}</b></div><div class="info"><small>Resultado analítico del proyecto</small><b class="${result<0?'negative':'positive'}">${money(result)}</b></div></div>${rows.length?`<div class="table-wrap" style="margin-top:10px"><table class="table"><tr><th>Mes</th><th>Persona</th><th>Concepto</th><th>Horas base</th><th>Importe</th></tr>${rows.map(r=>{const c=costMap.get(String(r.coste_personal_id));return `<tr data-pc-open="${esc(c?.id||'')}"><td>${esc(monthKey(c?.periodo))}</td><td>${esc(c?.persona||'')}</td><td>${esc(c?.concepto||'')}</td><td>${num(r.horas_base).toLocaleString('es-ES',{maximumFractionDigits:2})}</td><td><b>${money(r.importe)}</b></td></tr>`}).join('')}</table></div>`:'<div class="empty" style="margin-top:10px">Aún no hay costes mensuales repartidos a este proyecto.</div>'}</div>`);panel.querySelectorAll('[data-pc-open]').forEach(x=>x.onclick=()=>openCost(x.dataset.pcOpen))
}
function enhanceFinance(){
 if(window.APP?.route!=='informes'||!loaded)return;const root=$('#reports-v2');if(!root||root.querySelector('[data-personnel-finance]'))return;const alloc=D().imputacionesPersonal||[],costs=D().costesPersonal||[],project=alloc.filter(x=>x.clasificacion==='proyecto').reduce((a,x)=>a+num(x.importe),0),general=alloc.filter(x=>x.clasificacion==='general').reduce((a,x)=>a+num(x.importe),0),outside=alloc.filter(x=>x.clasificacion==='no_estudio').reduce((a,x)=>a+num(x.importe),0),origin=costs.reduce((a,x)=>a+num(x.importe),0),closed=costs.filter(x=>x.estado==='cerrado').length;
 root.insertAdjacentHTML('beforeend',`<section data-personnel-finance class="card panel" style="margin-top:14px"><h3>Costes de personal repartidos</h3><div class="grid cols-4"><div class="info"><small>Costes mensuales origen</small><b>${money(origin)}</b></div><div class="info"><small>Imputado a proyectos</small><b>${money(project)}</b></div><div class="info"><small>Estudio / general</small><b>${money(general)}</b></div><div class="info"><small>N · no estudio</small><b>${money(outside)}</b></div></div><p style="font-size:11px;color:var(--muted);margin:10px 0 0">${closed} coste${closed===1?'':'s'} mensual${closed===1?'':'es'} cerrado${closed===1?'':'s'}. El movimiento bancario se registra una sola vez; este bloque representa únicamente la imputación analítica.</p></section>`)
}
function schedule(){clearTimeout(timer);timer=setTimeout(async()=>{if(!loaded)await load();renderHours();enhanceProject();enhanceFinance()},80)}
window.iriarteOpenPersonnelCost=openCost;
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',schedule);window.addEventListener('hashchange',schedule);document.addEventListener('iriarte:route',schedule);
})();
