// Iriarte ERP V2 · CRUD de proyectos sobre public.proyectos
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const today=()=>new Date().toISOString().slice(0,10);
function options(arr,val){return '<option value="">—</option>'+(arr||[]).map(x=>`<option value="${x.id}" ${String(x.id)===String(val)?'selected':''}>${esc(x.nombre||'')}</option>`).join('')}
function statusOptions(current){const standard=[['activo','activo'],['en_obra','en obra'],['pausado','pausado'],['finalizado','finalizado']],known=standard.some(([v])=>v===current);return (!known&&current?`<option value="${esc(current)}" selected>${esc(current)} · histórico</option>`:'')+standard.map(([v,l])=>`<option value="${v}" ${current===v?'selected':''}>${l}</option>`).join('')}
function projectError(error){if(error?.code==='23505'&&/proyectos_codigo_unique|codigo/i.test(String(error.message||'')))return new Error('Ya existe otro proyecto con ese código. Usa un código distinto o abre el proyecto existente.');return error}
function open(pid){
 const S=window.APP,D=S?.data||{},x=(D.proyectos||[]).find(p=>String(p.id)===String(pid))||{};
 const linkedBudgets=pid?(D.presupuestos||[]).filter(p=>String(p.proyecto_id||'')===String(pid)):[],linkedInvoices=pid?(D.facturas||[]).filter(f=>String(f.proyecto_id||'')===String(pid)):[],clientLocked=!!pid&&(linkedBudgets.length>0||linkedInvoices.length>0);
 const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${pid?'Editar proyecto':'Nuevo proyecto'}</h2><div class="grow"></div><button type="button" class="btn" data-p-close>Cerrar</button></div><form id="p-form"><div class="modal-body"><div class="form-grid"><label class="full">Nombre<input name="nombre" required value="${esc(x.nombre||'')}"></label><label>Cliente<select ${clientLocked?'disabled':''} ${clientLocked?'':'name="cliente_id"'}>${options(D.clientes,x.cliente_id)}</select>${clientLocked?`<input type="hidden" name="cliente_id" value="${esc(x.cliente_id||'')}"><small style="display:block;color:var(--muted);margin-top:4px">Bloqueado por ${linkedBudgets.length} presupuesto${linkedBudgets.length===1?'':'s'} / ${linkedInvoices.length} factura${linkedInvoices.length===1?'':'s'} vinculada${linkedInvoices.length===1?'':'s'}.</small>`:''}</label><label>Código<input name="codigo" value="${esc(x.codigo||'')}"><small style="display:block;color:var(--muted);margin-top:4px">Si se informa, debe ser único.</small></label><label class="full">Dirección<input name="direccion" value="${esc(x.direccion||'')}"></label><label>Estado<select name="estado">${statusOptions(x.estado||'activo')}</select>${x.estado&&!['activo','en_obra','pausado','finalizado'].includes(x.estado)?'<small style="display:block;color:var(--muted);margin-top:4px">Estado histórico conservado. Solo cámbialo si quieres actualizar el ciclo operativo del proyecto.</small>':''}</label><label>Inicio<input name="fecha_inicio" type="date" value="${esc(x.fecha_inicio||today())}"></label><label>Fin<input name="fecha_fin" type="date" value="${esc(x.fecha_fin||'')}"></label><label>Expediente<input name="expediente" value="${esc(x.expediente||'')}"></label><label>Importe contratado<input name="importe_contratado" type="number" min="0" step="0.01" value="${num(x.importe_contratado)}"></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label></div>${clientLocked?'<div class="notice"><b>Cliente protegido.</b> Para conservar la trazabilidad contable, un proyecto con documentos financieros no puede cambiar de cliente mediante una edición normal. Los demás datos del proyecto sí se pueden modificar.</div>':''}<div id="p-error"></div></div><div class="modal-foot"><button type="button" class="btn" data-p-close>Cancelar</button><button type="submit" class="btn primary">Guardar</button></div></form></div></div>`;
 const close=()=>root.innerHTML='';root.querySelectorAll('[data-p-close]').forEach(b=>b.onclick=close);
 $('#p-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=Object.fromEntries(new FormData(e.currentTarget).entries());const amount=num(f.importe_contratado);if(amount<0)throw new Error('El importe contratado no puede ser negativo.');if(f.fecha_inicio&&f.fecha_fin&&f.fecha_fin<f.fecha_inicio)throw new Error('La fecha de fin no puede ser anterior a la fecha de inicio.');const payload={nombre:f.nombre,cliente_id:f.cliente_id||null,codigo:f.codigo||null,direccion:f.direccion||null,estado:f.estado||'activo',fecha_inicio:f.fecha_inicio||null,fecha_fin:f.fecha_fin||null,expediente:f.expediente||null,importe_contratado:amount,descripcion:f.descripcion||null};let projectId=pid;if(pid){const {error}=await db().from('proyectos').update(payload).eq('id',pid);if(error)throw projectError(error)}else{const {data,error}=await db().from('proyectos').insert(payload).select('id').single();if(error)throw projectError(error);projectId=data.id}close();if(window.APP)window.APP.sel.project=projectId;if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#p-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='new-project'){e.preventDefault();e.stopImmediatePropagation();open(null)}else if(b.dataset.action==='edit-project'){e.preventDefault();e.stopImmediatePropagation();open(window.APP?.sel?.project)}},true);
})();
