// Iriarte ERP V2 · ficha 360 de proyecto y rentabilidad integrada
(function(){
'use strict';
const $=s=>document.querySelector(s),money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(v||0));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(v||0)||0;
const issued=x=>!['borrador','anulada'].includes(String(x?.estado||'borrador').toLowerCase());
const activePurchase=x=>String(x?.estado||'').toLowerCase()!=='anulada';
const itemStyle='width:100%;text-align:left;border:0;background:transparent;color:inherit;font:inherit;cursor:pointer';
let timer;
function projectData(){
 const S=window.APP;if(!S?.data)return null;
 const p=(S.data.proyectos||[]).find(x=>String(x.id)===String(S.sel?.project));if(!p)return null;
 const match=(arr,key='proyecto_id')=>(arr||[]).filter(x=>String(x[key]??x.project_id??'')===String(p.id));
 const allInvoices=match(S.data.facturas),invoices=allInvoices.filter(issued),draftInvoices=allInvoices.filter(x=>String(x.estado||'borrador').toLowerCase()==='borrador');
 const allPurchases=match(S.data.compras),purchases=allPurchases.filter(activePurchase),hours=match(S.data.horas),visits=match(S.data.visitas),tasks=match(S.data.tareas),incidents=match(S.data.incidencias),docs=match(S.data.docs),budgets=(S.data.presupuestos||[]).filter(x=>String(x.proyecto_id||x.project_id||'')===String(p.id));
 const invoiceIds=new Set(invoices.map(x=>String(x.id))),purchaseIds=new Set(purchases.map(x=>String(x.id)));
 const collections=(S.data.cobros||[]).filter(x=>invoiceIds.has(String(x.factura_id))),payments=(S.data.pagos||[]).filter(x=>purchaseIds.has(String(x.compra_id)));
 const baseInv=invoices.reduce((a,x)=>a+num(x.base),0),totalInv=invoices.reduce((a,x)=>a+num(x.total),0),basePur=purchases.reduce((a,x)=>a+num(x.base),0),totalPur=purchases.reduce((a,x)=>a+num(x.total),0),hourCost=hours.reduce((a,x)=>a+num(x.horas)*num(x.coste_hora),0),collected=collections.reduce((a,x)=>a+num(x.importe),0),paid=payments.reduce((a,x)=>a+num(x.importe),0),overheads=(S.data.gastos||[]).filter(x=>String(x.proyecto_id||'')===String(p.id)),overheadBase=overheads.reduce((a,x)=>a+num(x.base),0);
 return {S,p,allInvoices,invoices,draftInvoices,allPurchases,purchases,hours,visits,tasks,incidents,docs,budgets,collections,payments,overheads,baseInv,totalInv,basePur,totalPur,hourCost,collected,paid,overheadBase,margin:baseInv-basePur-hourCost};
}
function route(name){if(window.iriarteRoute)window.iriarteRoute(name);else location.hash='#'+name}
function openRecord(type,id){if(window.iriarteOpenRecord)return window.iriarteOpenRecord(type,id);const r={project:'proyectos',invoice:'facturas',budget:'presupuestos',purchase:'compras',document:'documentos'}[type];if(!r)return;if(type==='project')window.APP.sel.project=id;else localStorage.setItem(`iriarte_open_${type}`,id);route(r)}
function openOperational(table,id){if(window.iriarteEditOperationalRecord)return window.iriarteEditOperationalRecord(table,id);window.APP.sel.project=window.APP?.sel?.project||'';route(table==='horas_proyecto'?'horas':'obra')}
function openExpense(id){if(window.iriarteEditExpense)return window.iriarteEditExpense(id);route('gastos')}
function record(type,id,title,small=''){return `<button type="button" class="master-item" style="${itemStyle}" data-project-record="${type}:${esc(id)}"><b>${title}</b>${small?`<small>${small}</small>`:''}</button>`}
function budgetTitle(x){return `${(x.kind||'obra')==='honorarios'?'Honorarios':'Obra'} · ${esc(x.name||x.nombre||'Presupuesto')}`}
function budgetState(x){return esc((x.kind||'obra')==='honorarios'?(x.estado||x.phase||x.status||''):(x.status||x.estado||x.phase||''))}
function operational(table,id,title,small=''){return `<button type="button" class="master-item" style="${itemStyle}" data-project-operational="${table}:${esc(id)}"><b>${title}</b>${small?`<small>${small}</small>`:''}</button>`}
function openBudget(d){
 if(!d.budgets.length){d.S.sel.project=d.p.id;route('presupuestos');return}
 if(d.budgets.length===1){openRecord('budget',d.budgets[0].id);return}
 const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(720px,94vw)"><div class="modal-head"><h2>Presupuestos · ${esc(d.p.nombre)}</h2><div class="grow"></div><button class="btn" data-ph-close>Cerrar</button></div><div class="modal-body">${d.budgets.map(x=>record('budget',x.id,budgetTitle(x),`${esc(x.ref||x.numero||'')} · ${budgetState(x)}`)).join('')}</div></div></div>`;root.querySelector('[data-ph-close]').onclick=()=>root.innerHTML=''
}
function metric(label,value,cls=''){return `<div class="info"><small>${esc(label)}</small><b class="${cls}">${esc(value)}</b></div>`}
function profitabilityHtml(d){
 const pendingCollect=Math.max(0,d.totalInv-d.collected),pendingPay=Math.max(0,d.totalPur-d.paid),result=d.margin-d.overheadBase,pct=d.baseInv?d.margin/d.baseInv*100:0;
 return `<section id="project-profitability-panel" class="card panel" style="margin-top:14px"><div class="page-head" style="margin-bottom:8px"><div><h3 style="margin:0">Rentabilidad del proyecto</h3><small style="color:var(--muted)">Ingresos emitidos, costes directos, gastos vinculados y tesorería del proyecto.</small></div></div><div class="grid cols-4">${metric('Facturado base',money(d.baseInv))}${metric('Facturado total',money(d.totalInv))}${metric('Compras base',money(d.basePur))}${metric('Coste de horas',money(d.hourCost))}${metric('Margen directo',money(d.margin),d.margin>=0?'positive':'negative')}${metric('Margen directo %',pct.toLocaleString('es-ES',{maximumFractionDigits:1})+'%',d.margin>=0?'positive':'negative')}${metric('Gastos vinculados',money(d.overheadBase))}${metric('Resultado tras vinculados',money(result),result>=0?'positive':'negative')}${metric('Cobrado',money(d.collected))}${metric('Pendiente de cobro',money(pendingCollect),pendingCollect>0?'negative':'positive')}${metric('Pagado a proveedores',money(d.paid))}${metric('Pendiente de pago',money(pendingPay),pendingPay>0?'negative':'positive')}</div>${d.draftInvoices.length?`<div class="notice" style="margin-top:12px"><b>${d.draftInvoices.length} factura${d.draftInvoices.length===1?'':'s'} en borrador.</b> No cuentan como facturación ni pendiente de cobro hasta su emisión.</div>`:''}<div class="grid cols-3" style="margin-top:14px"><div class="card panel"><h3>Facturas emitidas · ${d.invoices.length}</h3>${d.invoices.length?d.invoices.map(x=>record('invoice',x.id,`${esc(x.numero||'Factura')} · ${money(x.total)}`,`${esc(x.fecha||'')} · ${esc(x.estado||'')}`)).join(''):'<div class="empty">Sin facturas emitidas.</div>'}</div><div class="card panel"><h3>Costes directos · ${d.purchases.length}</h3>${d.purchases.length?d.purchases.map(x=>record('purchase',x.id,`${esc(x.numero_factura||x.concepto||'Compra')} · ${money(x.total)}`,esc(x.fecha||''))).join(''):'<div class="empty">Sin compras.</div>'}</div><div class="card panel"><h3>Gastos vinculados · ${d.overheads.length}</h3>${d.overheads.length?d.overheads.map(x=>`<button type="button" class="master-item" style="${itemStyle}" data-project-expense="${esc(x.id)}"><b>${esc(x.concepto||x.categoria||'Gasto')} · ${money(x.total??x.base)}</b><small>${esc(x.fecha||'')} · ${esc(x.categoria||'')}</small></button>`).join(''):'<div class="empty">Sin gastos vinculados.</div>'}</div></div></section>`
}
function replacePanel(panel,html,emptyText){const h=panel.querySelector('h3');if(!h)return;panel.querySelectorAll(':scope > :not(h3)').forEach(x=>x.remove());if(!html){const e=document.createElement('div');e.className='empty';e.textContent=emptyText||'No hay datos todavía.';panel.appendChild(e);return}const wrap=document.createElement('div');wrap.innerHTML=html;while(wrap.firstChild)panel.appendChild(wrap.firstChild)}
function setKpi(detail,label,value,cls=''){for(const k of detail.querySelectorAll('.kpi')){const small=k.querySelector('small');if(small?.textContent.trim()!==label)continue;const strong=k.querySelector('strong');if(!strong)continue;strong.textContent=value;strong.classList.remove('positive','negative');if(cls)strong.classList.add(cls);break}}
function decorate(){
 clearTimeout(timer);timer=setTimeout(()=>{
  if(window.APP?.route!=='proyectos')return;
  const d=projectData(),detail=$('.card.detail');if(!d||!detail)return;
  const signature=[d.p.id,d.budgets.length,d.allInvoices.length,d.allPurchases.length,d.hours.length,d.visits.length,d.tasks.length,d.incidents.length,d.docs.length,d.baseInv,d.basePur,d.hourCost,d.margin,d.overheadBase,d.collected,d.paid].join(':');if(detail.dataset.projectEnhancement===signature)return;detail.dataset.projectEnhancement=signature;
  setKpi(detail,'Facturado base',money(d.baseInv));setKpi(detail,'Compras base',money(d.basePur));setKpi(detail,'Coste horas',money(d.hourCost));setKpi(detail,'Margen directo',money(d.margin),d.margin<0?'negative':'positive');
  detail.querySelectorAll('.card.panel').forEach(panel=>{const title=panel.querySelector('h3')?.textContent.trim();if(title==='Presupuestos')replacePanel(panel,d.budgets.map(x=>record('budget',x.id,budgetTitle(x),`${esc(x.ref||x.numero||'')} · ${budgetState(x)}`)).join(''),'Sin presupuestos vinculados.');else if(title==='Facturas')replacePanel(panel,d.allInvoices.map(x=>record('invoice',x.id,esc(x.numero||'Borrador'),`${esc(x.fecha||'')} · ${money(x.total)} · ${esc(x.estado||'')}`)).join(''),'Sin facturas.');else if(title==='Compras')replacePanel(panel,d.allPurchases.map(x=>record('purchase',x.id,esc(x.numero_factura||x.concepto||'Compra'),`${esc(x.fecha||'')} · ${money(x.total)} · ${esc(x.estado||'')}`)).join(''),'Sin compras.');else if(title==='Horas')replacePanel(panel,d.hours.map(x=>operational('horas_proyecto',x.id,`${esc(x.persona||'Horas')} · ${num(x.horas).toLocaleString('es-ES',{maximumFractionDigits:2})} h`,`${esc(x.fecha||'')} · ${money(num(x.horas)*num(x.coste_hora))}`)).join(''),'Sin horas.');else if(title==='Obra'){const html=[...d.visits.map(x=>operational('obra_visitas',x.id,`Visita · ${esc(x.titulo||'Registro')}`,esc(x.fecha||''))),...d.tasks.map(x=>operational('obra_tareas',x.id,`Tarea · ${esc(x.titulo||'Registro')}`,`${esc(x.estado||'')} · ${esc(x.prioridad||'')}`)),...d.incidents.map(x=>operational('obra_incidencias',x.id,`Incidencia · ${esc(x.titulo||'Registro')}`,`${esc(x.estado||'')} · ${esc(x.prioridad||'')}`))].join('');replacePanel(panel,html,'Sin registros de obra.')}else if(title==='Documentos')replacePanel(panel,d.docs.map(x=>record('document',x.id,esc(x.nombre||x.archivo_nombre||'Documento'),`${esc(x.tipo||'')} · ${esc((x.fecha_documento||x.created_at||'').slice(0,10))}`)).join(''),'Sin documentos.');});
  const old=detail.querySelector('#project-profitability-panel');if(old)old.remove();const baseGrid=detail.querySelector('.grid.cols-4');if(baseGrid)baseGrid.insertAdjacentHTML('afterend',profitabilityHtml(d));
  const flow=detail.querySelector('.flow');if(flow){const budget=flow.querySelector('[data-project-nav="presupuestos"]');if(budget)budget.textContent=d.budgets.length===1?'Presupuesto':'Presupuestos';const profit=flow.querySelector('[data-project-nav="finanzas"]');if(profit){profit.textContent='Rentabilidad';profit.title='Ir al panel de rentabilidad del proyecto'}}
 },70)
}
new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',decorate);window.addEventListener('load',decorate);
document.addEventListener('click',e=>{
 const rec=e.target.closest('[data-project-record]');if(rec){e.preventDefault();e.stopImmediatePropagation();const [type,id]=rec.dataset.projectRecord.split(':');openRecord(type,id);return}
 const op=e.target.closest('[data-project-operational]');if(op){e.preventDefault();e.stopImmediatePropagation();const [table,id]=op.dataset.projectOperational.split(':');openOperational(table,id);return}
 const exp=e.target.closest('[data-project-expense]');if(exp){e.preventDefault();e.stopImmediatePropagation();openExpense(exp.dataset.projectExpense);return}
 const nav=e.target.closest('[data-project-nav]');if(!nav||window.APP?.route!=='proyectos')return;const d=projectData();if(!d)return;
 if(nav.dataset.projectNav==='clientes'){e.preventDefault();e.stopImmediatePropagation();window.iriarteOpenClientHub?.(d.p.cliente_id)}
 else if(nav.dataset.projectNav==='presupuestos'){e.preventDefault();e.stopImmediatePropagation();openBudget(d)}
 else if(nav.dataset.projectNav==='finanzas'){e.preventDefault();e.stopImmediatePropagation();document.querySelector('#project-profitability-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}
},true);
})();
