// Iriarte ERP V2 · CRUD de proyectos sobre public.proyectos
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const today=()=>new Date().toISOString().slice(0,10);
function options(arr,val){return '<option value="">—</option>'+(arr||[]).map(x=>`<option value="${x.id}" ${String(x.id)===String(val)?'selected':''}>${esc(x.nombre||'')}</option>`).join('')}
function open(pid){const S=window.APP,D=S?.data||{},x=(D.proyectos||[]).find(p=>String(p.id)===String(pid))||{};const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${pid?'Editar proyecto':'Nuevo proyecto'}</h2><div class="grow"></div><button type="button" class="btn" data-p-close>Cerrar</button></div><form id="p-form"><div class="modal-body"><div class="form-grid"><label class="full">Nombre<input name="nombre" required value="${esc(x.nombre||'')}"></label><label>Cliente<select name="cliente_id">${options(D.clientes,x.cliente_id)}</select></label><label>Código<input name="codigo" value="${esc(x.codigo||'')}"></label><label class="full">Dirección<input name="direccion" value="${esc(x.direccion||'')}"></label><label>Estado<select name="estado"><option value="activo" ${x.estado==='activo'?'selected':''}>activo</option><option value="en_obra" ${x.estado==='en_obra'?'selected':''}>en obra</option><option value="pausado" ${x.estado==='pausado'?'selected':''}>pausado</option><option value="finalizado" ${x.estado==='finalizado'?'selected':''}>finalizado</option></select></label><label>Inicio<input name="fecha_inicio" type="date" value="${esc(x.fecha_inicio||today())}"></label><label>Fin<input name="fecha_fin" type="date" value="${esc(x.fecha_fin||'')}"></label><label>Expediente<input name="expediente" value="${esc(x.expediente||'')}"></label><label>Importe contratado<input name="importe_contratado" type="number" step="0.01" value="${num(x.importe_contratado)}"></label><label class="full">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label></div><div id="p-error"></div></div><div class="modal-foot"><button type="button" class="btn" data-p-close>Cancelar</button><button type="submit" class="btn primary">Guardar</button></div></form></div></div>`;const close=()=>root.innerHTML='';root.querySelectorAll('[data-p-close]').forEach(b=>b.onclick=close);$('#p-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=Object.fromEntries(new FormData(e.currentTarget).entries());const payload={nombre:f.nombre,cliente_id:f.cliente_id||null,codigo:f.codigo||null,direccion:f.direccion||null,estado:f.estado||'activo',fecha_inicio:f.fecha_inicio||null,fecha_fin:f.fecha_fin||null,expediente:f.expediente||null,importe_contratado:num(f.importe_contratado),descripcion:f.descripcion||null};let projectId=pid;if(pid){const {error}=await db().from('proyectos').update(payload).eq('id',pid);if(error)throw error}else{const {data,error}=await db().from('proyectos').insert(payload).select('id').single();if(error)throw error;projectId=data.id}close();if(window.APP)window.APP.sel.project=projectId;if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#p-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='new-project'){e.preventDefault();e.stopImmediatePropagation();open(null)}else if(b.dataset.action==='edit-project'){e.preventDefault();e.stopImmediatePropagation();open(window.APP?.sel?.project)}},true);
})();
