// Iriarte ERP V2 · compras editables y control de pagos
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
let timer;
function pName(id){return (window.APP?.data?.proyectos||[]).find(x=>String(x.id)===String(id))?.nombre||'—'}
function sName(id){return (window.APP?.data?.proveedores||[]).find(x=>String(x.id)===String(id))?.nombre||'—'}
function paid(id){return (window.APP?.data?.pagos||[]).filter(x=>String(x.compra_id)===String(id)).reduce((a,x)=>a+num(x.importe),0)}
function opts(arr,val,label){return '<option value="">—</option>'+(arr||[]).map(x=>`<option value="${x.id}" ${String(x.id)===String(val)?'selected':''}>${esc(label(x))}</option>`).join('')}
function modal(x){const D=window.APP?.data||{},root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>Editar compra</h2><div class="grow"></div><button class="btn" type="button" data-c-close>Cerrar</button></div><form id="c-form"><div class="modal-body"><div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${esc(x.fecha||'')}"></label><label>Nº factura<input name="numero_factura" value="${esc(x.numero_factura||'')}"></label><label>Proveedor<select name="proveedor_id">${opts(D.proveedores,x.proveedor_id,p=>p.nombre)}</select></label><label>Proyecto<select name="proyecto_id">${opts(D.proyectos,x.proyecto_id,p=>p.nombre)}</select></label><label class="full">Concepto<input name="concepto" value="${esc(x.concepto||'')}" required></label><label>Base<input name="base" type="number" step="0.01" value="${num(x.base)}"></label><label>IVA %<input name="iva_pct" type="number" step="0.01" value="${num(x.iva_pct||21)}"></label><label>Estado<select name="estado"><option value="pendiente" ${x.estado==='pendiente'?'selected':''}>pendiente</option><option value="parcialmente_pagada" ${x.estado==='parcialmente_pagada'?'selected':''}>parcialmente pagada</option><option value="pagada" ${x.estado==='pagada'?'selected':''}>pagada</option><option value="anulada" ${x.estado==='anulada'?'selected':''}>anulada</option></select></label><label>Vencimiento<input name="fecha_vencimiento" type="date" value="${esc(x.fecha_vencimiento||'')}"></label><label class="full">Notas<textarea name="notas">${esc(x.notas||'')}</textarea></label></div><div id="c-error"></div></div><div class="modal-foot"><button type="button" class="btn" data-c-close>Cancelar</button><button type="submit" class="btn primary">Guardar</button></div></form></div></div>`;const close=()=>root.innerHTML='';root.querySelectorAll('[data-c-close]').forEach(b=>b.onclick=close);$('#c-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const f=Object.fromEntries(new FormData(e.currentTarget).entries()),base=num(f.base),pct=num(f.iva_pct),iva=base*pct/100;const {error}=await db().from('compras').update({fecha:f.fecha,numero_factura:f.numero_factura||null,proveedor_id:f.proveedor_id||null,proyecto_id:f.proyecto_id||null,concepto:f.concepto,base,iva_pct:pct,iva_importe:iva,total:base+iva,estado:f.estado,fecha_vencimiento:f.fecha_vencimiento||null,notas:f.notas||null}).eq('id',x.id);if(error)throw error;close();if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#c-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}}
async function remove(id){if(!confirm('¿Eliminar esta compra? También se eliminarán sus pagos vinculados.'))return;const {error}=await db().from('compras').delete().eq('id',id);if(error)return alert(error.message);if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}
function render(){if(window.APP?.route!=='compras')return;if($('#purchases-v2'))return;const D=window.APP.data,pid=window.APP.sel.project||'',rows=(D.compras||[]).filter(x=>!pid||String(x.proyecto_id)===String(pid));const view=$('#app-view');if(!view)return;view.innerHTML=`<div id="purchases-v2"><div class="page-head"><h1>Compras y pagos</h1><div class="grow"></div><div class="toolbar"><select class="btn" data-p-filter><option value="">Todos los proyectos</option>${(D.proyectos||[]).map(p=>`<option value="${p.id}" ${String(pid)===String(p.id)?'selected':''}>${esc(p.nombre)}</option>`).join('')}</select><button class="btn primary" data-action="new-purchase">+ Nueva compra</button></div></div>${rows.length?`<div class="card panel table-wrap"><table class="table"><tr><th>Fecha</th><th>Proveedor</th><th>Proyecto</th><th>Factura</th><th>Concepto</th><th>Base</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th>Estado</th><th></th></tr>${rows.map(x=>{const p=paid(x.id),pend=Math.max(0,num(x.total)-p);return `<tr><td>${esc(x.fecha||'')}</td><td>${esc(sName(x.proveedor_id))}</td><td>${esc(pName(x.proyecto_id))}</td><td>${esc(x.numero_factura||'')}</td><td><b>${esc(x.concepto||'')}</b></td><td>${money(x.base)}</td><td>${money(x.total)}</td><td>${money(p)}</td><td><b>${money(pend)}</b></td><td><span class="badge ${x.estado==='pagada'?'good':x.estado==='anulada'?'bad':'warn'}">${esc(x.estado||'')}</span></td><td><div class="toolbar"><button class="btn" data-p-edit="${x.id}">Editar</button><button class="btn danger" data-p-delete="${x.id}">Eliminar</button></div></td></tr>`}).join('')}</table></div>`:'<div class="empty">No hay compras para este filtro.</div>'}</div>`;view.querySelector('[data-p-filter]').onchange=e=>{window.APP.sel.project=e.target.value;view.innerHTML='';render()};view.querySelectorAll('[data-p-edit]').forEach(b=>b.onclick=()=>modal(rows.find(x=>String(x.id)===String(b.dataset.pEdit))));view.querySelectorAll('[data-p-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.pDelete))}
function schedule(){clearTimeout(timer);timer=setTimeout(render,70)}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',schedule);window.addEventListener('load',schedule);
})();
