// Iriarte ERP V2 · Registros V4: libro mayor operativo transversal, rico y no duplicado
(function(){
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
let timer;
function D(){return window.APP?.data||{}}
function byId(arr,id){return (arr||[]).find(x=>String(x.id)===String(id))||null}
function client(id){return byId(D().clientes,id)}
function supplier(id){return byId(D().proveedores,id)}
function project(id){return byId(D().proyectos,id)}
function dateOf(x){return x.fecha||x.date||x.fecha_documento||x.fecha_limite||x.periodo||String(x.created_at||x.updated_at||'').slice(0,10)}
function primitive(v){if(v==null)return'';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function collections(id){return (D().cobros||[]).filter(x=>String(x.factura_id)===String(id)).reduce((a,x)=>a+num(x.importe),0)}
function payments(id){return (D().pagos||[]).filter(x=>String(x.compra_id)===String(id)).reduce((a,x)=>a+num(x.importe),0)}
function signedBank(x){const n=Math.abs(num(x.total));return ['pago','gasto'].includes(String(x.tipo||'').toLowerCase())?-n:n}
function budgetIrpf(x){return x.irpf_enabled?num(x.base)*num(x.irpf_pct||15)/100:0}
function baseRow(type,x,extra={}){const projectId=extra.projectId??x.proyecto_id??x.project_id??null,p=project(projectId),clientId=extra.clientId??x.cliente_id??null,supplierId=extra.supplierId??x.proveedor_id??null;return {type,id:x.id,raw:x,date:extra.date??dateOf(x),period:extra.period??String(extra.date??dateOf(x)).slice(0,7),ref:extra.ref??x.numero??x.ref??x.codigo??x.numero_factura??x.referencia??'',party:extra.party??(client(clientId)?.nombre||supplier(supplierId)?.nombre||''),person:extra.person??'',projectId,projectCode:extra.projectCode??p?.codigo??'',projectName:extra.projectName??p?.nombre??'',concept:extra.concept??x.concepto??x.nombre??x.name??x.titulo??x.descripcion??'',classification:extra.classification??x.categoria??x.tipo??'',account:extra.account??x.cuenta??'',hours:extra.hours??'',base:extra.base??'',iva:extra.iva??'',irpf:extra.irpf??'',total:extra.total??x.total??x.importe??'',pending:extra.pending??'',status:extra.status??x.estado??x.status??x.phase??'',origin:extra.origin??type,open:extra.open||null}}
function rows(){
 const d=D(),out=[];
 (d.clientes||[]).forEach(x=>out.push(baseRow('Cliente',x,{party:x.nombre,concept:x.email||x.contacto||'',status:x.activo===false?'inactivo':'activo',open:['client',x.id]})));
 (d.proveedores||[]).forEach(x=>out.push(baseRow('Proveedor',x,{party:x.nombre,concept:x.tipo||x.email||'',status:x.activo===false?'inactivo':'activo',open:['supplier',x.id]})));
 (d.proyectos||[]).forEach(x=>out.push(baseRow('Proyecto',x,{ref:x.codigo,party:client(x.cliente_id)?.nombre||'',projectId:x.id,concept:x.direccion||x.descripcion||'',open:['project',x.id]})));
 (d.presupuestos||[]).forEach(x=>{const irpf=budgetIrpf(x),base=num(x.base),total=num(x.total),iva=Math.max(0,total-base+irpf);out.push(baseRow('Presupuesto',x,{party:client(x.cliente_id)?.nombre||x.client||'',concept:x.name||x.nombre||'',classification:x.kind==='honorarios'?'honorarios':'obra',base,iva,irpf,total,open:['budget',x.id]}))});
 (d.facturas||[]).forEach(x=>{const paid=collections(x.id);out.push(baseRow('Factura',x,{party:client(x.cliente_id)?.nombre||'',base:x.base,iva:x.iva_importe,irpf:x.irpf_importe,total:x.total,pending:Math.max(0,num(x.total)-paid),classification:'venta',open:['invoice',x.id]}))});
 (d.compras||[]).forEach(x=>{const paid=payments(x.id);out.push(baseRow('Compra',x,{party:supplier(x.proveedor_id)?.nombre||'',base:x.base,iva:x.iva_importe,total:x.total,pending:Math.max(0,num(x.total)-paid),classification:'proveedor',open:['purchase',x.id]}))});
 (d.cobros||[]).forEach(x=>{const f=byId(d.facturas,x.factura_id);out.push(baseRow('Cobro',x,{ref:f?.numero||'',clientId:f?.cliente_id,projectId:f?.proyecto_id,party:client(f?.cliente_id)?.nombre||'',concept:x.referencia||'Cobro de factura',classification:'cobro',total:x.importe,pending:'',open:['collection',x.id]}))});
 (d.pagos||[]).forEach(x=>{const c=byId(d.compras,x.compra_id);out.push(baseRow('Pago',x,{ref:c?.numero_factura||c?.referencia||'',supplierId:c?.proveedor_id,projectId:c?.proyecto_id,party:supplier(c?.proveedor_id)?.nombre||'',concept:x.referencia||'Pago de compra',classification:'pago',total:x.importe,pending:'',open:['payment',x.id]}))});
 (d.horas||[]).forEach(x=>out.push(baseRow('Horas',x,{party:x.persona||'',person:x.persona||'',concept:x.concepto||x.notas||'',classification:'personal directo',hours:x.horas,total:num(x.horas)*num(x.coste_hora),open:['operational','horas_proyecto:'+x.id]})));
 (d.visitas||[]).forEach(x=>out.push(baseRow('Visita',x,{projectId:x.project_id,concept:x.titulo||x.descripcion||'',classification:'obra',status:x.estado_obra||'',open:['operational','obra_visitas:'+x.id]})));
 (d.tareas||[]).forEach(x=>out.push(baseRow('Tarea',x,{date:x.fecha_limite||dateOf(x),projectId:x.project_id,concept:x.titulo||x.descripcion||'',classification:'obra',open:['operational','obra_tareas:'+x.id]})));
 (d.incidencias||[]).forEach(x=>out.push(baseRow('Incidencia',x,{projectId:x.project_id,party:supplier(x.proveedor_id)?.nombre||'',concept:x.titulo||x.descripcion||'',classification:x.tipo||'incidencia',open:['operational','obra_incidencias:'+x.id]})));
 (d.docs||[]).forEach(x=>out.push(baseRow('Documento',x,{projectId:x.proyecto_id,party:client(x.cliente_id)?.nombre||supplier(x.proveedor_id)?.nombre||'',concept:x.nombre||x.archivo_nombre||'',classification:x.tipo||'documento',open:['document',x.id]})));
 (d.gastos||[]).forEach(x=>out.push(baseRow('Gasto general',x,{party:supplier(x.proveedor_id)?.nombre||x.proveedor||'',classification:x.categoria||'general',base:x.base,iva:x.iva_importe,total:x.total,open:['expense',x.id]})));
 (d.movs||[]).forEach(x=>out.push(baseRow('Banco',x,{party:x.cliente_proveedor||client(x.cliente_id)?.nombre||supplier(x.proveedor_id)?.nombre||'',concept:x.concepto||x.concepto_banco||'',classification:[x.categoria,x.subcategoria].filter(Boolean).join(' · '),account:x.cuenta||'',total:signedBank(x),status:x.conciliado?'revisado':'pendiente',open:[x.conciliado?'detail':'bank',x.id]})));
 const costMap=new Map((d.costesPersonal||[]).map(x=>[String(x.id),x]));
 (d.costesPersonal||[]).forEach(x=>out.push(baseRow('Coste personal',x,{date:x.periodo,period:String(x.periodo||'').slice(0,7),party:x.persona,person:x.persona,concept:x.concepto,classification:x.tipo,total:x.importe,status:x.estado,origin:'coste mensual',open:['personnel-cost',x.id]})));
 (d.imputacionesPersonal||[]).forEach(x=>{const c=costMap.get(String(x.coste_personal_id)),dest=x.clasificacion==='proyecto'?project(x.proyecto_id)?.nombre||'':x.clasificacion==='no_estudio'?'N · No estudio':'Estudio / general';out.push(baseRow('Imputación personal',x,{date:c?.periodo||dateOf(x),period:String(c?.periodo||'').slice(0,7),party:c?.persona||'',person:c?.persona||'',projectId:x.clasificacion==='proyecto'?x.proyecto_id:null,projectName:dest,concept:c?.concepto||'Coste personal',classification:x.clasificacion+(x.ajuste_manual?' · manual':' · automático'),hours:x.horas_base,total:x.importe,status:c?.estado||'',origin:'reparto analítico',open:['personnel-cost',x.coste_personal_id]}))});
 return out.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))
}
const C={type:{label:'Tipo',get:r=>r.type},date:{label:'Fecha / periodo',get:r=>r.date},ref:{label:'Referencia',get:r=>r.ref},party:{label:'Cliente / proveedor / persona',get:r=>r.party},person:{label:'Persona',get:r=>r.person},projectCode:{label:'Nº proyecto',get:r=>r.projectCode},projectName:{label:'Proyecto / destino',get:r=>r.projectName},concept:{label:'Concepto',get:r=>r.concept},classification:{label:'Clasificación',get:r=>r.classification},account:{label:'Banco / cuenta',get:r=>r.account},hours:{label:'Horas',get:r=>r.hours,kind:'number'},base:{label:'Base',get:r=>r.base,kind:'money'},iva:{label:'IVA',get:r=>r.iva,kind:'money'},irpf:{label:'IRPF',get:r=>r.irpf,kind:'money'},total:{label:'Total / importe',get:r=>r.total,kind:'money'},pending:{label:'Pendiente',get:r=>r.pending,kind:'money'},status:{label:'Estado',get:r=>r.status},origin:{label:'Origen',get:r=>r.origin}};
const PRESETS={todo:['type','date','ref','party','projectCode','projectName','concept','classification','hours','base','iva','irpf','total','pending','status'],banco:['date','account','concept','classification','projectCode','projectName','party','total','status'],costes:['date','type','party','person','projectCode','projectName','concept','classification','hours','base','total','status'],personal:['date','type','person','projectCode','projectName','hours','classification','total','status'],ventas:['date','type','ref','party','projectCode','projectName','base','iva','irpf','total','pending','status'],compras:['date','type','ref','party','projectCode','projectName','base','iva','total','pending','status']};
const PRESET_TYPES={banco:['Banco'],costes:['Compra','Pago','Horas','Gasto general','Coste personal','Imputación personal','Banco'],personal:['Horas','Coste personal','Imputación personal'],ventas:['Presupuesto','Factura','Cobro'],compras:['Compra','Pago','Proveedor']};
function rawKeys(list){const s=new Set();list.forEach(r=>Object.keys(r.raw||{}).forEach(k=>s.add(k)));return [...s].sort((a,b)=>a.localeCompare(b,'es'))}
function pretty(k){const m={id:'ID',created_at:'Creado',updated_at:'Actualizado',created_by:'Creado por',cliente_id:'Cliente ID',proveedor_id:'Proveedor ID',proyecto_id:'Proyecto ID',project_id:'Proyecto ID',coste_personal_id:'Coste personal ID'};return m[k]||k.replaceAll('_',' ').replace(/^./,x=>x.toUpperCase())}
function columns(preset,type,list){const base=(PRESETS[preset]||PRESETS.todo).map(k=>({key:k,...C[k]}));if(!type)return base;const existing=new Set(base.map(x=>x.key));return [...base,...rawKeys(list).filter(k=>!existing.has(k)).map(k=>({key:'raw:'+k,label:pretty(k),get:r=>r.raw?.[k]}))]}
function val(r,c){return primitive(c.get(r))}
function display(r,c){const v=c.get(r);if(v==null||v==='')return'';if(c.kind==='money')return money(v);if(c.kind==='number')return num(v).toLocaleString('es-ES',{maximumFractionDigits:2});const s=primitive(v);return esc(s.length>150?s.slice(0,147)+'…':s)}
function searchText(r){return Object.values(r).filter(v=>typeof v!=='object').join(' ').toLowerCase()+' '+JSON.stringify(r.raw||{}).toLowerCase()}
function open(r){if(!r.open)return detail(r);const [type,id]=r.open;if(type==='client')return window.iriarteOpenClientHub?.(id);if(type==='supplier')return window.iriarteOpenSupplierHub?.(id);if(type==='operational'){const [table,rid]=String(id).split(':');return window.iriarteEditOperationalRecord?.(table,rid)}if(type==='expense')return window.iriarteEditExpense?.(id);if(type==='collection')return window.iriarteEditCollection?.(id);if(type==='payment')return window.iriarteEditPayment?.(id);if(type==='bank')return window.iriarteReconcileMovement?.(id);if(type==='personnel-cost')return window.iriarteOpenPersonnelCost?.(id);if(type==='detail')return detail(r);return window.iriarteOpenRecord?.(type,id)}
function detail(r){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(950px,96vw)"><div class="modal-head"><h2>${esc(r.type)} · ${esc(r.ref||r.concept||r.id)}</h2><div class="grow"></div><button class="btn" data-r4-close>Cerrar</button></div><div class="modal-body"><div class="notice">Este registro procede de <b>${esc(r.origin)}</b>. Los campos derivados se calculan automáticamente; para modificar el dato original usa su ficha.</div><div class="grid cols-2">${Object.entries(r.raw||{}).map(([k,v])=>`<div class="info"><small>${esc(pretty(k))}</small><b style="overflow-wrap:anywhere;white-space:pre-wrap">${esc(primitive(v)||'—')}</b></div>`).join('')}</div></div></div></div>`;root.querySelector('[data-r4-close]').onclick=()=>root.innerHTML=''}
function styles(){if($('#records-v4-style'))return;const s=document.createElement('style');s.id='records-v4-style';s.textContent=`.r4-presets{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.r4-presets button{border:1px solid var(--line);background:#fff;border-radius:999px;padding:7px 11px;cursor:pointer}.r4-presets button.active{background:#e8ece2;border-color:#9aaa94;color:#2d4527;font-weight:700}.r4-tools{display:grid;grid-template-columns:minmax(230px,1.3fr) minmax(160px,.7fr) minmax(160px,.7fr) minmax(150px,.6fr);gap:8px;margin-bottom:10px}.r4-tools input,.r4-tools select,.r4-filter{width:100%;border:1px solid var(--line);border-radius:7px;padding:8px;background:#fff}.r4-table{min-width:max-content}.r4-table th{position:sticky;top:0;background:#fff;z-index:1;white-space:nowrap}.r4-table td{max-width:310px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.r4-row{cursor:pointer}.r4-row:hover{background:#edf0e8}.r4-filters th{padding:4px;top:33px}.r4-filters input{font-size:10px;padding:5px;min-width:100px}.r4-meta{display:flex;gap:15px;flex-wrap:wrap;color:var(--muted);font-size:11px;margin:8px 0 12px}@media(max-width:950px){.r4-tools{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
function render(){const view=$('#app-view'),S=window.APP;if(!view||!S||S.route!=='registros')return;styles();const all=rows(),types=[...new Set(all.map(x=>x.type))].sort((a,b)=>a.localeCompare(b,'es')),projects=D().proyectos||[],state={preset:localStorage.getItem('iriarte_records_preset')||'todo',type:'',project:'',month:'',global:'',filters:{}};view.innerHTML=`<div id="records-v4"><div class="page-head"><div><h1>Registros</h1><p style="color:var(--muted);margin:4px 0 0">Libro mayor operativo: la información se rellena desde sus módulos originales y aquí se cruza, filtra y abre sin duplicarla.</p></div></div><div class="r4-presets">${[['todo','Todo'],['banco','Banco'],['costes','Costes de proyecto'],['personal','Personal'],['ventas','Ventas'],['compras','Compras']].map(([k,l])=>`<button data-r4-preset="${k}" class="${state.preset===k?'active':''}">${l}</button>`).join('')}</div><div class="r4-tools"><input data-r4-global placeholder="Buscar cualquier dato…"><select data-r4-type><option value="">Todos los tipos</option>${types.map(t=>`<option>${esc(t)}</option>`).join('')}</select><select data-r4-project><option value="">Todos los proyectos</option>${projects.map(p=>`<option value="${esc(p.id)}">${esc(p.codigo||'')} · ${esc(p.nombre)}</option>`).join('')}</select><input data-r4-month type="month"></div><div class="r4-meta"><span><b data-r4-count>${all.length}</b> registros visibles</span><span>Selecciona una fila para abrir/editar el registro original</span><span data-r4-note></span></div><div class="card panel table-wrap"><table class="table r4-table"><thead data-r4-head></thead><tbody data-r4-body></tbody></table></div></div>`;
 const typeSel=$('[data-r4-type]'),projectSel=$('[data-r4-project]'),month=$('[data-r4-month]'),global=$('[data-r4-global]'),head=$('[data-r4-head]'),body=$('[data-r4-body]'),count=$('[data-r4-count]'),note=$('[data-r4-note]');
 function scoped(){let list=all;const allowed=PRESET_TYPES[state.preset];if(allowed)list=list.filter(r=>allowed.includes(r.type));if(state.type)list=list.filter(r=>r.type===state.type);if(state.project)list=list.filter(r=>String(r.projectId||'')===String(state.project));if(state.month)list=list.filter(r=>String(r.period||r.date||'').slice(0,7)===state.month);if(state.global)list=list.filter(r=>searchText(r).includes(state.global));return list}
 function cols(){return columns(state.preset,state.type,scoped())}
 function filtered(){const cs=cols();return scoped().filter(r=>Object.entries(state.filters).every(([k,q])=>{if(!q)return true;const c=cs.find(x=>x.key===k);return c&&val(r,c).toLowerCase().includes(q)}))}
 function draw(){const cs=cols(),list=filtered();count.textContent=list.length;note.textContent=state.type?`${cs.length} columnas · incluye campos reales de ${state.type}`:`Vista ${state.preset}`;head.innerHTML=`<tr>${cs.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr><tr class="r4-filters">${cs.map(c=>`<th><input class="r4-filter" data-r4-filter="${esc(c.key)}" value="${esc(state.filters[c.key]||'')}" placeholder="Filtrar…"></th>`).join('')}</tr>`;body.innerHTML=list.map(r=>`<tr class="r4-row" data-r4-id="${all.indexOf(r)}">${cs.map(c=>`<td title="${esc(val(r,c))}">${display(r,c)}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${Math.max(1,cs.length)}"><div class="empty">No hay registros con estos filtros.</div></td></tr>`;head.querySelectorAll('[data-r4-filter]').forEach(x=>x.oninput=()=>{state.filters[x.dataset.r4Filter]=x.value.toLowerCase();draw()});body.querySelectorAll('[data-r4-id]').forEach(tr=>tr.onclick=()=>open(all[Number(tr.dataset.r4Id)]))}
 function refreshPreset(){document.querySelectorAll('[data-r4-preset]').forEach(b=>b.classList.toggle('active',b.dataset.r4Preset===state.preset));const allowed=PRESET_TYPES[state.preset];[...typeSel.options].forEach(o=>{o.hidden=!!allowed&&o.value&&!allowed.includes(o.value)});if(allowed&&state.type&&!allowed.includes(state.type)){state.type='';typeSel.value=''}state.filters={};draw()}
 document.querySelectorAll('[data-r4-preset]').forEach(b=>b.onclick=()=>{state.preset=b.dataset.r4Preset;localStorage.setItem('iriarte_records_preset',state.preset);refreshPreset()});typeSel.onchange=()=>{state.type=typeSel.value;state.filters={};draw()};projectSel.onchange=()=>{state.project=projectSel.value;draw()};month.onchange=()=>{state.month=month.value;draw()};global.oninput=()=>{state.global=global.value.toLowerCase();draw()};refreshPreset()
}
window.iriarteRenderRecordsV4=render;
window.renderIriarteRecords=render;
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{if(window.APP?.route==='registros')render()},60)}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',schedule);window.addEventListener('hashchange',schedule);document.addEventListener('iriarte:route',schedule);
})();
