// Iriarte ERP V2 · finanzas, informes y control de integridad
(function(){
'use strict';
const db=()=>window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(v||0)||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
const pct=v=>`${num(v).toLocaleString('es-ES',{minimumFractionDigits:0,maximumFractionDigits:1})}%`;
const month=v=>v?new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date(v+'T12:00:00')):'—';
const today=()=>new Date().toISOString().slice(0,10);
const issued=x=>!['borrador','anulada'].includes(String(x?.estado||'borrador').toLowerCase());
const activePurchase=x=>String(x?.estado||'').toLowerCase()!=='anulada';
const sum=(a,f)=>(a||[]).reduce((s,x)=>s+num(f(x)),0);
let token=0,loading=false;
function integrityPanel(i={}){
 const labels=[
  ['Facturas sin proyecto','facturas_sin_proyecto'],['Compras sin proyecto','compras_sin_proyecto'],['Horas sin proyecto','horas_sin_proyecto'],
  ['Documentos sin proyecto','documentos_sin_proyecto'],['Movimientos sin proyecto','movimientos_sin_proyecto'],['Visitas de obra sin proyecto','visitas_sin_proyecto'],
  ['Tareas de obra sin proyecto','tareas_sin_proyecto'],['Incidencias de obra sin proyecto','incidencias_sin_proyecto'],['Facturas con líneas y total 0','facturas_total_cero_con_lineas'],
  ['Facturas cobradas incoherentes','facturas_cobradas_incoherentes'],['Compras pagadas incoherentes','compras_pagadas_incoherentes'],
  ['Facturas borrador con cobros','facturas_borrador_con_cobros'],['Facturas sobrecobradas','facturas_sobrecobradas'],['Compras sobrepagadas','compras_sobrepagadas'],
  ['Documento de factura con proyecto distinto','documentos_factura_proyecto_incoherente'],['Documento de compra con proyecto distinto','documentos_compra_proyecto_incoherente'],
  ['Movimiento de factura con proyecto distinto','movimientos_factura_proyecto_incoherente'],['Movimiento de compra con proyecto distinto','movimientos_compra_proyecto_incoherente'],
  ['Cobros conciliados sin cobro real','cobros_conciliados_sin_cobro'],['Pagos conciliados sin pago real','pagos_conciliados_sin_pago'],
  ['Fases facturadas sin factura','fases_facturadas_sin_factura'],['Fases pendientes con factura ya emitida','fases_pendientes_con_factura_emitida'],['Fases con factura y estado incoherente','fases_con_factura_estado_incoherente'],['Presupuestos convertidos sin proyecto','presupuestos_proyecto_sin_vinculo']
 ];
 const issues=labels.reduce((a,[,k])=>a+num(i[k]),0);
 if(!issues)return `<div class="notice" style="margin-top:14px;background:#e8f0e5;color:#30482b"><b>Control de integridad: correcto.</b> No se han detectado incoherencias en vínculos, estados, documentos, conciliación ni totales críticos.</div>`;
 return `<div class="card panel" style="margin-top:14px"><h3>Control de integridad</h3><div class="notice" style="background:#fff2d8;color:#745b24;margin-bottom:10px"><b>${issues} incidencias detectadas.</b> Conviene corregirlas antes de utilizar los informes como cierre definitivo.</div><div class="grid cols-4">${labels.filter(([,k])=>num(i[k])>0).map(([l,k])=>`<div class="info"><small>${esc(l)}</small><b class="negative">${num(i[k])}</b></div>`).join('')}</div></div>`;
}
function openProject(id){if(!id)return;window.APP.sel.project=id;localStorage.setItem('iriarte_open_project',id);if(window.iriarteRoute)window.iriarteRoute('proyectos');else location.hash='#proyectos'}
function openRecord(type,id){if(window.iriarteOpenRecord)return window.iriarteOpenRecord(type,id);const route={invoice:'facturas',purchase:'compras'}[type];if(route){localStorage.setItem(`iriarte_open_${type}`,id);window.iriarteRoute?.(route)}}
function pendingBy(rows,key,id){return sum(rows.filter(x=>String(x[key])===String(id)),x=>x.importe)}
function maturityPanel(invoices,purchases,cobros,pagos){
 const t=today();
 const inv=invoices.map(x=>({...x,_pending:Math.max(0,num(x.total)-pendingBy(cobros,'factura_id',x.id))})).filter(x=>x._pending>.009&&x.fecha_vencimiento&&x.fecha_vencimiento<t).sort((a,b)=>String(a.fecha_vencimiento).localeCompare(String(b.fecha_vencimiento)));
 const pur=purchases.map(x=>({...x,_pending:Math.max(0,num(x.total)-pendingBy(pagos,'compra_id',x.id))})).filter(x=>x._pending>.009&&x.fecha_vencimiento&&x.fecha_vencimiento<t).sort((a,b)=>String(a.fecha_vencimiento).localeCompare(String(b.fecha_vencimiento)));
 const invAmount=sum(inv,x=>x._pending),purAmount=sum(pur,x=>x._pending);
 return `<div class="card panel" style="margin-top:14px"><h3>Vencimientos</h3><div class="grid cols-4"><div class="info"><small>Facturas vencidas</small><b class="${inv.length?'negative':''}">${inv.length}</b></div><div class="info"><small>Cobro vencido</small><b class="${invAmount?'negative':''}">${money(invAmount)}</b></div><div class="info"><small>Compras vencidas</small><b class="${pur.length?'negative':''}">${pur.length}</b></div><div class="info"><small>Pago vencido</small><b class="${purAmount?'negative':''}">${money(purAmount)}</b></div></div><div class="grid cols-2" style="margin-top:12px"><div><h4 style="margin:0 0 8px">Cobros vencidos</h4>${inv.length?`<div class="table-wrap"><table class="table"><tr><th>Vence</th><th>Factura</th><th>Pendiente</th></tr>${inv.map(x=>`<tr data-fin-record="invoice:${esc(x.id)}" style="cursor:pointer"><td>${esc(x.fecha_vencimiento)}</td><td><b>${esc(x.numero||'Sin número')}</b></td><td class="negative"><b>${money(x._pending)}</b></td></tr>`).join('')}</table></div>`:'<div class="empty">No hay facturas vencidas pendientes.</div>'}</div><div><h4 style="margin:0 0 8px">Pagos vencidos</h4>${pur.length?`<div class="table-wrap"><table class="table"><tr><th>Vence</th><th>Compra</th><th>Pendiente</th></tr>${pur.map(x=>`<tr data-fin-record="purchase:${esc(x.id)}" style="cursor:pointer"><td>${esc(x.fecha_vencimiento)}</td><td><b>${esc(x.numero_factura||x.concepto||'Compra')}</b></td><td class="negative"><b>${money(x._pending)}</b></td></tr>`).join('')}</table></div>`:'<div class="empty">No hay compras vencidas pendientes.</div>'}</div></div></div>`;
}
function categoriesPanel(gastos){
 const m=new Map();(gastos||[]).forEach(x=>{const k=String(x.categoria||'Sin categoría').trim()||'Sin categoría',v=m.get(k)||{base:0,total:0,count:0};v.base+=num(x.base);v.total+=num(x.total);v.count++;m.set(k,v)});
 const rows=[...m.entries()].sort((a,b)=>b[1].base-a[1].base),total=sum(gastos,x=>x.base);
 return `<div class="card panel"><h3>Gastos generales por categoría</h3>${rows.length?`<div class="table-wrap"><table class="table"><tr><th>Categoría</th><th>Registros</th><th>Base</th><th>% gastos</th><th>Total c/IVA</th></tr>${rows.map(([k,v])=>`<tr><td><b>${esc(k)}</b></td><td>${v.count}</td><td>${money(v.base)}</td><td>${pct(total?v.base/total*100:0)}</td><td>${money(v.total)}</td></tr>`).join('')}</table></div>`:'<div class="empty">No hay gastos generales registrados.</div>'}</div>`;
}
async function render(){
 if(window.APP?.route!=='informes'||loading)return;const view=$('#app-view');if(!view||view.querySelector('#reports-v2'))return;
 const my=++token;loading=true;
 view.innerHTML='<div class="page-head"><h1>Finanzas</h1></div><div class="card panel"><div class="empty">Calculando…</div></div>';
 try{
  const [{data:projects,error:e1},{data:months,error:e2},{data:integrity,error:e3}]=await Promise.all([
   db().from('v_proyectos_resumen').select('*'),
   db().from('v_finanzas_mensual').select('*').order('mes',{ascending:false}).limit(24),
   db().from('v_control_integridad_erp').select('*').maybeSingle()
  ]);if(my!==token||window.APP?.route!=='informes')return;
  if(e1||e2){view.innerHTML=`<div id="reports-v2"><div class="page-head"><h1>Finanzas</h1></div><div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(e1?.message||e2?.message||'No se pudieron cargar los informes financieros')}</div></div>`;return}
  const D=window.APP.data,unlinked={facturas:(D.facturas||[]).filter(x=>!x.proyecto_id).length,compras:(D.compras||[]).filter(x=>!x.proyecto_id).length,horas:(D.horas||[]).filter(x=>!x.proyecto_id).length,movs:(D.movs||[]).filter(x=>!x.proyecto_id).length};
  const overheadFor=pid=>(D.gastos||[]).filter(g=>String(g.proyecto_id||'')===String(pid)).reduce((a,g)=>a+num(g.base),0);
  const totalMargin=(projects||[]).reduce((a,x)=>a+num(x.margen_directo),0),projectInv=(projects||[]).reduce((a,x)=>a+num(x.ingresos_facturados),0),projectCosts=(projects||[]).reduce((a,x)=>a+num(x.costes_compras)+num(x.coste_horas),0),linkedOverhead=(projects||[]).reduce((a,x)=>a+overheadFor(x.proyecto_id),0),totalOverhead=sum(D.gastos,x=>x.base),result=totalMargin-totalOverhead;
  const invoices=(D.facturas||[]).filter(issued),purchases=(D.compras||[]).filter(activePurchase),invoiceIds=new Set(invoices.map(x=>String(x.id))),purchaseIds=new Set(purchases.map(x=>String(x.id))),cobros=(D.cobros||[]).filter(x=>invoiceIds.has(String(x.factura_id))),pagos=(D.pagos||[]).filter(x=>purchaseIds.has(String(x.compra_id))),collected=sum(cobros,x=>x.importe),paid=sum(pagos,x=>x.importe),invoiceTotal=sum(invoices,x=>x.total),purchaseTotal=sum(purchases,x=>x.total),invoiceBase=sum(invoices,x=>x.base),purchaseBase=sum(purchases,x=>x.base),pendingCollect=Math.max(0,invoiceTotal-collected),pendingPay=Math.max(0,purchaseTotal-paid);
  const outputVat=sum(invoices,x=>x.iva_importe),inputVatPurchases=sum(purchases,x=>x.iva_importe),inputVatOverheads=sum(D.gastos,x=>x.iva_importe),inputVat=inputVatPurchases+inputVatOverheads,vatBalance=outputVat-inputVat,irpf=sum(invoices,x=>x.irpf_importe);
  const marginPct=invoiceBase?totalMargin/invoiceBase*100:0,collectionPct=invoiceTotal?collected/invoiceTotal*100:0,paymentPct=purchaseTotal?paid/purchaseTotal*100:0,overheadPct=invoiceBase?totalOverhead/invoiceBase*100:0,directCostPct=invoiceBase?projectCosts/invoiceBase*100:0;
  view.innerHTML=`<div id="reports-v2"><div class="page-head"><div><h1>Finanzas</h1><p style="color:var(--muted);margin:4px 0 0">Rentabilidad, cobros y pagos, impuestos operativos, vencimientos, categorías, evolución y control de integridad.</p></div></div>
  <div class="grid cols-4"><div class="card kpi"><small>Facturado base por proyectos</small><strong>${money(projectInv)}</strong></div><div class="card kpi"><small>Costes directos</small><strong>${money(projectCosts)}</strong></div><div class="card kpi"><small>Margen directo</small><strong class="${totalMargin<0?'negative':'positive'}">${money(totalMargin)}</strong></div><div class="card kpi"><small>Resultado tras gastos generales</small><strong class="${result<0?'negative':'positive'}">${money(result)}</strong></div></div>
  <div class="grid cols-4" style="margin-top:14px"><div class="card kpi"><small>Cobrado</small><strong>${money(collected)}</strong></div><div class="card kpi"><small>Pendiente de cobro</small><strong class="${pendingCollect>0?'negative':'positive'}">${money(pendingCollect)}</strong></div><div class="card kpi"><small>Pagado a proveedores</small><strong>${money(paid)}</strong></div><div class="card kpi"><small>Pendiente de pago</small><strong class="${pendingPay>0?'negative':'positive'}">${money(pendingPay)}</strong></div></div>
  <div class="grid cols-2" style="margin-top:14px"><div class="card panel"><h3>Impuestos registrados</h3><div class="grid cols-2"><div class="info"><small>IVA repercutido</small><b>${money(outputVat)}</b></div><div class="info"><small>IVA soportado compras</small><b>${money(inputVatPurchases)}</b></div><div class="info"><small>IVA soportado gastos generales</small><b>${money(inputVatOverheads)}</b></div><div class="info"><small>Saldo IVA estimado</small><b class="${vatBalance>0?'negative':'positive'}">${money(vatBalance)}</b></div><div class="info"><small>IRPF retenido en facturas</small><b>${money(irpf)}</b></div></div><p style="font-size:11px;color:var(--muted);margin:12px 0 0">Cálculo operativo a partir de los documentos registrados. No sustituye la liquidación fiscal ni contempla ajustes externos al ERP.</p></div><div class="card panel"><h3>Ratios financieros</h3><div class="grid cols-2"><div class="info"><small>Margen directo / facturación</small><b>${pct(marginPct)}</b></div><div class="info"><small>Coste directo / facturación</small><b>${pct(directCostPct)}</b></div><div class="info"><small>Cobrado / facturado total</small><b>${pct(collectionPct)}</b></div><div class="info"><small>Pagado / compras total</small><b>${pct(paymentPct)}</b></div><div class="info"><small>Gastos generales / facturación</small><b>${pct(overheadPct)}</b></div></div></div></div>
  <div class="notice" style="margin-top:14px"><b>Gastos generales vinculados:</b> ${money(linkedOverhead)} directamente a proyectos · <b>Gastos generales totales:</b> ${money(totalOverhead)}.</div>
  ${maturityPanel(invoices,purchases,cobros,pagos)}
  ${e3?`<div class="notice" style="margin-top:14px;background:#fff2d8;color:#745b24"><b>Control de integridad no disponible:</b> ${esc(e3.message)}</div>`:integrityPanel(integrity||{})}
  <div class="notice" style="margin-top:14px"><b>Registros pendientes de atribución:</b> facturas sin proyecto: ${unlinked.facturas} · compras sin proyecto: ${unlinked.compras} · horas sin proyecto: ${unlinked.horas} · movimientos bancarios sin proyecto: ${unlinked.movs}. Los registros no vinculados no se atribuyen a la rentabilidad de un proyecto.</div>
  <div class="card panel" style="margin-top:14px"><h3>Rentabilidad por proyecto</h3><p style="font-size:11px;color:var(--muted)">Pulsa un proyecto para abrir su ficha. El margen directo solo descuenta compras y horas; los gastos generales vinculados aparecen separados.</p>${projects?.length?`<div class="table-wrap"><table class="table"><tr><th>Proyecto</th><th>Cliente</th><th>Facturado base</th><th>Cobrado</th><th>Compras</th><th>Horas</th><th>Coste horas</th><th>Margen directo</th><th>Margen %</th><th>Gastos vinculados</th><th>Resultado tras vinculados</th></tr>${projects.map(x=>{const p=num(x.ingresos_facturados)?num(x.margen_directo)/num(x.ingresos_facturados)*100:0,oh=overheadFor(x.proyecto_id),after=num(x.margen_directo)-oh;return `<tr data-fin-project="${esc(x.proyecto_id||'')}" style="cursor:${x.proyecto_id?'pointer':'default'}"><td><b>${esc(x.proyecto||'')}</b></td><td>${esc(x.cliente||'—')}</td><td>${money(x.ingresos_facturados)}</td><td>${money(x.cobrado)}</td><td>${money(x.costes_compras)}</td><td>${num(x.horas).toLocaleString('es-ES',{maximumFractionDigits:1})} h</td><td>${money(x.coste_horas)}</td><td class="${num(x.margen_directo)<0?'negative':'positive'}"><b>${money(x.margen_directo)}</b></td><td>${pct(p)}</td><td>${money(oh)}</td><td class="${after<0?'negative':'positive'}"><b>${money(after)}</b></td></tr>`}).join('')}</table></div>`:'<div class="empty">Aún no hay proyectos para analizar.</div>'}</div>
  <div class="grid cols-2" style="margin-top:14px">${categoriesPanel(D.gastos)}<div class="card panel"><h3>Evolución mensual</h3><p style="font-size:11px;color:var(--muted)">Resultado mensual = facturación base emitida − compras base − gastos generales base. El coste de horas se mantiene separado en la rentabilidad directa por proyecto.</p>${months?.length?`<div class="table-wrap"><table class="table"><tr><th>Mes</th><th>Facturado base</th><th>Cobrado</th><th>Compras base</th><th>Pagado proveedores</th><th>Gastos generales</th><th>Resultado antes coste personal</th></tr>${months.map(x=>`<tr><td><b>${esc(month(x.mes))}</b></td><td>${money(x.facturado_base)}</td><td>${money(x.cobrado)}</td><td>${money(x.compras_base)}</td><td>${money(x.pagado_proveedores)}</td><td>${money(x.gastos_generales_base)}</td><td class="${num(x.resultado_antes_coste_personal)<0?'negative':'positive'}"><b>${money(x.resultado_antes_coste_personal)}</b></td></tr>`).join('')}</table></div>`:'<div class="empty">No hay meses con actividad todavía.</div>'}</div></div></div>`;
  view.querySelectorAll('[data-fin-project]').forEach(r=>r.onclick=()=>{if(r.dataset.finProject)openProject(r.dataset.finProject)});
  view.querySelectorAll('[data-fin-record]').forEach(r=>r.onclick=()=>{const [type,id]=r.dataset.finRecord.split(':');openRecord(type,id)});
 }finally{loading=false}
}
function schedule(){setTimeout(render,80)}
new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',schedule);window.addEventListener('load',schedule);
})();