// Iriarte ERP V2 · ronda de mejora UX, navegación y documentos
(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
const today=()=>new Date().toISOString().slice(0,10);
const db=()=>window.__iriarteDb;
let timer;
function sum(a,f){return (a||[]).reduce((s,x)=>s+num(f(x)),0)}
function project(){const S=window.APP;return (S?.data?.proyectos||[]).find(x=>String(x.id)===String(S?.sel?.project))||null}
function projectName(id){return (window.APP?.data?.proyectos||[]).find(x=>String(x.id)===String(id))?.nombre||'—'}
function clientName(id){return (window.APP?.data?.clientes||[]).find(x=>String(x.id)===String(id))?.nombre||'—'}
function supplierName(id){return (window.APP?.data?.proveedores||[]).find(x=>String(x.id)===String(id))?.nombre||'—'}
function modal(title,html){const root=$('#modal-root');if(!root)return;root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="width:min(1050px,96vw)"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-r1-close>Cerrar</button></div><div class="modal-body">${html}</div></div></div>`;root.querySelector('[data-r1-close]').onclick=()=>root.innerHTML='';root.querySelector('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)root.innerHTML=''}}
function formModal(title,html,onSave,save='Guardar'){
 const root=$('#modal-root');if(!root)return;root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-r1-close>Cerrar</button></div><form id="r1-form"><div class="modal-body">${html}<div id="r1-error"></div></div><div class="modal-foot"><button class="btn" type="button" data-r1-close>Cancelar</button><button class="btn primary" type="submit">${esc(save)}</button></div></form></div></div>`;
 const close=()=>root.innerHTML='';root.querySelectorAll('[data-r1-close]').forEach(b=>b.onclick=close);$('#r1-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const ok=await onSave(Object.fromEntries(new FormData(e.currentTarget).entries()),e.currentTarget);if(ok!==false){close();if(window.reloadIriarte)await window.reloadIriarte()}}catch(err){$('#r1-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`}finally{b.disabled=false}}
}
function openRecord(type,id){if(window.iriarteOpenRecord)return window.iriarteOpenRecord(type,id);if(!id)return;localStorage.setItem('iriarte_open_'+type,id);const route={project:'proyectos',invoice:'facturas',budget:'presupuestos',purchase:'compras',document:'documentos'}[type];if(route&&window.iriarteRoute)window.iriarteRoute(route)}

function ensureNav(){
 const nav=$('#main-nav');if(!nav)return;
 const bank=nav.querySelector('[data-route="finanzas"]');if(bank){bank.textContent='Banco';bank.title='Banco'}
 const finance=nav.querySelector('[data-route="informes"]');if(finance){finance.textContent='Finanzas';finance.title='Finanzas e informes'}
 if(!nav.querySelector('[data-r1-registers]')){const a=document.createElement('a');a.className='nav-item';a.href='#registros';a.textContent='Registros';a.dataset.r1Registers='1';if(finance)nav.insertBefore(a,finance);else nav.appendChild(a)}
 if(location.hash==='#registros')nav.querySelectorAll('.nav-item').forEach(a=>a.classList.toggle('active',!!a.dataset.r1Registers));
}

function profitability(){
 const S=window.APP,p=project();if(!S||!p)return;
 const issued=(S.data.facturas||[]).filter(x=>String(x.proyecto_id)===String(p.id)&&!['borrador','anulada'].includes(String(x.estado||'borrador').toLowerCase()));
 const purchases=(S.data.compras||[]).filter(x=>String(x.proyecto_id)===String(p.id)&&String(x.estado||'').toLowerCase()!=='anulada');
 const hours=(S.data.horas||[]).filter(x=>String(x.proyecto_id||x.project_id)===String(p.id));
 const overheads=(S.data.gastos||[]).filter(x=>String(x.proyecto_id||'')===String(p.id));
 const invoiceIds=new Set(issued.map(x=>String(x.id))),purchaseIds=new Set(purchases.map(x=>String(x.id)));
 const collections=(S.data.cobros||[]).filter(x=>invoiceIds.has(String(x.factura_id))),payments=(S.data.pagos||[]).filter(x=>purchaseIds.has(String(x.compra_id)));
 const invBase=sum(issued,x=>x.base),invTotal=sum(issued,x=>x.total),purBase=sum(purchases,x=>x.base),purTotal=sum(purchases,x=>x.total),hourCost=sum(hours,x=>num(x.horas)*num(x.coste_hora)),oh=sum(overheads,x=>x.base),col=sum(collections,x=>x.importe),paid=sum(payments,x=>x.importe),margin=invBase-purBase-hourCost,result=margin-oh,pct=invBase?margin/invBase*100:0;
 const budgets=(S.data.presupuestos||[]).filter(x=>String(x.proyecto_id||'')===String(p.id));
 const metric=(l,v,c='')=>`<div class="info"><small>${esc(l)}</small><b class="${c}">${v}</b></div>`;
 modal(`Rentabilidad · ${p.nombre}`,`<div class="round-profit-grid">${metric('Facturado base',money(invBase))}${metric('Facturado total',money(invTotal))}${metric('Compras base',money(purBase))}${metric('Coste de horas',money(hourCost))}${metric('Margen directo',money(margin),margin<0?'negative':'positive')}${metric('Margen directo %',pct.toLocaleString('es-ES',{maximumFractionDigits:1})+'%',margin<0?'negative':'positive')}${metric('Gastos vinculados',money(oh))}${metric('Resultado tras vinculados',money(result),result<0?'negative':'positive')}${metric('Cobrado',money(col))}${metric('Pendiente de cobro',money(Math.max(0,invTotal-col)),invTotal-col>.01?'negative':'positive')}${metric('Pagado a proveedores',money(paid))}${metric('Pendiente de pago',money(Math.max(0,purTotal-paid)),purTotal-paid>.01?'negative':'positive')}</div><div class="notice round-profit-section"><b>${budgets.length} presupuesto${budgets.length===1?'':'s'} vinculado${budgets.length===1?'':'s'}.</b> La rentabilidad directa se calcula con facturas emitidas, compras activas y coste de horas. Los gastos vinculados se muestran por separado.</div><div class="grid cols-2 round-profit-section"><div class="card panel"><h3>Facturas emitidas</h3>${issued.length?`<div class="table-wrap"><table class="table"><tr><th>Factura</th><th>Fecha</th><th>Base</th><th>Total</th></tr>${issued.map(x=>`<tr class="project-record-link" data-round-record="invoice:${esc(x.id)}"><td><b>${esc(x.numero||'—')}</b></td><td>${esc(x.fecha||'')}</td><td>${money(x.base)}</td><td>${money(x.total)}</td></tr>`).join('')}</table></div>`:'<div class="empty">Sin facturas emitidas.</div>'}</div><div class="card panel"><h3>Costes directos</h3>${purchases.length?`<div class="table-wrap"><table class="table"><tr><th>Compra</th><th>Proveedor</th><th>Base</th><th>Total</th></tr>${purchases.map(x=>`<tr class="project-record-link" data-round-record="purchase:${esc(x.id)}"><td><b>${esc(x.numero_factura||x.concepto||'Compra')}</b></td><td>${esc(supplierName(x.proveedor_id))}</td><td>${money(x.base)}</td><td>${money(x.total)}</td></tr>`).join('')}</table></div>`:'<div class="empty">Sin compras.</div>'}<div style="margin-top:10px" class="info">Horas: <b>${sum(hours,x=>x.horas).toLocaleString('es-ES',{maximumFractionDigits:1})} h · ${money(hourCost)}</b></div></div></div>`)
}

function projectRecords(){
 const S=window.APP,p=project(),detail=$('.card.detail');if(!S||!p||!detail)return;
 const sets={
  'Presupuestos':(S.data.presupuestos||[]).filter(x=>String(x.proyecto_id||'')===String(p.id)).map(x=>['budget',x.id]),
  'Facturas':(S.data.facturas||[]).filter(x=>String(x.proyecto_id||'')===String(p.id)).map(x=>['invoice',x.id]),
  'Compras':(S.data.compras||[]).filter(x=>String(x.proyecto_id||'')===String(p.id)).map(x=>['purchase',x.id]),
  'Documentos':(S.data.docs||[]).filter(x=>String(x.proyecto_id||'')===String(p.id)).map(x=>['document',x.id])
 };
 detail.querySelectorAll('.card.panel').forEach(panel=>{const title=panel.querySelector('h3')?.textContent.trim(),rows=sets[title];if(!rows)return;panel.querySelectorAll(':scope > .master-item').forEach((el,i)=>{if(!rows[i])return;el.classList.add('project-record-link');el.dataset.roundRecord=rows[i][0]+':'+rows[i][1]})});
 const flow=detail.querySelector('.flow');if(flow){const rent=flow.querySelector('[data-project-nav="finanzas"]');if(rent){rent.textContent='Rentabilidad';rent.dataset.roundProfit='1'}const cli=flow.querySelector('[data-project-nav="clientes"]');if(cli)cli.dataset.roundClient='1';const bud=flow.querySelector('[data-project-nav="presupuestos"]');if(bud)bud.dataset.roundBudget='1'}
 const hub=$('#project-hub-v2');if(hub){hub.querySelectorAll('[data-hub-route="finanzas"]').forEach(b=>{b.textContent='Rentabilidad';b.dataset.roundProfit='1'})}
}

function createWorkRecord(kind){
 const S=window.APP,pid=S?.sel?.project||S?.data?.proyectos?.[0]?.id;if(!pid)return alert('Selecciona primero un proyecto.');const opts=(S.data.proyectos||[]).map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(pid)?'selected':''}>${esc(p.nombre)}</option>`).join('');
 if(kind==='visit')formModal('Nueva visita de obra',`<div class="form-grid"><label>Proyecto<select name="project_id">${opts}</select></label><label>Fecha<input name="fecha" type="date" value="${today()}"></label><label class="full">Título<input name="titulo" value="Visita de obra"></label><label class="full">Descripción<textarea name="descripcion"></textarea></label><label class="full">Observaciones<textarea name="observaciones"></textarea></label></div>`,async f=>{const {error}=await db().from('obra_visitas').insert({project_id:f.project_id,fecha:f.fecha,titulo:f.titulo||'Visita de obra',descripcion:f.descripcion||null,observaciones:f.observaciones||null});if(error)throw error});
 if(kind==='task')formModal('Nueva tarea',`<div class="form-grid"><label>Proyecto<select name="project_id">${opts}</select></label><label>Prioridad<select name="prioridad"><option>baja</option><option selected>normal</option><option>alta</option><option>urgente</option></select></label><label>Fecha límite<input name="fecha_limite" type="date"></label><label class="full">Título<input name="titulo" required></label><label class="full">Descripción<textarea name="descripcion"></textarea></label></div>`,async f=>{const {error}=await db().from('obra_tareas').insert({project_id:f.project_id,titulo:f.titulo,descripcion:f.descripcion||null,prioridad:f.prioridad||'normal',fecha_limite:f.fecha_limite||null,estado:'pendiente'});if(error)throw error});
 if(kind==='incident')formModal('Nueva incidencia',`<div class="form-grid"><label>Proyecto<select name="project_id">${opts}</select></label><label>Prioridad<select name="prioridad"><option>baja</option><option selected>normal</option><option>alta</option><option>urgente</option></select></label><label>Tipo<input name="tipo"></label><label class="full">Título<input name="titulo" required></label><label class="full">Descripción<textarea name="descripcion"></textarea></label></div>`,async f=>{const {error}=await db().from('obra_incidencias').insert({project_id:f.project_id,titulo:f.titulo,descripcion:f.descripcion||null,tipo:f.tipo||null,prioridad:f.prioridad||'normal',estado:'abierta'});if(error)throw error});
}

function newBudget(){
 const S=window.APP;if(!S?.data?.proyectos?.length)return alert('Primero crea un proyecto. Los nuevos presupuestos se vinculan a un proyecto y a su cliente.');
 const pid=S.sel.project&&S.data.proyectos.some(x=>String(x.id)===String(S.sel.project))?S.sel.project:S.data.proyectos[0].id,p=S.data.proyectos.find(x=>String(x.id)===String(pid));
 const popts=S.data.proyectos.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(pid)?'selected':''} data-client="${esc(x.cliente_id||'')}">${esc(x.nombre)}</option>`).join(''),copts=S.data.clientes.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(p?.cliente_id)?'selected':''}>${esc(x.nombre)}</option>`).join('');
 formModal('Nuevo presupuesto',`<div class="form-grid"><label class="full">Proyecto<select name="proyecto_id" id="r1-budget-project" required>${popts}</select></label><label>Cliente<select name="cliente_id" id="r1-budget-client" required>${copts}</select></label><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label class="full">Nombre<input name="nombre" value="${esc(p?.nombre||'Nuevo presupuesto')}" required></label></div><div class="notice"><b>El presupuesto quedará vinculado desde el principio al proyecto seleccionado.</b> Ya no es necesario convertirlo después en proyecto.</div>`,async f=>{const pr=S.data.proyectos.find(x=>String(x.id)===String(f.proyecto_id)),cl=S.data.clientes.find(x=>String(x.id)===String(f.cliente_id));if(!pr||!cl)throw new Error('Selecciona proyecto y cliente.');const count=(S.data.presupuestos||[]).filter(x=>String(x.proyecto_id)===String(pr.id)).length+1,ref=(pr.codigo||pr.ref)?`${pr.codigo||pr.ref}-Pres.${count}`:null,row={nombre:f.nombre,name:f.nombre,kind:S.budgetKind||'obra',cliente_id:cl.id,proyecto_id:pr.id,fecha:f.fecha,date:f.fecha,numero:ref,ref,client:cl.nombre,address:pr.direccion||cl.direccion||'',estado:'borrador',status:'Borrador',phase:'Borrador',items:[],fee_lines:[],irpf_enabled:false,irpf_pct:15,base:0,total:0};const {data,error}=await db().from('presupuestos').insert(row).select('id').single();if(error)throw error;S.sel.project=pr.id;S.sel.budget=data.id;localStorage.setItem('iriarte_open_budget',data.id);setTimeout(()=>window.iriarteRoute&&window.iriarteRoute('presupuestos'),80)});
 setTimeout(()=>{const ps=$('#r1-budget-project'),cs=$('#r1-budget-client');if(ps&&cs)ps.onchange=()=>{const pr=S.data.proyectos.find(x=>String(x.id)===String(ps.value));if(pr?.cliente_id)cs.value=pr.cliente_id}},20)
}
function phaseNumber(p){const raw=String(p.fase||p.phase_number||p.ref||p.numero||'');const m=raw.match(/(?:pres\.?|fase\s*)?(\d+)$/i);return m?.[1]||p.fase||'1'}
function budgetGroups(p){const rows=(p.kind||'obra')==='honorarios'?(p.fee_lines||[]).map(x=>({code:'',section:'Honorarios',description:x.description||x.concepto||'',location:'',unit:'',qty:1,price:num(x.amount??x.importe),vat:num(x.vat??x.ivaPct??21)})):(p.items||[]).map(x=>({code:x.code||x.codigo||'',section:x.section||x.seccion||'General',description:x.description||x.descripcion||'',location:x.location||x.ubicacion||'',unit:x.unit||x.unidad||'ud',qty:num(x.qty??x.cantidad),price:num(x.price??x.precio),vat:num(x.vat??x.ivaPct??21)}));const groups=[];rows.forEach(x=>{let g=groups.find(y=>y.name===x.section);if(!g){g={name:x.section||'General',rows:[]};groups.push(g)}g.rows.push(x)});return groups}
function budgetDocument(){
 const S=window.APP;if(S?.route!=='presupuestos'||!['client','supplier'].includes(S.budgetView))return;const p=(S.data.presupuestos||[]).find(x=>String(x.id)===String(S.sel.budget)),content=$('.budget-content');if(!p||!content||content.querySelector('.budget-document-real'))return;
 const supplier=S.budgetView==='supplier',groups=budgetGroups(p),pr=(S.data.proyectos||[]).find(x=>String(x.id)===String(p.proyecto_id)),cl=(S.data.clientes||[]).find(x=>String(x.id)===String(p.cliente_id)),base=groups.reduce((a,g)=>a+sum(g.rows,x=>x.qty*x.price),0),vats={};groups.forEach(g=>g.rows.forEach(x=>{vats[x.vat]=(vats[x.vat]||0)+x.qty*x.price*x.vat/100}));const vatTotal=Object.values(vats).reduce((a,x)=>a+x,0),irpf=p.irpf_enabled?base*num(p.irpf_pct||15)/100:0,total=base+vatTotal-irpf,logo=window.IRIARTE_LOGO_DATA_URI||'';
 const sections=groups.map(g=>{const gb=sum(g.rows,x=>x.qty*x.price),gv=sum(g.rows,x=>x.qty*x.price*x.vat/100);return `<section class="budget-doc-section"><h3>${esc(g.name)}</h3><div style="overflow:auto"><table class="budget-doc-table"><thead><tr><th style="width:7%">Cód.</th><th style="width:6%">Ud.</th><th>Descripción</th><th style="width:18%">Ubicación</th><th class="n" style="width:8%">Unidades</th>${supplier?'':`<th class="n" style="width:11%">Precio ud.</th><th class="n" style="width:12%">Base imponible</th><th class="n" style="width:7%">IVA</th><th class="n" style="width:12%">Total c/IVA</th>`}</tr></thead><tbody>${g.rows.map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.unit)}</td><td>${esc(x.description)}</td><td class="loc">${esc(x.location)}</td><td class="n">${x.qty.toLocaleString('es-ES',{maximumFractionDigits:3})}</td>${supplier?'':`<td class="n">${money(x.price)}</td><td class="n">${money(x.qty*x.price)}</td><td class="n">${x.vat.toLocaleString('es-ES',{maximumFractionDigits:2})}%</td><td class="n"><b>${money(x.qty*x.price*(1+x.vat/100))}</b></td>`}</tr>`).join('')}${supplier?'':`<tr class="budget-doc-subtotal"><td colspan="6">Subtotal ${esc(g.name)}</td><td class="n">${money(gb)}</td><td></td><td class="n">${money(gb+gv)}</td></tr>`}</tbody></table></div></section>`}).join('');
 content.innerHTML=`<div class="budget-doc-actions no-print"><button class="btn primary" type="button" data-r1-print>Imprimir / guardar PDF</button></div><article class="budget-document-real ${supplier?'budget-doc-supplier':''}"><header class="budget-doc-header">${logo?`<img class="budget-doc-logo" src="${logo}" alt="Sonsoles Pérez Iriarte">`:''}<div class="budget-doc-title"><h1>${supplier?'Solicitud de precios a proveedor':esc(pr?.nombre||p.name||p.nombre||'Presupuesto')}</h1><p>${supplier?esc((pr?.nombre||p.name||'')+' — '+groups.map(g=>g.name).join(', ')):'Presupuesto de jardinería y paisajismo'}</p></div></header><div class="budget-doc-meta">${supplier?`<div><small>Proyecto</small><b>${esc(pr?.nombre||p.name||'—')}</b></div><div><small>Fecha</small><b>${esc(p.fecha||p.date||'')}</b></div><div><small>Ref.</small><b>${esc(pr?.codigo||p.ref||p.numero||'—')}</b></div>`:`<div><small>Cliente</small><b>${esc(cl?.nombre||p.client||'—')}</b></div><div><small>Dirección</small><b>${esc(pr?.direccion||p.address||cl?.direccion||'—')}</b></div><div><small>Fecha</small><b>${esc(p.fecha||p.date||'')}</b></div><div><small>Ref. proyecto</small><b>${esc(pr?.codigo||p.ref||p.numero||'—')}</b></div><div><small>Fase</small><b>${esc(phaseNumber(p))}</b></div>`}</div>${sections}${supplier?'':`<div class="budget-doc-totals"><div class="budget-doc-total-line"><span>Base imponible</span><b>${money(base)}</b></div>${Object.entries(vats).sort((a,b)=>Number(a[0])-Number(b[0])).map(([rate,val])=>`<div class="budget-doc-total-line"><span>IVA (${esc(rate)}%)</span><b>${money(val)}</b></div>`).join('')}${irpf?`<div class="budget-doc-total-line"><span>IRPF (${num(p.irpf_pct||15)}%)</span><b>− ${money(irpf)}</b></div>`:''}<div class="budget-doc-total-line grand"><span>Total</span><span>${money(total)}</span></div></div>`}<div class="budget-doc-note">${supplier?'Listado sin precios — Estudio de Jardinería y Paisajismo Sonsoles Pérez Iriarte.':'Presupuesto generado por el Estudio de Jardinería y Paisajismo Sonsoles Pérez Iriarte.'}</div></article>`;content.querySelector('[data-r1-print]').onclick=()=>window.print()
}

function normalizedRecords(){
 const D=window.APP?.data||{},rows=[];const add=(type,x,extra={})=>rows.push({type,id:x.id,date:extra.date??x.fecha??x.date??String(x.created_at||'').slice(0,10),ref:extra.ref??x.numero??x.codigo??x.numero_factura??x.referencia??'',entity:extra.entity??'',project:extra.project??projectName(x.proyecto_id||x.project_id),concept:extra.concept??x.concepto??x.nombre??x.name??x.titulo??x.descripcion??'',status:extra.status??x.estado??x.status??x.phase??'',base:extra.base??x.base??'',total:extra.total??x.total??'',raw:x,open:extra.open||null});
 (D.clientes||[]).forEach(x=>add('Cliente',x,{entity:x.nombre,project:'',concept:x.contacto||x.email||'',status:x.activo===false?'inactivo':'activo',open:['client',x.id]}));
 (D.proveedores||[]).forEach(x=>add('Proveedor',x,{entity:x.nombre,project:'',concept:x.contacto||x.tipo||'',status:x.activo===false?'inactivo':'activo',open:['supplier',x.id]}));
 (D.proyectos||[]).forEach(x=>add('Proyecto',x,{ref:x.codigo||'',entity:clientName(x.cliente_id),project:x.nombre,concept:x.direccion||'',open:['project',x.id]}));
 (D.presupuestos||[]).forEach(x=>add('Presupuesto',x,{ref:x.ref||x.numero||'',entity:clientName(x.cliente_id),project:projectName(x.proyecto_id),concept:x.name||x.nombre||'',open:['budget',x.id]}));
 (D.facturas||[]).forEach(x=>add('Factura',x,{entity:clientName(x.cliente_id),project:projectName(x.proyecto_id),open:['invoice',x.id]}));
 (D.compras||[]).forEach(x=>add('Compra',x,{entity:supplierName(x.proveedor_id),project:projectName(x.proyecto_id),open:['purchase',x.id]}));
 (D.cobros||[]).forEach(x=>add('Cobro',x,{ref:x.factura_id||'',project:projectName(x.proyecto_id),concept:x.concepto||'Cobro',total:x.importe}));
 (D.pagos||[]).forEach(x=>add('Pago',x,{ref:x.compra_id||'',project:projectName(x.proyecto_id),concept:x.concepto||'Pago',total:x.importe}));
 (D.horas||[]).forEach(x=>add('Horas',x,{entity:x.persona||'',project:projectName(x.proyecto_id||x.project_id),concept:x.concepto||x.descripcion||'',total:num(x.horas)*num(x.coste_hora)}));
 (D.visitas||[]).forEach(x=>add('Visita',x,{project:projectName(x.project_id),concept:x.titulo||x.descripcion||'',status:x.estado_obra||''}));
 (D.tareas||[]).forEach(x=>add('Tarea',x,{date:x.fecha_limite||String(x.created_at||'').slice(0,10),project:projectName(x.project_id),concept:x.titulo||'',status:x.estado||''}));
 (D.incidencias||[]).forEach(x=>add('Incidencia',x,{project:projectName(x.project_id),concept:x.titulo||'',status:x.estado||''}));
 (D.docs||[]).forEach(x=>add('Documento',x,{date:x.fecha_documento||String(x.created_at||'').slice(0,10),project:projectName(x.proyecto_id),concept:x.nombre||x.archivo_nombre||'',status:x.tipo||'',open:['document',x.id]}));
 (D.gastos||[]).forEach(x=>add('Gasto general',x,{project:projectName(x.proyecto_id),entity:x.proveedor||'',concept:x.concepto||x.categoria||''}));
 (D.movs||[]).forEach(x=>add('Banco',x,{project:projectName(x.proyecto_id),entity:x.cliente_proveedor||'',concept:x.concepto||x.concepto_banco||'',status:x.conciliado?'conciliado':'pendiente',total:x.total??x.importe}));
 return rows
}
function renderRegisters(){
 const view=$('#app-view'),S=window.APP;if(!view||!S)return;S.route='registros';ensureNav();if(view.querySelector('#round-registers'))return;
 const rows=normalizedRecords(),cols=[['type','Tipo'],['date','Fecha'],['ref','Referencia'],['entity','Cliente / proveedor'],['project','Proyecto'],['concept','Concepto'],['status','Estado'],['base','Base'],['total','Total']];
 view.innerHTML=`<div id="round-registers"><div class="page-head"><div><h1>Registros</h1><p style="color:var(--muted);margin:4px 0 0">Vista unificada de los registros del ERP. Puedes filtrar cualquier columna.</p></div></div><div class="records-toolbar"><input data-reg-global placeholder="Buscar en todos los campos…"><select data-reg-type><option value="">Todos los tipos</option>${[...new Set(rows.map(x=>x.type))].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select><div class="info"><small>Registros cargados</small><b data-reg-count>${rows.length}</b></div></div><div class="card panel table-wrap"><table class="table records-table"><thead><tr>${cols.map(c=>`<th>${esc(c[1])}</th>`).join('')}</tr><tr class="records-filter-row">${cols.map(c=>`<th><input data-reg-col="${c[0]}" placeholder="Filtrar…"></th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr data-reg-row="${i}" ${r.open?'class="project-record-link"':''}>${cols.map(([k])=>`<td data-v="${esc(String(r[k]??''))}">${['base','total'].includes(k)&&r[k]!==''?money(r[k]):esc(r[k]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;
 const filter=()=>{const global=($('[data-reg-global]')?.value||'').toLowerCase(),type=$('[data-reg-type]')?.value||'',filters={};$$('[data-reg-col]').forEach(x=>filters[x.dataset.regCol]=x.value.toLowerCase());let shown=0;$$('[data-reg-row]').forEach(tr=>{const r=rows[Number(tr.dataset.regRow)],all=Object.values(r).filter(v=>typeof v!=='object').join(' ').toLowerCase(),okGlobal=!global||all.includes(global),okType=!type||r.type===type,okCols=Object.entries(filters).every(([k,q])=>!q||String(r[k]??'').toLowerCase().includes(q)),show=okGlobal&&okType&&okCols;tr.style.display=show?'':'none';if(show)shown++});$('[data-reg-count]').textContent=shown};
 $('[data-reg-global]').oninput=filter;$('[data-reg-type]').onchange=filter;$$('[data-reg-col]').forEach(x=>x.oninput=filter);$$('[data-reg-row]').forEach(tr=>tr.onclick=()=>{const r=rows[Number(tr.dataset.regRow)];if(!r.open)return;const [type,id]=r.open;if(type==='client')window.iriarteOpenClientHub?.(id);else if(type==='supplier')window.iriarteOpenSupplierHub?.(id);else openRecord(type,id)})
}

function routeRegisters(){history.replaceState(null,'','#registros');renderRegisters()}
function decorate(){clearTimeout(timer);timer=setTimeout(()=>{ensureNav();if(location.hash==='#registros'){renderRegisters();return}projectRecords();budgetDocument()},60)}
new MutationObserver(decorate).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>{if(location.hash==='#registros')setTimeout(renderRegisters,20);else decorate()});window.addEventListener('load',decorate);

document.addEventListener('click',e=>{
 const reg=e.target.closest('[data-r1-registers]');if(reg){e.preventDefault();e.stopImmediatePropagation();routeRegisters();return}
 const rec=e.target.closest('[data-round-record]');if(rec){e.preventDefault();e.stopImmediatePropagation();const [type,id]=rec.dataset.roundRecord.split(':');$('#modal-root').innerHTML='';openRecord(type,id);return}
 const profit=e.target.closest('[data-round-profit]');if(profit){e.preventDefault();e.stopImmediatePropagation();profitability();return}
 const cli=e.target.closest('[data-round-client]');if(cli){e.preventDefault();e.stopImmediatePropagation();const p=project();if(p?.cliente_id)window.iriarteOpenClientHub?.(p.cliente_id);return}
 const bud=e.target.closest('[data-round-budget]');if(bud){e.preventDefault();e.stopImmediatePropagation();const p=project(),b=(window.APP?.data?.presupuestos||[]).find(x=>String(x.proyecto_id||'')===String(p?.id));if(b)openRecord('budget',b.id);else{window.APP.sel.project=p?.id||'';window.iriarteRoute?.('presupuestos')}return}
 const a=e.target.closest('[data-action]');if(a&&window.APP?.route==='obra'&&['new-visit','new-task','new-incident'].includes(a.dataset.action)){e.preventDefault();e.stopImmediatePropagation();createWorkRecord(a.dataset.action==='new-visit'?'visit':a.dataset.action==='new-task'?'task':'incident');return}
 if(a&&a.dataset.action==='new-budget'){e.preventDefault();e.stopImmediatePropagation();newBudget();return}
 if(a&&a.dataset.action==='budget-to-project'){e.preventDefault();e.stopImmediatePropagation();alert('Este flujo ya no es necesario: los nuevos presupuestos se crean vinculados directamente a un proyecto.');return}
},true);
})();
