// Iriarte ERP V2 · cobros y pagos pendientes
(function(){
'use strict';
const db=window.__iriarteDb;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const num=v=>Number(String(v??0).replace(',','.'))||0;
const money=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(num(v));
const today=()=>new Date().toISOString().slice(0,10);
const issuedInvoice=x=>!['borrador','anulada'].includes(String(x?.estado||'borrador').toLowerCase());
let timer;
function modal(title,html,onSave){const root=$('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><div class="grow"></div><button class="btn" type="button" data-w-close>Cerrar</button></div><form id="w-form"><div class="modal-body">${html}<div id="w-error"></div></div><div class="modal-foot"><button class="btn" type="button" data-w-close>Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form></div></div>`;const close=()=>root.innerHTML='';root.querySelectorAll('[data-w-close]').forEach(b=>b.onclick=close);$('#w-form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await onSave(Object.fromEntries(new FormData(e.currentTarget).entries()));close();if(window.reloadIriarte)await window.reloadIriarte();else location.reload()}catch(err){$('#w-error').innerHTML=`<div class="notice" style="background:#f6dfd7;color:#8f4d3c">${esc(err.message||err)}</div>`;e.submitter.disabled=false}}}
const pName=id=>(window.APP?.data?.proyectos||[]).find(x=>String(x.id)===String(id))?.nombre||'—';
const cName=id=>(window.APP?.data?.clientes||[]).find(x=>String(x.id)===String(id))?.nombre||'—';
const sName=id=>(window.APP?.data?.proveedores||[]).find(x=>String(x.id)===String(id))?.nombre||'—';
function paidInvoice(id){return (window.APP?.data?.cobros||[]).filter(x=>String(x.factura_id)===String(id)).reduce((a,x)=>a+num(x.importe),0)}
function paidPurchase(id){return (window.APP?.data?.pagos||[]).filter(x=>String(x.compra_id)===String(id)).reduce((a,x)=>a+num(x.importe),0)}

function collect(id){
 const x=(window.APP?.data?.facturas||[]).find(r=>String(r.id)===String(id));if(!x)return;
 if(!issuedInvoice(x)){alert('Esta factura todavía está en borrador o anulada. Emítela antes de registrar cobros.');return}
 const pending=Math.max(0,num(x.total)-paidInvoice(id));if(pending<=0.009){alert('Esta factura no tiene saldo pendiente de cobro.');return}
 modal('Registrar cobro',`<div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label>Importe<input name="importe" type="number" min="0.01" max="${pending.toFixed(2)}" step="0.01" value="${pending.toFixed(2)}" required><small style="display:block;color:var(--muted);margin-top:4px">Máximo pendiente: ${money(pending)}</small></label><label>Método<input name="metodo" placeholder="Transferencia, tarjeta…"></label><label>Cuenta<input name="cuenta"></label><label>Referencia<input name="referencia"></label><label class="full">Notas<textarea name="notas"></textarea></label></div>`,async f=>{const amount=num(f.importe);if(amount<=0)throw new Error('El importe del cobro debe ser mayor que cero.');if(amount>pending+0.009)throw new Error(`El cobro no puede superar el saldo pendiente de ${money(pending)}.`);const {error}=await db.from('cobros').insert({factura_id:id,fecha:f.fecha,importe:amount,metodo:f.metodo||null,cuenta:f.cuenta||null,referencia:f.referencia||null,notas:f.notas||null});if(error)throw error})
}
function pay(id){
 const x=(window.APP?.data?.compras||[]).find(r=>String(r.id)===String(id));if(!x)return;if(String(x.estado||'').toLowerCase()==='anulada'){alert('No se puede registrar un pago para una compra anulada.');return}
 const pending=Math.max(0,num(x.total)-paidPurchase(id));if(pending<=0.009){alert('Esta compra no tiene saldo pendiente de pago.');return}
 modal('Registrar pago',`<div class="form-grid"><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label>Importe<input name="importe" type="number" min="0.01" max="${pending.toFixed(2)}" step="0.01" value="${pending.toFixed(2)}" required><small style="display:block;color:var(--muted);margin-top:4px">Máximo pendiente: ${money(pending)}</small></label><label>Método<input name="metodo" placeholder="Transferencia, tarjeta…"></label><label>Cuenta<input name="cuenta"></label><label>Referencia<input name="referencia"></label><label class="full">Notas<textarea name="notas"></textarea></label></div>`,async f=>{const amount=num(f.importe);if(amount<=0)throw new Error('El importe del pago debe ser mayor que cero.');if(amount>pending+0.009)throw new Error(`El pago no puede superar el saldo pendiente de ${money(pending)}.`);const {error}=await db.from('pagos').insert({compra_id:id,fecha:f.fecha,importe:amount,metodo:f.metodo||null,cuenta:f.cuenta||null,referencia:f.referencia||null,notas:f.notas||null});if(error)throw error})
}

function enhanceInvoices(){if($('#wf-invoice-panel'))return;const view=$('#app-view');if(!view)return;const rows=(window.APP?.data?.facturas||[]).filter(issuedInvoice).filter(x=>num(x.total)-paidInvoice(x.id)>0.009);const panel=document.createElement('section');panel.id='wf-invoice-panel';panel.className='card panel';panel.style.marginTop='14px';panel.innerHTML=`<h3>Cobros pendientes</h3><p style="font-size:11px;color:var(--muted)">Solo aparecen facturas emitidas. Los borradores no forman parte de cuentas por cobrar.</p>${rows.length?`<div class="table-wrap"><table class="table"><tr><th>Factura</th><th>Cliente</th><th>Proyecto</th><th>Total</th><th>Cobrado</th><th>Pendiente</th><th></th></tr>${rows.map(x=>{const paid=paidInvoice(x.id);return `<tr><td><b>${esc(x.numero||'Sin número')}</b></td><td>${esc(cName(x.cliente_id))}</td><td>${esc(pName(x.proyecto_id))}</td><td>${money(x.total)}</td><td>${money(paid)}</td><td><b>${money(num(x.total)-paid)}</b></td><td><button class="btn primary" data-wf-collect="${x.id}">Registrar cobro</button></td></tr>`}).join('')}</table></div>`:'<div class="empty">No hay facturas emitidas pendientes de cobro.</div>'}`;view.appendChild(panel)}
function enhancePurchases(){if($('#wf-purchase-panel'))return;const view=$('#app-view');if(!view)return;const rows=(window.APP?.data?.compras||[]).filter(x=>String(x.estado||'').toLowerCase()!=='anulada').filter(x=>num(x.total)-paidPurchase(x.id)>0.009);const panel=document.createElement('section');panel.id='wf-purchase-panel';panel.className='card panel';panel.style.marginTop='14px';panel.innerHTML=`<h3>Pagos pendientes</h3>${rows.length?`<div class="table-wrap"><table class="table"><tr><th>Compra</th><th>Proveedor</th><th>Proyecto</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th></th></tr>${rows.map(x=>{const paid=paidPurchase(x.id);return `<tr><td><b>${esc(x.numero_factura||x.concepto||'Compra')}</b></td><td>${esc(sName(x.proveedor_id))}</td><td>${esc(pName(x.proyecto_id))}</td><td>${money(x.total)}</td><td>${money(paid)}</td><td><b>${money(num(x.total)-paid)}</b></td><td><button class="btn primary" data-wf-pay="${x.id}">Registrar pago</button></td></tr>`}).join('')}</table></div>`:'<div class="empty">No hay compras pendientes de pago.</div>'}`;view.appendChild(panel)}
function enhance(){clearTimeout(timer);timer=setTimeout(()=>{const r=window.APP?.route;if(r==='facturas')enhanceInvoices();else if(r==='compras')enhancePurchases()},80)}
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',enhance);window.addEventListener('load',enhance);
document.addEventListener('click',e=>{const b=e.target.closest('[data-wf-collect],[data-wf-pay]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.wfCollect)collect(b.dataset.wfCollect);else if(b.dataset.wfPay)pay(b.dataset.wfPay)},true);
})();
